### ISSUE TITLE
Automatically publish release artifacts to PyPI

### ISSUE THREAD

**Issue by terrytangyuan** [tensorflow/io#1004]
Currently the process to upload artifacts to PyPI is manual. We can consider doing this automatically and leverage something like [pypa/gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish) to publish them to PyPI as part of our GitHub Actions pipeline.

**Comment by yongtang** [comment]
We could automate though a manual trigger (vs. PR push) might still be needed.

The GitHub Actions is not super reliable, and PyPI.org has one issue of you cannot override once a pip is pushed. On PyPI.org you can only bump a new version. The problematic scenario is that when we push or tag a commit, GitHub Actions fails half way then we will have to abandon a version and skip to a new version.

**Comment by terrytangyuan** [comment]
Okay it seems like manual trigger is more reliable for now then.

**Comment by kvignesh1420** [comment]
@terrytangyuan @yongtang if we are continuing with the manual process, can this be closed?

**Comment by terrytangyuan** [comment]
Yes

**Comment by terrytangyuan** [comment]
Adding to @yongtang's point https://github.com/tensorflow/io/pull/1621#issuecomment-1030685498. 

Another check is to release the draft release to https://test.pypi.org/.

**Comment by kvignesh1420** [comment]
+1 for the draft approach in https://github.com/tensorflow/io/pull/1621#issuecomment-1030685498
