### ISSUE TITLE
Where is the `ossfs_op`  module?

### ISSUE THREAD

**Issue by Ouwen** [tensorflow/io#1013]
In the OSS directory [README.md](https://github.com/tensorflow/io/blob/master/tensorflow_io/core/kernels/oss/README.md), it states that 

> In Python code, import the extension `ossfs_op` module to use the extension with `gfile`. The files and directory URI should have `oss://` prefix, followed by an oss bucket name, access_id, access_key, oss_host, then the directory hierarchy.

> ```python
> import tensorflow as tf
> import tensorflow_io as tfio

> tf.io.gfile.mkdir('oss://${bucket}\x01id=${access_id}\x02key=${access_key}\x02host=${host}/test_dir')
> ```

Does the ossfs_op module need to be manually compiled?

Many thanks!

**Comment by yongtang** [comment]
@Ouwen ossfs is embedded in tfio automatically. So if you use the following:
```
import tensorflow_io as tfio
```

then you can just reading and writing oss like normal file system.
