### ISSUE TITLE
Decode JPEG2000 bytes

### ISSUE THREAD

**Issue by JeffreyWardman** [tensorflow/io#1017]
Considering there is work done on reading JPEG2000 bytes from DICOM files, may I recommend also including a tfio.image.decode_jpeg2000 function specifically for converting JPEG2000 image bytes into a UINT16 tensor?

**Comment by yongtang** [comment]
@JeffreyWardman Added a PR #1019 as a first step to support JPEG2000. The PR only adds jp2 uint8 support. Will expand if this does not cover the image you want to use.

**Comment by JeffreyWardman** [comment]
@yongtang Thanks. My images are UINT16. If the PR can be expanded to accommodate for UINT16 it would be very much appreciated.

**Comment by yongtang** [comment]
@JeffreyWardman Would you mind to share a small sample file of the single channel uint16 image?

**Comment by JeffreyWardman** [comment]
@yongtang here's some code to generate a sample JPEG2000. Ideally a file-like object would be fed into the function (rather than a file specifically).

```
import glymur
import numpy as np
import skimage.data

data = skimage.data.camera().astype(np.uint16)
jp2 = glymur.Jp2k('img.jp2', data=data, cratios=[20, 10, 1])
img = jp2[:]
thumbnail = jp2[::2, ::2]

```

**Comment by yongtang** [comment]
Added PR #1020 for uint16 support

**Comment by JeffreyWardman** [comment]
Thanks @yongtang :)
