### ISSUE TITLE
Branch that works with 2.3.0?

### ISSUE THREAD

**Issue by lminer** [tensorflow/io#1026]
Is there a branch that I can build that would work with tensorflow 2.3.0-rc0? Seems as if the nightly automatically installs tensorflow 2.2.0

**Comment by yongtang** [comment]
@lminer We are in the process of releasing another version (#1023) this week. Once the new version is released we will immediately switch to 2.3.0.

I would suggest you to hold for a day or two. Though I have a branch on my fork (https://github.com/yongtang/io/tree/nightly) which works with 2.3.0rc0, you can give it a try. Note the branch will be merged to master once version in #1023 is released.

**Comment by yongtang** [comment]
@lminer The master branch has been updated and now it depends on 2.3.0rc0+. Please give it a try.

I will close this issue for now, but feel free to re-open if you encounter any problems.
