### ISSUE TITLE
Apparent error in dbscale calculation

### ISSUE THREAD

**Issue by agkphysics** [tensorflow/io#1035]
## Versions
`tensorflow-io 0.14.0`

## Problem
I believe there is an error in the `tfio.experimental.audio.dbscale()` function:
https://github.com/tensorflow/io/blob/486aa0dd85433540e19fa474961bc04a8b75c3c0/tensorflow_io/core/python/experimental/audio_ops.py#L93

Subtracting ln(10) instead of dividing causes the resulting clipped spectrograms to look odd because they're clipped at the wrong value (bad on left, good on right, with clipping at -60dB relative):
![spectrogram_bad](https://user-images.githubusercontent.com/5217766/87259828-2cc5fa00-c502-11ea-9ad0-36fc92ed2d16.png) ![spectrogram_good](https://user-images.githubusercontent.com/5217766/87259823-28014600-c502-11ea-8e30-ad2d3c4dad97.png)

## Proposed Solution
I think it should be a division since `dbscale()` is supposed to use the base-10 logarithm per the docstring.
```python
    log_spec = 10.0 * (tf.math.log(power) / tf.math.log(10.0))
```

**Comment by yongtang** [comment]
Thanks @agkphysics for pointing this out! A PR has #1037 been created to fix the issue.
