### ISSUE TITLE
Incompatible data types while preparing KafkaIODataset

### ISSUE THREAD

**Issue by kvignesh1420** [tensorflow/io#1045]
Description:

In an attempt to run the following code snippet that has been taken from `class KafkaIODataset`, I encountered a type mismatch while concatenating datasets.

Steps to reproduce:

```ipython
In [23]: step = 1024
    ...: stop = 2000
    ...: indices_start = tf.data.Dataset.range(0, stop, step)
    ...: indices_stop = indices_start.skip(1).concatenate(
    ...:     tf.data.Dataset.from_tensor_slices([stop])
    ...: )
    ...: dataset = tf.data.Dataset.zip((indices_start, indices_stop))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-23-486defd7eedd> in <module>
      3 indices_start = tf.data.Dataset.range(0, stop, step)
      4 indices_stop = indices_start.skip(1).concatenate(
----> 5     tf.data.Dataset.from_tensor_slices([stop])
      6 )
      7 dataset = tf.data.Dataset.zip((indices_start, indices_stop))

~/.tf-venv/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py in concatenate(self, dataset)
   1027       Dataset: A `Dataset`.
   1028     """
-> 1029     return ConcatenateDataset(self, dataset)
   1030
   1031   def prefetch(self, buffer_size):

~/.tf-venv/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py in __init__(self, input_dataset, dataset_to_concatenate)
   3511       raise TypeError(
   3512           "Two datasets to concatenate have different types %s and %s" %
-> 3513           (output_types, get_legacy_output_types(dataset_to_concatenate)))
   3514
   3515     output_classes = get_legacy_output_classes(input_dataset)

TypeError: Two datasets to concatenate have different types <dtype: 'int64'> and <dtype: 'int32'>

In [24]: indices_start
Out[24]: <RangeDataset shapes: (), types: tf.int64>

In [25]: tf.data.Dataset.from_tensor_slices([2000])
Out[25]: <TensorSliceDataset shapes: (), types: tf.int32>
```

The `indices_start` and `tf.data.Dataset.from_tensor_slices([2000])` have a data type mismatch, which prevents the concatenation. 

Reference:
https://github.com/tensorflow/io/blob/98856494636097ec9f81ba4ff37da7c078f86125/tensorflow_io/core/python/ops/kafka_dataset_ops.py#L42-L47

**Comment by kvignesh1420** [comment]
@yongtang   setting the output_type in range Dataset to int32 should do the trick. Will raise PR for the same.

**Comment by yongtang** [comment]
@kvignesh1420 I think the issue is that the value passed to `from_tensor_slices` and to `range` are with python integers. Depending on the API, some will interprets  python integers as tf.int32 and some will assume tf.int64.

One way to avoid confusion is to explicitly pass tensors instead. In other words, `stop = tf.constant(1024, tf.int64)`, `step = tf.constant(1024, tf.int64)`.... That will help avoid the issue.

**Comment by kvignesh1420** [comment]
@yongtang right. I am adding the docstrings to avoid this confusion.
