### ISSUE TITLE
Bazel build fails inside development docker container

### ISSUE THREAD

**Issue by kvignesh1420** [tensorflow/io#1050]
While setting up the docker container for building tensorflow-io c++ packages, the following error was raised due to which the build fails.

Steps to reproduce:

```sh
$ docker build -f tools/dev/Dockerfile -t tfio-dev .
$ docker run -it --rm --net=host -v ${PWD}:/v -w /v tfio-dev

(tfio-dev) root@docker-desktop:/v$ ./configure.sh

(tfio-dev) root@docker-desktop:/v$ bazel build -c opt --copt=-march=native --copt=-fPIC -s --verbose_failures //tensorflow_io/...
```

It fails while building the `gstpufs` kernels.

Log in the attachment.

[build_error.log](https://github.com/tensorflow/io/files/4956125/build_error.log)

**Comment by BryanCutler** [comment]
I just built with the latest and it worked for me with the command:
```bash
bazel build --copt=-msse4.2 --copt=-mavx --compilation_mode=opt --verbose_failures --test_output=errors --crosstool_top=//third_party/toolchains/gcc7_manylinux2010:toolchain //tensorflow_io/...
```
could you try with these options?

I just noticed that perhaps we should be using a different base image. Currently we use `tensorflow/tensorflow:custom-op-ubuntu16` and looks like `2.1.0-custom-op-ubuntu16` is recommended for TF >= 2.1. Not sure of the difference, do you happen to know @yongtang ?

**Comment by BryanCutler** [comment]
nvm, from what I can tell `tensorflow:custom-op-ubuntu16` targets the image for the latest version, 2.2 now.

**Comment by kvignesh1420** [comment]
@BryanCutler what's the version of TensorFlow inside the container? By default, `tensorflow-2.3.0rc2` is installed by the `./configure` step.

**Comment by BryanCutler** [comment]
TF isn't in the container. It's either downloaded by the config script, or you can install a version manually before running config

**Comment by kvignesh1420** [comment]
Yes, even after using the configure.sh script to install TensorFlow and then running the above command results in a failure. Any insights from the above-provided log file?

**Comment by BryanCutler** [comment]
The last error seems a bit odd, maybe environmental. Did you try clearing all cache and restarting the container?

**Comment by kvignesh1420** [comment]
@BryanCutler after I removed the cache and rebuilt the packages, I encountered this error:
```
Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/server/jvm.out')
```

but then figured out that by limiting the number of parallel jobs for the Bazel build (resource constraints) inside the container, the build was successful. Will raise a PR to document this and close the issue. Thanks.
