### ISSUE TITLE
[kafka-io] Possible support for online learning using kafka.

### ISSUE THREAD

**Issue by kvignesh1420** [tensorflow/io#1076]
While working on the Kafka tutorial, I observed an interesting event which might give us some direction towards support for online-learning of ml models.

**Background**

When streaming data from Kafka into the ML model using the `KafkaGroupIODataset` during the training phase, the first epoch is unsure of the number of batches it will be provided with.  Once the first epoch has finished, the dataset tries to fetch all the messages from the beginning again. This is not possible with the current implementation of `KafkaGroupIODataset` _(feature can be added based on config)_.  However, with the `stream_timeout` functionality of the dataset, we can have a single long-running loop with the model being trained on the data points which are streaming from the source.

**Scenario:**

Implement a micro-batch functionality wherein the result of iterating through the `KafkaGroupIODataset`  will be a `tf.data.Dataset`. A possible implementation with an additional arg `nested_ds=True` would be as follows:

```
group_io_ds = KafkaGroupIODataset(topics=['topic'], group_id='cg', nested_ds=True)

for micro_batch in group_io_ds:
  model.fit(micro_batch, epochs=10)
```

So when we pick up batches (`micro_batch`) from `KafkaGroupIODataset`, instead of returning them as individual records, we can return them as a `tf.data.Dataset` with `n` data points within them, which can be directly fed into `model.fit`.

Not sure about the feasibility, but would like to get feedback on the idea for possible implementation efforts. Thanks.

cc: @yongtang  @terrytangyuan  @BryanCutler

**Comment by yongtang** [comment]
@kvignesh1420 That is definitely an interesting case and I could see it might be very useful in many scenarios 👍 . The only thing that might be worth thinking could be the naming. Maybe we can change to a separate name instead of reusing the `KafkaGroupIODataset`? Having a different name could avoid confusion as the output of the dataset structures are quite different.

**Comment by kvignesh1420** [comment]
@yongtang , how about `KafkaOnlineIODataset` for the dataset name? Will look into the implementation aspect of this.

**Comment by yongtang** [comment]
@kvignesh1420 Maybe something like `KafkaBatchIODataset`, or similar?

Just wondering if `Online` is too generic and user may not connect?

**Comment by kvignesh1420** [comment]
@yongtang, the `KafkaBatchIODataset` class seems fine. We can expose the API with some docstrings to avoid confusion as to what the `Batch` indicates.

**Comment by yongtang** [comment]
@kvignesh1420 sounds good to me 👍
