### ISSUE TITLE
Potential multiple initialization calls due to out-of-range increment in `FFmpegInit`?

### ISSUE THREAD

**Issue by kyamagu** [tensorflow/io#1077]
It seems `FFmpegInit` uses unsigned count to check if it's initialized, but won't this reach out-of-range?

https://github.com/tensorflow/io/blob/520eaf91203cfee354943680a92ed5664042cd80/tensorflow_io/core/kernels/ffmpeg_kernels_deprecated.cc#L39

**Comment by yongtang** [comment]
@kyamagu Indeed this is problematic if the program is long running. Would you like to create a PR?

**Comment by kyamagu** [comment]
Alright, will prepare
