### ISSUE TITLE
Discussion: Official docker image for tensorflow-io

### ISSUE THREAD

**Issue by kvignesh1420** [tensorflow/io#1087]
As new features are being added to the library, it would be great if we can have an official Docker image for ease of use and integration.  There was a discussion going on in https://github.com/tensorflow/io/issues/414 for integration with tf-serving, but kind of went stale.

We already have our development image but that is not an efficient one. I think it will be a good work item for the upcoming releases. Please let me know your opinions.

cc: @yongtang @terrytangyuan @BryanCutler @vlasenkoalexey

**Comment by yongtang** [comment]
@kvignesh1420 That would be great! Some thing to consider, that tensorflow-io only depends on tensorflow and there is no other dependencies. We could just build a `minimal` image with tensorflow+tensorflow-io only with some lightweight base image.

Another thing to consider is to automatically push build to dockerhub (could be combined with GitHub Actions I guess).

**Comment by kvignesh1420** [comment]
@yongtang, can we reach out to the tf folks to create a repository named `tensorflow/io` in docker hub? We can tag our images as follows:

- tensorflow/io:latest
- tensorflow/io:latest-devel

GPU supported images can be added later on.

**Comment by yongtang** [comment]
Thanks @kvignesh1420. Also cc @seanpmorgan and @WindQAQ in case tensorflow-addons also want to publish docker images to tensorflow repo on GitHub.

**Comment by seanpmorgan** [comment]
Please let us know how this goes. We decided to just create our own namespace since it seemed like less bureaucracy but would be happy to align:
https://hub.docker.com/repository/docker/tfaddons/dev_container

**Comment by kvignesh1420** [comment]
@seanpmorgan, few question regarding the hub:

1. Who maintains this docker repository in the hub?
2. Do you plan to switch to the main TensorFlow repo in the hub?
3. What is the process that you are following to push the images?

**Comment by kvignesh1420** [comment]
Thanks for the info @seanpmorgan. 

@yongtang what do you think about this?

**Comment by yongtang** [comment]
@kvignesh1420 I think in the short term, we can start with a docker account (such as `tfio`) and build our containers with an automatic pipeline in GitHub Actions. Once the container stabilizes we can work with tensorflow team to see if the containers could be moved under tensorflow account gradually.

**Comment by kvignesh1420** [comment]
@yongtang sounds good. If you can please create an account and store the creds as Github secrets, I can work on the actions and see how it turns out.

**Comment by yongtang** [comment]
`tfio` username seems to have been taken in dockerhub. Trying to come up with a name that can fit.

**Comment by yongtang** [comment]
Created a `tfiocontainer` account instead.

**Comment by kvignesh1420** [comment]
@yongtang how about `tensorflowio` ?

**Comment by yongtang** [comment]
`tensorflowio` is also occupied unfortunately.

**Comment by yongtang** [comment]
I manually created a docker container https://hub.docker.com/repository/docker/tfiocontainer/tfio, using the https://github.com/tensorflow/io/blob/master/tools/docker/cpu.Dockerfile

We can gradually move to an automated pipeline. And we can change the name or repo if we find a good fit.

**Comment by kvignesh1420** [comment]
@yongtang, that's great. Last but not the least, can we give one last try to `tfsigio`, if you feel it is better? If not we can proceed with the current account. 👍

**Comment by yongtang** [comment]
@kvignesh1420 `tfsigio` works:
https://hub.docker.com/r/tfsigio/tfio/tags

**Comment by kvignesh1420** [comment]
@seanpmorgan thanks for the help. We were able to push the images using Github actions. 
https://hub.docker.com/r/tfsigio/tfio/tags

cc: @yongtang @terrytangyuan @BryanCutler @vlasenkoalexey
