### ISSUE TITLE
Add support for elasticsearch

### ISSUE THREAD

**Issue by kvignesh1420** [tensorflow/io#1093]
Since many organizations use the ELK stack for data analysis, I think it would be beneficial for many users if they can connect to ElasticSearch and train their ML models.

cc: @yongtang @terrytangyuan @BryanCutler @vlasenkoalexey

**Comment by yongtang** [comment]
@kvignesh1420 This will be a great addition!. ELK stack is used widely in data analysis. Combining it with tfio => tf.data => tf.keras will really helps pushing the usage of ML to wider audiences.

**Comment by kvignesh1420** [comment]
Will explore the integration.

**Comment by kvignesh1420** [comment]
@yongtang  Since the connection with Elasticsearch is HTTP based, which approach would be the fastest based on previous client implementations? For example, the Prometheus kernel uses the external `prometheus/client_golang` package for connecting to the server. Do we want to follow the same style and use the [go-elasticsearch](https://github.com/elastic/go-elasticsearch) third_party package by elastic ? or do we write the connectors from scratch using libcurl (using TensorFlow wrapper `HttpRequest`)?

**Comment by yongtang** [comment]
@kvignesh1420 We can start with anyone and incrementally improve later.

In prometheus, the reason to choose golang was that, prometheus by itself is a golang implementation, and golang has the first class citizen support. There is also no official C or C++ client support.

However, during the implementation we noticed that, golang does not play really well with C/C++ when embedding into one shared object. See #492 for more details. This is quite different from Swift embedding in C++ where we don't see similar issues. I have been considering to drop golang and in favor of C/C++ client for prometheus for sometime, haven't made this happen yet.

For that reason, I think a C++/C client for elasticsearch, or using libcurl directly (through HttpRequest) might make sense. I noticed that elasticsearch also has no official C++/C client. We might just pick up a C++/C client that is maintained better?

Note Rust could also be an option as there is an official rust client for elasticsearch. However, integrate Rust with Bazel could be really painful. (Last time I tried to get rust working for AVIF code in our repo, haven't had success yet). Rust also might be exposed to the risk of its own future, given the recent situation in Mozilla. For that reason we might want to defer rust related integration.

So overall I think a quality (even if not official) C++/C client would make sense for now. libcurl could be considered if the C++/C client does not meet our expectations.

Let me know if you run into any problems or have any issues, especially with Bazel 😃 .

**Comment by kvignesh1420** [comment]
@yongtang this is the C++ client which was mentioned in the elasticsearch-community contributed clients section. (https://github.com/seznam/elasticlient). However, I don't think this is very actively maintained and we might run into dependency issues in the future (not sure though). For now, I will start with our own libcurl implementation and see how things turn out.

**Comment by kvignesh1420** [comment]
The experimental API's and the colab tutorial have been added. Enhancements/Bug-fixes will be taken up as separate issues.
