### ISSUE TITLE
Missing .bazelversion file

### ISSUE THREAD

**Issue by mkuchnik** [tensorflow/io#1104]
The build system for tensorflow/io uses Bazel. Bazel can be installed (and if often [recommended](https://www.tensorflow.org/install/source#install_bazel) to be installed) using [Bazelisk](https://github.com/bazelbuild/bazelisk). Bazelisk looks for a .bazelversion file (e.g., see [Tensorflow's](https://github.com/tensorflow/tensorflow/commit/d2b02580e6f68d2360bd6ad6eda805aa1d4e9871#diff-6c232aa20b0cc9065978a6352081dfc9)). It seems tensorflow/io is missing a .bazelversion file, which means users of Bazelisk may get some random upstream version (e.g., v3.5 in my case), which may cause build reproducibility issues.

**Comment by yongtang** [comment]
@mkuchnik Thanks for opening the issue and create the PR! The PR #1105 has been merged 👍 🎉
