### ISSUE TITLE
NotFoundError: Op type not registered 'IO>DecodeDICOMImage' in binary running on n-18b2717f-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. [Op:ParallelMapDataset]

### ISSUE THREAD

**Issue by ZyingHang** [tensorflow/io#1106]
System information

Have I written custom : yes
OS Platform : 'Linux-4.19.112+-x86_64-with-debian-buster-sid'
TensorFlow version : 2.2.0
Python version: 3.7.6
Tensorflow_io version: 0.14.0

from kaggle_datasets import KaggleDatasets
import tensorflow as tf
import tensorflow_io as tfio
import pandas as pd
import os
from sklearn.model_selection import KFold

tpu = tf.distribute.cluster_resolver.TPUClusterResolver()
tf.config.experimental_connect_to_cluster(tpu)
tf.tpu.experimental.initialize_tpu_system(tpu)
strategy = tf.distribute.experimental.TPUStrategy(tpu)
AUTO     = tf.data.experimental.AUTOTUNE
BATCH_SIZE = 32 * strategy.num_replicas_in_sync

GCS_DS_PATH = KaggleDatasets().get_gcs_path('competetion_name')
def preprocessing():
    ......
    filepath = os.path.join(GCS_DS_PATH, patient_ids[i], dcmnames[i][j])
    ......
   df = pd.DataFrame(data = dataset, columns = ['Patient_Week', 'filepath', 'Weeks', 'FVC'])
   return df 

def read_labeled(example):
    image_bytes = tf.io.read_file(example['filepath'])
    image_gray = tfio.image.decode_dicom_image(image_bytes, scale='auto', on_error='lossy', dtype=tf.uint8)
    image_gray = tf.image.resize(image_gray, [IMG_SIZE, IMG_SIZE])
    return tf.squeeze(image_gray, axis = 0), example['Weeks'], tf.cast(example['FVC'], tf.float32)

def prepare_image(img, data, augment=True):
    img = tf.cast(img, tf.float32) / 255.0
    if augment:
        img = transform(img,DIM=IMG_SIZE)
        img = tf.image.random_flip_left_right(img)
    data = tf.cast(data, tf.float32)
    return {'inp1': img, 'inp2':data} 

def get_dataset(meta, labeled = True, return_patient_week = True, 
                shuffle = False, repeat = False, augment = False):
    ds = tf.data.Dataset.from_tensor_slices(meta)        
    ds = ds.cache()    
    if repeat:
        ds = ds.repeat()    
    if shuffle:
        ds = ds.shuffle(1024*8)
        opt = tf.data.Options()
        opt.experimental_deterministic = False
        ds = ds.with_options(opt)        
    if labeled:
        ds = ds.map(read_labeled, num_parallel_calls = AUTO)
    else:
        ds = ds.map(lambda example: read_unlabeled(example, return_patient_week), num_parallel_calls = AUTO)
    ds = ds.map(lambda img, data, patweek_or_label: (prepare_image(img, data, augment=augment), patweek_or_label),
num_parallel_calls=AUTO)
    ds = ds.batch(BATCH_SIZE)
    ds = ds.prefetch(AUTO)    
    return ds

......
skf = KFold(n_splits = FOLDS, shuffle = True, random_state = SEED)
df_train = preprocessing()
df_train = {'Patient_Week': df['Patient_Week'], 'filepath': df['filepath'], 'Weeks': df['Weeks'], 'FVC': df['FVC']}
for fold, (idxT, idxV) in enumerate(skf.split(df_train)):
    train = df_train.iloc[idxT]
    train_dict = {'Patient_Week': train['Patient_Week'], 'filepath': train['filepath'], 'Weeks': train['Weeks'], 'FVC': train['FVC']}
    ......
    print('Training...')
    history = model.fit(
        get_dataset(train_dict, augment=True, shuffle=True, repeat=True), 
        epochs=EPOCHS, callbacks = [sv,get_lr_callback()],   #lr_scheduler
        steps_per_epoch=len(train)/BATCH_SIZE,
        validation_data=get_dataset(valid_dict,augment=False,shuffle=False,repeat=False), 
        verbose=VERBOSE
    )
......

NotFoundError                             Traceback (most recent call last)
<ipython-input-11-49e0fb4405b9> in <module>
     31     print('Training...')
     32     history = model.fit(
---> 33         get_dataset(train_dict, augment=True, shuffle=True, repeat=True),
     34         epochs=EPOCHS, callbacks = [sv,get_lr_callback()],   #lr_scheduler
     35         steps_per_epoch=len(train)/BATCH_SIZE,

<ipython-input-8-fe90b729c1d1> in get_dataset(meta, labeled, return_patient_week, shuffle, repeat, augment)
     21      else:
     22             ds = ds.map(lambda example: read_unlabeled(example, return_patient_week), num_parallel_calls = AUTO)
---> 23     ds = ds.map(lambda img, data, patweek_or_label: (prepare_image(img, data, augment=augment), patweek_or_label), num_parallel_calls=AUTO)
     24      ds = ds.batch(BATCH_SIZE)
     25      ds = ds.prefetch(AUTO)

/opt/conda/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py in map(self, map_func, num_parallel_calls, deterministic)
   1626           num_parallel_calls,
   1627           deterministic,
-> 1628           preserve_cardinality=True)
   1629 
   1630   def flat_map(self, map_func):

/opt/conda/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py in __init__(self, input_dataset, map_func, num_parallel_calls, deterministic, use_inter_op_parallelism, preserve_cardinality, use_legacy_function)
   4048           use_inter_op_parallelism=self._use_inter_op_parallelism,
   4049           preserve_cardinality=self._preserve_cardinality,
-> 4050           **self._flat_structure)
   4051     super(ParallelMapDataset, self).__init__(input_dataset, variant_tensor)
   4052 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py in parallel_map_dataset(input_dataset, other_arguments, num_parallel_calls, f, output_types, output_shapes, use_inter_op_parallelism, sloppy, preserve_cardinality, name)
   4690         pass  # Add nodes to the TensorFlow graph.
   4691     except _core._NotOkStatusException as e:
-> 4692       _ops.raise_from_not_ok_status(e, name)
   4693   # Add nodes to the TensorFlow graph.
   4694   if not isinstance(output_types, (list, tuple)):

/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6651   message = e.message + (" name: " + name if name is not None else "")
   6652   # pylint: disable=protected-access
-> 6653   six.raise_from(core._status_to_exception(e.code, message), None)
   6654   # pylint: enable=protected-access
   6655 

/opt/conda/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

NotFoundError: Op type not registered 'IO>DecodeDICOMImage' in binary running on n-6a93be02-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. [Op:ParallelMapDataset]

I got the problem above at Kaggle. Do you have any ideas? I guess something between `tfio.image.decode_dicom_image` and  `tf.data.Dataset` is wrong, but I don't know how to do.

**Comment by yongtang** [comment]
@ZyingHang can you provide your OS version (e.g., Ubuntu 18.04, etc) and python version (and the python env such as system default, or conda)?

**Comment by ZyingHang** [comment]
OS Platform : 'Linux-4.19.112+-x86_64-with-debian-buster-sid'
TensorFlow version : 2.2.0
Python version: 3.7.6
Tensorflow_io version: 0.14.0
with GCS+TPU at kaggle
Thank you.

**Comment by yongtang** [comment]
@ZyingHang I am able to run with tensorflow-io 0.15.0 + tensorflow 2.3.0 on Kaggle (gcr.io/kaggle-images/python), after installing tensorflow-io from:
```

$ docker run -i -t --rm -v $PWD:/v -w /v gcr.io/kaggle-images/python bash

### enter into docker shell

$ python3 -m pip install tensorflow-io

...
```

Can you give it a try? Or if you are installing tensorflow-io from other methods than pip, can you specify in details?

**Comment by ZyingHang** [comment]
1. Well, I got an error as follows with `python3 -m pip install tensorflow-io` :
```
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-3-df8484dc15ea> in <module>
     13             tf.config.experimental_connect_to_cluster(tpu)
---> 14             tf.tpu.experimental.initialize_tpu_system(tpu)
     15             strategy = tf.distribute.experimental.TPUStrategy(tpu)

/opt/conda/lib/python3.7/site-packages/tensorflow/python/tpu/tpu_strategy_util.py in initialize_tpu_system(cluster_resolver)
    110 
--> 111     serialized_topology = output.numpy()
    112 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py in numpy(self)
   1062     # TODO(slebedev): Consider avoiding a copy for non-CPU or remote tensors.
-> 1063     maybe_arr = self._numpy()  # pylint: disable=protected-access
   1064     return maybe_arr.copy() if isinstance(maybe_arr, np.ndarray) else maybe_arr

/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py in _numpy(self)
   1030     except core._NotOkStatusException as e:  # pylint: disable=protected-access
-> 1031       six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access
   1032 

/opt/conda/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: NodeDef expected inputs 'string' do not match 0 inputs specified; Op<name=_Send; signature=tensor:T -> ; attr=T:type; attr=tensor_name:string; attr=send_device:string; attr=send_device_incarnation:int; attr=recv_device:string; attr=client_terminated:bool,default=false; is_stateful=true>; NodeDef: {{node _Send}}

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-3-df8484dc15ea> in <module>
     15             strategy = tf.distribute.experimental.TPUStrategy(tpu)
     16             print("TPU initialized")
---> 17         except _:
     18             print("failed to initialize TPU")
     19     else:

TypeError: catching classes that do not inherit from BaseException is not allowed
```
It occurred a TPU setting error. Is there something I ignore?
2. I installed tfio with `!pip install tensorflow-io==0.14.0`

**Comment by yongtang** [comment]
@ZyingHang It may not be of difference, though have you give tensorflow 2.3.0+tensorflow-io 0.15.0 a try?

**Comment by ZyingHang** [comment]
Yeah, I have tried tensorflow 2.3.0+tensorflow-io 0.15.0, which is OK without TPU(both GPU and CPU is ok), but because there is a mismatch between tf2.3.0 and tpu (I guess), it results to tpu config error above, so I can't get it done with tf2.3.0+tfio0.15.0+tpu.

**Comment by vlasenkoalexey** [comment]
TF.IO is not yet supported on TPUs, see #716 
Hope it is going to be addressed soon

**Comment by ZyingHang** [comment]
OK, I know, thank you, and wait for update.
