### ISSUE TITLE
[Question] How to stream data from cache of parquet files?

### ISSUE THREAD

**Issue by chaaland** [tensorflow/io#1121]
Hi, I have a cache of parquet files on a network drive that I would like to stream using `IODataset` since the total size of all the files is too large to fit into memory. How can I efficiently load my dataset into a tensorflow dataset?

Note: I've asked a similar question [here](https://github.com/tensorflow/io/issues/927) which has some examples of things I've attempted that did not work

**Comment by marcromeyn** [comment]
I am facing this issue as well. Is there a way to fix this?

**Comment by kvignesh1420** [comment]
@chaaland @marcromeyn here is a small working reference as per the example defined in https://github.com/tensorflow/io/issues/927:

```python
import numpy as np
import tensorflow as tf
import pandas as pd
import tensorflow_io as tfio

df = pd.DataFrame({"pred_0": 0.1*np.arange(100), "pred_1": -0.1*np.arange(100)})
df.to_parquet("df_x.parquet")
df.to_parquet("df_y.parquet")
columns = {"pred_0": tf.TensorSpec(tf.TensorShape([]), tf.double), "pred_1": tf.TensorSpec(tf.TensorShape([]), tf.double)}

def map_fn(file_location):
  return tfio.IODataset.from_parquet(file_location, columns=columns)

ds = tf.data.Dataset.list_files("*.parquet").map(map_fn)

for d in ds: # loop over the files
    for item in d: # loop over items
        print(item)
```

the key point to note is that we have to provide the `TypeSpec`s of the columns to the dataset during initialization.

**Comment by chaaland** [comment]
Thanks for the example. For clarity, there is no way to work with multiple parquet files in a single dataset? Ideally I'd like to just pass a list of parquet files and be able to call things like `.batch(10)` on that dataset and have the dataset figure out whether it needs to load part of the next file to make the batch.

**Comment by kvignesh1420** [comment]
@chaaland to achieve that you can do the following:

Assuming you have a list of parquet files

```python

def make_common_ds(files):
    common_ds = tfio.IODataset.from_parquet(files[0], columns=columns)
    for file_name in files[1:]:
        ds = tfio.IODataset.from_parquet(file_name, columns=columns)
        common_ds = common_ds.concatenate(ds)
    return common_ds

files = ['file1.parquet', 'file_2.parquet']
ds = make_common_ds(files)
ds = ds.batch(10)
for batch_item in ds:
  print(batch_item)

```

**Comment by kvignesh1420** [comment]
@chaaland can this issue be closed?

**Comment by chaaland** [comment]
Sure I will can close this issue

**Comment by lrothack** [comment]
In order to directly iterate over the samples from multiple parquet files in a single dataset, you can replace `map` with `interleave` in @kvignesh1420 's original answer.

**Comment by abedshantti** [comment]
@kvignesh1420 do the files need to be stored in my local machine, or can I use files in AWS S3?

I have tried replacing `files = ['file1.parquet', 'file_2.parquet']` with `files = [s3bucket + "/path/file_{}.parquet".format(i) for i in range(5)]`, but the file reading never actually finish.

**Comment by abedshantti** [comment]
> @kvignesh1420 do the files need to be stored in my local machine, or can I use files in AWS S3?
> 
> I have tried replacing `files = ['file1.parquet', 'file_2.parquet']` with `files = [s3bucket + "/path/file_{}.parquet".format(i) for i in range(5)]`, but the file reading never actually finishes.

I managed to resolve this by using `tf..data.Dataset.from_tensor_slices` instead of `tf.data.Dataset.list_files`
```
files = [ s3bucket + "/path/file_{}.parquet".format(i) for i in range(5) ]
ds = tf.data.Dataset.from_tensor_slices(files).map(map_fn)
``` 
It is also stated on the Tensorflow's API that `from_tensor_slices` is preferred to `list_files` for reading remotely stored data: https://www.tensorflow.org/api_docs/python/tf/data/Dataset#list_files

**Comment by kvignesh1420** [comment]
thanks for the update @abedshantti

**Comment by abedshantti** [comment]
@kvignesh1420  no problem. I am relatively new to `tf.datasets` and I have one more question regarding the labels for the files. In my case, each file is a time-series and I want the tensorflow dataset to embed the classification labels in order to train the model. This is how I am defining my function:

```
train_size = 640
batch_size = 32

def train_map_fn(file_location, labels):
    inner_ds = tfio.IODataset.from_parquet(file_location, columns=col_dict)
    inner_ds = inner_ds.shuffle(buffer_size=train_size)
    inner_ds = inner_ds.batch(batch_size)
    inner_ds = inner_ds.prefetch(batch_size)
    return inner_ds, labels

train_files = [ s3bucket + "/path/file_{}.parquet".format(i) for i in range(train_size) ]
train_labels = np.array([0, 1, 0, 0, ... , 1])
train_ds = tf.data.Dataset.from_tensor_slices((train_files, train_labels)).map(train_map_fn)
```

Is the correct way to generate a dataset that includes both the data and labels, which I can use for training? My only concern is that I am not sure if the labels are shuffled alongside the labels.

**Comment by kvignesh1420** [comment]
@abedshantti in the above snippet, `labels` are not shuffled. Only the `inner_ds` dataset is shuffled. 
To shuffle both labels and data, you can try:
```python
train_ds = tf.data.Dataset.from_tensor_slices((train_files, train_labels))
train_ds = train_ds.shuffle(buffer_size=buffer_size)
train_ds = train_ds.map(train_map_fn)
```

**Comment by abedshantti** [comment]
@kvignesh1420 I am trying to shuffle the order of the files in the batches, so that I don't end up with exactly the same training time-series files in every batch. So instead of batch 1 being files 1, 2, ... , 32 during every epoch, I would prefer to the order of the files to be shuffled when training, but not the contents of the files (which are preprocess time-series data).

**Comment by sayakpaul** [comment]
@lrothack 

> In order to directly iterate over the samples from multiple parquet files in a single dataset, you can replace map with interleave in @kvignesh1420 's original answer.

Could you provide an example?

**Comment by chaaland** [comment]
@sayakpaul 

You'd do something like below
```python
import pandas as pd
import numpy as np
import tensorflow as tf
import tensorflow_io as tfio

x1 = np.arange(10).reshape(5, 2)
x2 = np.arange(10, 16).reshape(3, 2)

df1 = pd.DataFrame(x1, columns=["pred_1", "pred_2"])
df2 = pd.DataFrame(x2, columns=["pred_1", "pred_2"])

df1.to_parquet("foo.parquet")
df2.to_parquet("bar.parquet")

columns = {
    "pred_1": tf.TensorSpec(tf.TensorShape((None, 2)), tf.int64), 
    "pred_2": tf.TensorSpec(tf.TensorShape((None, 2)), tf.int64),
}

ds = tf.data.Dataset.list_files("*.parquet")
ds = ds.interleave(lambda f: tfio.IODataset.from_parquet(f, columns=columns), cycle_length=2, block_length=2)

for elem in ds:
    print(elem) # each one of these is an OrderedDict

```

**Comment by nkvuradi** [comment]
@chaaland When I run the exact code as provided by you - I see below error - _InvalidArgumentError: Incompatible shapes at component 0: expected [?,2] but got []. [Op:IteratorGetNext]_
Seems like some issue with from_paquet method, any idea on this error?

**Comment by chaaland** [comment]
Maybe you don't have pyarrow installed so the parquet files aren't being written? Here are the libraries I have in environment for which this code definitely works

```
tensorflow==2.7.0
tensorflow-io==0.23.1
pandas==1.5.2
pyarrow==9.0.0
```

**Comment by nkvuradi** [comment]
I've parquet files written well, no issues there. I was facing issue with tf 2.7.1, reinstalling 2.7.0 worked. Thanks!

**Comment by nkvuradi** [comment]
@chaaland I am struggling a little with an issue here. Any help on this is highly appreciated. 
After I get ordered dict of colmns from the above parquet read, I need to perform json.loads operation as the values I have is in the byte array format(actually list of floats), thats how parquet stores list of floats. 

Below is the code with the type of data input I have got. 

`df1 = pd.DataFrame({'col1':['[1.2, 2.3, 4.5]', '[1.0, 2.2, 4.3]'], 'col2':['[1.2, 0.3, 0.9]', '[1.1, 9.2, 5.3]']})
df2 = pd.DataFrame({'col1':['[1.1, 2.1, 4.1]', '[1.09 2.29, 4.39]'], 'col2':['[12.2, 20.3, 20.96]', '[12.1, 19.2, 15.3]']})

df1.to_parquet("foo.parquet")
df2.to_parquet("bar.parquet")

columns = {
    "col1": tf.TensorSpec(tf.TensorShape([]), tf.string), 
    "col2": tf.TensorSpec(tf.TensorShape([]), tf.string),
}

ds = tf.data.Dataset.list_files("*.parquet")
ds = ds.interleave(lambda f: tfio.IODataset.from_parquet(f, columns=columns), cycle_length=2, block_length=2) # returns an ordered dict

def decode_json(ip):
    return tf.py_function(json.loads, [ip], Tout=[tf.float32])

def decode(ip):
    out1 = ip["col1"].map(decode_json)
    out2 = ip["col2"].map(decode_json)
    return out1, out2

ds = ds.map(decode)

for elem in ds:
    print(elem)`

This gives error "AttributeError: 'Tensor' object has no attribute 'map'"

**Comment by chaaland** [comment]
Yes, if you put a print statement in your decode function you'll see that `ip["col1"]` is a Tensor and not a Dataset (which is the class that has the `map` attribute). I never did manage to completely grok tf Datasets and ended up moving to torch awhile ago as it was much simpler for this sort of thing.

Anyway, the only way I can think to do what you want above is the code below

```python
import codecs
import json

import pandas as pd
import tensorflow as tf
import tensorflow_io as tfio

df1 = pd.DataFrame({"col1": ["[1.2, 2.3, 4.5]", "[1.0, 2.2, 4.3]"], "col2": ["[1.2, 0.3, 0.9]", "[1.1, 9.2, 5.3]"]})
df2 = pd.DataFrame(
    {"col1": ["[1.1, 2.1, 4.1]", "[1.09, 2.29, 4.39]"], "col2": ["[12.2, 20.3, 20.96]", "[12.1, 19.2, 15.3]"]}
)

df1.to_parquet("foo.parquet")
df2.to_parquet("bar.parquet")

columns = {
    "col1": tf.TensorSpec(tf.TensorShape([]), tf.string),
    "col2": tf.TensorSpec(tf.TensorShape([]), tf.string),
}


def data_gen():
    ds = tf.data.Dataset.list_files("*.parquet")
    ds = ds.interleave(lambda f: tfio.IODataset.from_parquet(f, columns=columns), cycle_length=2, block_length=2)

    for elem in ds:
        col1 = json.loads(codecs.decode(elem["col1"].numpy()))
        col2 = json.loads(codecs.decode(elem["col2"].numpy()))

        yield col1, col2


ds = tf.data.Dataset.from_generator(
    data_gen,
    output_signature=(tf.TensorSpec(shape=(3,), dtype=tf.float32), tf.TensorSpec(shape=(3,), dtype=tf.float32)),
)
for elem in ds:
    print(elem)
```

Having to use `from_generator` is pretty much always a bad sign in my experience. Also, I'd really try to avoid having arrays as values in your schema if it can be helped.

**Comment by nkvuradi** [comment]
First of all, appreciate taking out sometime. Only thing I'm concerned about the above approach is that we might loose the capability of parallel processing.

**Comment by chaaland** [comment]
Yes, your concerns are valid. This is what I referencing when I said `from_generator` is a bad sign. I'm not sure how else to do it. If you have the ability to move to torch, I would. Otherwise, would think about whether you can make a simpler schema
