### ISSUE TITLE
Wrong import for tensorflow_io in the official website.

### ISSUE THREAD

**Issue by kvignesh1420** [tensorflow/io#1141]
I recently observed that the example showcased on the [official website](https://www.tensorflow.org/io) has a wrong import for `tensorflow_io`.

![image](https://user-images.githubusercontent.com/25393945/94857744-9d204f80-044f-11eb-8322-5344bc754bae.png)

I searched for the content in our repo and in `tensorflow/docs` repo, but to no avail. Any idea how this can be fixed?

cc: @MarkDaoust @terrytangyuan @yongtang

**Comment by MarkDaoust** [comment]
I'm sending a fix.

**Comment by kvignesh1420** [comment]
Thanks !

**Comment by kvignesh1420** [comment]
The import has been fixed. Thanks @MarkDaoust .
