### ISSUE TITLE
Loading boolean data from hdf5

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/io#1144]
Hi I have the following error when loading HDF5 boolean data with the latest versions: 

```
InvalidArgumentError: unsupported data class for /my_bool_data: 8 [Op:IO>HDF5ReadableInfo]
```

Here is a [link](https://colab.research.google.com/drive/11sUZgDcfQLRgG7PeE2PXBJIShR_1i6qH?usp=sharing) to a google colab.

**Comment by yongtang** [comment]
Added PR #1145 for the fix.
