### ISSUE TITLE
KafkaDataset doesn't consume from latest with config_topic=['auto.offset.reset=latest']

### ISSUE THREAD

**Issue by tungnat97** [tensorflow/io#1146]
I don't know if it was a bug or not. My KafkaDataset code:
`test_ds = kafka_io.KafkaDataset('network', 'some-ip-address:9092', group='test', 
                                config_topic=["auto.offset.reset=latest"])`

**Comment by kvignesh1420** [comment]
`KafkaDataset` is more useful when you want to consume messages from particular partitions and have a limit on how many are consumed. For streaming with timeouts, you can use `streaming.KafkaGroupIODataset` and `streaming.KafkaBatchIODataset`

I see that you raised a diff issue here which uses them:
https://github.com/tensorflow/io/issues/1148

**Comment by tungnat97** [comment]
Thank you for the recommendation. I set `"auto.offset.reset=latest"` in `streaming.KafkaGroupIODataset` but its offset doesn't change to latest.

**Comment by kvignesh1420** [comment]
Please check the comment in https://github.com/tensorflow/io/issues/1148. The feature is available in nightly release as of now.
