### ISSUE TITLE
tfio.experimental.audio.freq_mask fails with tf.data.Dataset.map

### ISSUE THREAD

**Issue by BryanWBear** [tensorflow/io#1158]
To reproduce: 

Instantiate `dataset`, a Dataset of 2d `float-32` tensors.
Running `dataset.map(lambda x: tfio.experimental.audio.freq_mask(x, param=10))`

yields the following error:
```
/usr/local/lib/python3.6/dist-packages/tensorflow_io/core/python/experimental/audio_ops.py:286 freq_mask  *
        return tf.where(condition, 0, input)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py:201 wrapper  **
        return target(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py:4461 where_v2
        return gen_math_ops.select_v2(condition=condition, t=x, e=y, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_math_ops.py:8875 select_v2
        "SelectV2", condition=condition, t=t, e=e, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:506 _apply_op_helper
        inferred_from[input_arg.type_attr]))

    TypeError: Input 'e' of 'SelectV2' Op has type float32 that does not match type int32 of argument 't'.
```

**Fix**: Change `return tf.where(condition, 0, input)` to `return tf.where(condition, 0.0, input)` (line 286 in `io/tensorflow_io/core/python/experimental/audio_ops.py`)

**Comment by yongtang** [comment]
@BryanWBear Created a PR to carry your patch. Thanks for reporting this!

**Comment by BryanWBear** [comment]
Thank you yongtang! The same error is present in `tfio.experimental.audio.time_mask`, which is right below `freq_mask`.

**Comment by yongtang** [comment]
@BryanWBear The PR #1170 has been merged so I will close this PR. Thanks a lot for your contribution!
