### ISSUE TITLE
Issues with building IODataset from truly hierarchical hdf5 

### ISSUE THREAD

**Issue by Antymon** [tensorflow/io#1161]
Hi, I have hdf5 files with datasets (features) nested under groups (samples) in the following way: `/sample_id/feature_column_id`. Is it possible to make a dataset of this with `IODataset.from_hdf5`? I have been trying in eager mode but failed. Keep getting `tensorflow.python.framework.errors_impl.InvalidArgumentError: unsupported data class for /eps0_t0/label_done: 8 [Op:IO>HDF5ReadableInfo]`
by simply calling `features = tfio.IODataset.from_hdf5(path,"/")`

Dependencies:
tensorflow-io Version: 0.15.0
tensorflow Version: 2.3.0

Also, whatever knowledge I get out of this question might be also worth putting as docs as I haven't found anything on how to use this part of API.

**Comment by kvignesh1420** [comment]
@Antymon I think you have to give the path to each feature column (based on the current implementation of the `IODataset`).

For example:

```python
for s_id in sample_ids:
  for c_id in feature_column_ids:
    feature_ds = tfio.IODataset.from_hdf5(path,"/{}/{}".format(s_id, c_id))
```

You can then zip multiple of these `feature_ds` datasets into a single dataset for a `sample_id`.

**Comment by Antymon** [comment]
Thanks, so I would use an `IODataset` object for something that is merely a feature of an example. I do wonder what would be performance implications, coz this feels like an approach that is going around the original intent of how hdf5 should be structured Perhaps my problem is the file itself as it is not really meant to be hierarchical?

**Comment by kvignesh1420** [comment]
@Antymon maybe you can represent your dataset in another format? Check the PR https://github.com/tensorflow/io/pull/1163 for a discussion on this.

**Comment by Antymon** [comment]
Interesting. How about if I stored each feature for all samples in a single group? Wouldn't that convention make my h5 columnar? Then I would have as many datasets as features and perhaps could zip those together. Does that sound like an improvement over my current structure?

**Comment by kvignesh1420** [comment]
@Antymon can this issue be closed?

**Comment by Antymon** [comment]
Well, it can, of course. As a user, I would wish for some instructions on h5 to appear in the docs, but I leave it to your judgment. I am speculating that one could mimic TFRecord in serializing all tensors to strings and dump everything as one string matrix under a single h5 dataset, but I haven't benchmarked either this or what was originally suggested. As for my problem, I will simply go for now with TFRecord.

**Comment by kvignesh1420** [comment]
@Antymon we will try to put down some documentation around this. Also, it would be great if you can contribute the benchmarking with TFRecord and h5 datasets. It would be helpful to others as well. Thanks.
