### ISSUE TITLE
Error in decode_tiff and IOtensor.from_tiff  

### ISSUE THREAD

**Issue by usryokousha** [tensorflow/io#1205]
When decoding a tiff file using the Tensorflow IO API I am getting an error in the libtiff code.  This issue was already addressed on StackOverflow [See link](https://stackoverflow.com/questions/64424426/load-tiff-images-in-tensorflow-using-tensorflow-ios-decode-tiff) but hasn't appeared here.  

The failed line of code is the following:
Assertion failed: sizeof(tmsize_t)==sizeof(void*), file external/libtiff/libtiff/tif_open.c, line 99

**Comment by yongtang** [comment]
@usryokousha Can you list the details of the OS and python version? If it is on Windows then the issue may have been solved in  #1171

**Comment by usryokousha** [comment]
Sorry, for the delayed response.  I am also on a system running Windows 10! You are right that it was addressed in #1171!  Thank you for the help!
