### ISSUE TITLE
TPU Support? `IODataset.from_hdf5`

### ISSUE THREAD

**Issue by JulesGM** [tensorflow/io#1217]
Hello, 
when trying to use `IODataset.from_hdf5` with `tf.distribute.TPUStrategy` and `tf.distribute.Strategy.experimental_distribute_dataset`, I get `tensorflow.python.framework.errors_impl.NotFoundError: 'IO>HDF5ReadableInfo' is neither a type of a primitive operation nor a name of a function registered in binary running on n-0b70162a-w-0. Make sure the operation or function is registered in the binary running in this process.` which I assume means the TPUs can't use them. Is there a way to use this on TPUs with TPUStrategy that I don't know about? thanks.

**Comment by vlasenkoalexey** [comment]
In order to support different data sources provided by tensorflow-io, it has to be installed on TPU VM. See 
https://github.com/tensorflow/io/issues/716#issuecomment-988362978 for details.
