### ISSUE TITLE
decode_vorbis causing RAM leak

### ISSUE THREAD

**Issue by marno1d** [tensorflow/io#1245]
I'm seeing an issue where using tfio.audio.decode_vorbis is causing a RAM memory leak. If I call decode_vorbis in a loop the RAM increases. However, when I call decode_wav in a loop the RAM stays constant. 

TF Version: 2.4
TF IO Version 0.17.0
OS: Ubuntu 18.04

I created a colab notebook that reproduces this issue: https://colab.research.google.com/drive/1W0ubBFr2lEEHeqAYDguXgAyFZgjuZOvl?usp=sharing

There was a similar issue where decode video was causing a memory leak #680. Perhaps a similar problem is happening here.

**Comment by kvignesh1420** [comment]
@marno1d PR: https://github.com/tensorflow/io/pull/1249 has been opened to address this issue.

**Comment by marno1d** [comment]
@kvignesh1420 Great, thanks for getting to this so quickly. I really appreciate the whole tfio.audio library.

**Comment by kvignesh1420** [comment]
@marno1d I didn't observe any obvious mem leaks while trying the `decode_vorbis` functionality on my mac. However, I have addresses the file cleanup in the PR. Folks might be on vacation so it might take some time to get this reviewed.

**Comment by marno1d** [comment]
@kvignesh1420 I had a chance to test these changes in the new tensorflow-io-nightly build and it seemed to get rid of the memory leak. Thanks for making this fix. I'll close this issue now.
