### ISSUE TITLE
Restructure README.md content

### ISSUE THREAD

**Issue by kvignesh1420** [tensorflow/io#1255]
The [development](https://github.com/tensorflow/io#development) section in the README.md file is not only being used to document instructions for the developers but is also used by Github Actions CI jobs. This section consumes a lot of space which might overwhelm new developers/contributors who just want to get a brief idea about the project through the README.md file.

[Build Status](https://github.com/tensorflow/io#build-status-and-ci) section should be updated as new datasets have been added and the python version for CI builds have changed.

Suggested plan:

- [x] Create a new reference for developers in `docs/` named `developer.md` which will contain the [development](https://github.com/tensorflow/io#development) section. This file can be used by the Github Actions instead of README.md (https://github.com/tensorflow/io/pull/1257)
- [x] Update/Refactor the content and tables in [Build Status](https://github.com/tensorflow/io#build-status-and-ci) section. (https://github.com/tensorflow/io/pull/1257)

Will create PR's as per these items.
cc: @yongtang @terrytangyuan @BryanCutler @vlasenkoalexey for suggestions.

**Comment by yongtang** [comment]
Sounds good to me 👍
