### ISSUE TITLE
FYI: Bazel 0.20.0 now really required (Newer versions no longer working)

### ISSUE THREAD

**Issue by suphoff** [tensorflow/io#126]
A new external dependency requires Bazel 0.20.0
[Google Cloud #2090](https://github.com/googleapis/google-cloud-cpp/issues/2090)

[Workaround to avoid having to globally downgrade bazel ](https://github.com/bazelbuild/bazel/issues/4396#issuecomment-396923909)

**Comment by yongtang** [comment]
@suphoff Created a PR #127 which upgrades grpc and indirectly upgrades protobuf. Should work with bazel 0.22.0 now.

**Comment by suphoff** [comment]
@yongtang: Thanks! Just tested PR #127 and I can confirm it compiles on Bazel 0.22.0

Thanks!
