### ISSUE TITLE
ArrowDataset' object has no attribute 'make_one_shot_iterator'

### ISSUE THREAD

**Issue by MohannadEhabBarakat** [tensorflow/io#1260]
I used the sample code in the readme file to test loading pandas and I got this error:
ArrowDataset' object has no attribute 'make_one_shot_iterator'

code:
!pip install tensorflow_io
import tensorflow as tf
import tensorflow_io.arrow as arrow_io
import pandas as pd

df = pd.DataFrame(
        {
            "A": [1.0, 5, 7, 9, 8],
            "C": [66, 779, 90, 90, 100]
        }
    )

dataset = arrow_io.ArrowDataset.from_pandas(df)

iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

with tf.Session() as sess:
  for i in range(len(df)):
    print(sess.run(next_element))

environment: Colab

**Comment by kvignesh1420** [comment]
@MohannadEhabBarakat the code snippet is outdated:
You can use the dataset as follows:

```python
!pip install tensorflow_io
import tensorflow as tf
import tensorflow_io.arrow as arrow_io
import pandas as pd

df = pd.DataFrame(
{
"A": [1.0, 5, 7, 9, 8],
"C": [66, 779, 90, 90, 100]
}
)

dataset = arrow_io.ArrowDataset.from_pandas(df)

for i in dataset:
  print(i)
```

**Comment by MohannadEhabBarakat** [comment]
@kvignesh1420 
Thanks that works now
