### ISSUE TITLE
Support Apache Arrow for tensorflow-io

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#13]
Note: this issue is from tensorflow/tensorflow#23001 (@BryanCutler 👍 )

Apache Arrow is a standard format for in-memory columnar data. It provides a cross-language platform for systems to communicate and operate on data efficiently.

Adding Arrow support in TensorFlow Dataset will allow systems to interface with TensorFlow in a well defined way, without the need to develop custom converters, serialize data, or write to specialized files.

It would be straightforward to add a base layer of Arrow support that works on Arrow record batches (a common struct for Arrow IPC) and extend that layer to support different kinds of Arrow Ops:

- Python memory / Pandas DataFrames
- Arrow Feather files
- Parquet files
- Socket / Pipes

A slightly more involved Op could use Arrow Flight - Arrow-based messaging over gRPC. Additionally, it would possible to define Ops to connect directly to other systems that can export Arrow data.

**Comment by BryanCutler** [comment]
Thanks for opening this issue and setting up the repo @yongtang! I'll work on porting over the PR soon, thanks!

**Comment by joehoeller** [comment]
when will this be ready?

**Comment by yongtang** [comment]
@joehoeller The PR #36 has been opened to add Apache Arrow dataset support, and is in working-in-progress.
