### ISSUE TITLE
TPU compatibility

### ISSUE THREAD

**Issue by donglinz** [tensorflow/io#1325]
Hi guys,

As we know the available dependencies on a TPU server is differ from a GPU server. Can we have a cheat sheet that highlighting the TPU compatibility of different tensorflow-io data source? Maybe something like this?

| Datasource| TPU compatibility |
| ----------- | ----------- |
| Ignite | Yes/No |
| Kafka | Yes/No|
| Azure blob | Yes/No |

**Comment by donglinz** [comment]
I noticed some similar issues confusing on TPU compatibility [1217](https://github.com/tensorflow/io/issues/1217). So, I think it would be really helpful to have such a list.

**Comment by vlasenkoalexey** [comment]
In order to support different data sources provided by tensorflow-io, it has to be installed on TPU VM. See 
https://github.com/tensorflow/io/issues/716#issuecomment-988362978 for details.
