### ISSUE TITLE
AttributeError: module 'tensorflow.io' has no attribute 'experimental'

### ISSUE THREAD

**Issue by LucasColas** [tensorflow/io#1344]
Hello I install tensorflow and tensorflow-io (with pip : 

> pip install tensorflow-io

). 

but when I try to use tensorflow.io.experimental I have an issue : 

> AttributeError: module 'tensorflow.io' has no attribute 'experimental'

I have Windows 10, Cuda 11.2, GTX 1660Ti. 

Could you help me ? Thank yo

**Comment by kvignesh1420** [comment]
Hi, please use:
```python
import tensorflow_io as tfio
# then use
tfio.experimental. # the apis follow
```

**Comment by LucasColas** [comment]
It's still doesn't work...

**Comment by kvignesh1420** [comment]
@LucasColas can you please paste the code snippet of the API you are trying to import and use?
