### ISSUE TITLE
bazel install tensorflow-io issue

### ISSUE THREAD

**Issue by wutengcoding** [tensorflow/io#1345]
Hi , if i what to use bazel build to install tensorflow-io, what is the path name of bazel build target, Thank u

**Comment by kvignesh1420** [comment]
@wutengcoding you can use the following steps to build the library.
```
# Install tensorflow and configure bazel
sudo ./configure.sh

# Build shared libraries
bazel build -s --verbose_failures $BAZEL_OPTIMIZATION //tensorflow_io/...

# Use tensorflow-io
TFIO_DATAPATH=bazel-bin python3

>>> import tensorflow_io as tfio
>>> 
```

The detailed process is documented [here](https://github.com/tensorflow/io/blob/master/docs/development.md#python)
