### ISSUE TITLE
Add batch support to audio resample

### ISSUE THREAD

**Issue by AlexFuster** [tensorflow/io#1366]
As this library is usually combined with Tensorflow, I think that the resample function should accept batches of audios in the form of tensors of shape [batch_size, samples, channels]. 

I know this can be easily solved by iterating over the batch dimension, but all the Tensorflow functions make this transparent to the user, that's why I was expecting the same here

**Comment by yongtang** [comment]
@AlexFuster Added a PR #1390 for the fix.
