### ISSUE TITLE
Change the default for num_epochs to 1 from None in make_csv_dataset

### ISSUE THREAD

**Issue by dgoldenberg-audiomack** [tensorflow/io#1377]
The default for the `num_epochs` parameter in `make_csv_dataset` is None:

```
    num_epochs: An int specifying the number of times this dataset is repeated.
      If None, cycles through the dataset forever.
```

This is really confusing to the user (at least, it was very surprising and confusing to me). I could not tell why my training appeared to be 'hanging'. It turned out it was due to this default.  I propose that this be changed to 1.  Looping forever is highly unexpected and leads to many user time cycles left trying to debug and understand what's happening.

I'm filing this per the [discussion in TFRS](https://github.com/tensorflow/recommenders/issues/274#issuecomment-824170502) regarding this problem which took a long time to troubleshoot and fix.  Per that discussion,

> [the]... default [...] goes against the compositional nature of tf.data APIs (where you'd normally stick a .repeat() at the end if you want an infinite dataset).

**Comment by yongtang** [comment]
@dgoldenberg-audiomack make_csv_dataset  is part of the core tensorflow repo. Can you open the issue in https://github.com/tensorflow/tensorflow instead?

**Comment by dgoldenberg-audiomack** [comment]
@yongtang Sure, I've just opened https://github.com/tensorflow/tensorflow/issues/48759.

**Comment by yongtang** [comment]
Thanks @dgoldenberg-audiomack . Let's close this issue and track in tensorflow/tensorflow#48759 instead.
