### ISSUE TITLE
macOS build using xcode 12

### ISSUE THREAD

**Issue by faroit** [tensorflow/io#1439]
bazel 3.7.2 doesn't seem to support xcode 12, and tfio doesn't seem to work with a newer bazel version. 

Is there any other way to compile tfio on mac OS 11.3?

**Comment by kvignesh1420** [comment]
@faroit any specific error that is popping up? I am using:
```
$ bazel --version
bazel 3.7.2
$ xcodebuild -version
Xcode 12.5
Build version 12E262

MacOS: 11.3.1
```
and the build step:
```
 $ bazel build -s --verbose_failures $BAZEL_OPTIMIZATION //tensorflow_io/... //tensorflow_io_gcs_filesystem/...
```
works fine

**Comment by faroit** [comment]
now that I added `ARCHFLAGS="-arch x86_64"` it seems to work fine

**Comment by faroit** [comment]
@kvignesh1420 thanks
