### ISSUE TITLE
Improve project directory layout

### ISSUE THREAD

**Issue by kvignesh1420** [tensorflow/io#1440]
The following is a proposal to restructure the `tensorflow-io` directory layout for improving the modularity and maintainability of the project.

The current directory layout (with tree depth 2) is as follows:
```
tensorflow_io
├── BUILD
├── __init__.py
├── arrow
│   ├── BUILD
│   ├── README.md
│   ├── __init__.py
│   ├── kernels
│   ├── ops
│   └── python
├── bigquery
│   ├── BUILD
│   ├── README.md
│   ├── __init__.py
│   ├── kernels
│   ├── ops
│   └── python
├── core
│   ├── BUILD
│   ├── __init__.py
│   ├── go
│   ├── grpc
│   ├── kernels
│   ├── ops
│   ├── plugins
│   ├── python
│   └── swift
├── ignite
│   ├── README.md
│   ├── __init__.py
│   └── python
└── kafka
    ├── __init__.py
    └── python
```

It can be observed that:
- `kafka`, `ignite`, `bigquery` and `arrow` have their own directories with `kernels`, `ops` and `python` to expose their set of API's.
- `core` encompasses all other APIs.

The following are the changes that can be made to improve the consistency with this layout.

move:
- [x] `arrow/kernels` to `core/kernels` (https://github.com/tensorflow/io/pull/1442)
- [x] `arrow/ops` to `core/ops` (https://github.com/tensorflow/io/pull/1442)
- [x] `arrow/python` to `core/python` (https://github.com/tensorflow/io/pull/1442)
- [x] `bigquery/kernels` to `core/kernels` (https://github.com/tensorflow/io/pull/1446)
- [x] `bigquery/ops` to `core/ops` (https://github.com/tensorflow/io/pull/1446)
- [x] `bigquery/python` to `core/python` (https://github.com/tensorflow/io/pull/1446)
- [x] `ignite/python` to `core/python` (https://github.com/tensorflow/io/pull/1447)
- [x] `kafka/python` to `core/python` (https://github.com/tensorflow/io/pull/1447)

After this change, the layout should look something like this:
```
tensorflow_io
├── BUILD
├── __init__.py
├── core
│   ├── BUILD
│   ├── __init__.py
│   ├── go
│   ├── grpc
│   ├── kernels
│   ├── ops
│   ├── plugins
│   ├── python
│   └── swift
│── arrow.py
│── bigquery.py
│── ignite.py
│── kafka.py
```
At this point, the `core` can be split in the following ways:
```
tensorflow_io
├── BUILD
├── __init__.py
├── core
│   ├── BUILD
│   ├── __init__.py
│   ├── go
│   ├── grpc
│   ├── kernels
│   ├── ops
|   |── swift
│── plugins
│── python
│── arrow.py
│── bigquery.py
│── ignite.py
│── kafka.py
```
_Suggestions on how the `go`, `grpc` and `swift` directories can be refactored/moved/renamed are welcome._

This layout helps in:
- [x] splitting the `core` functionality from the `python` layer. (#1450)
- [x] Additionally, it decouples `plugins` from the `core` (atleast from directory p.o.v). (#1452)

This facilitates the addition of new pluggable functionality without overwhelming the core.

**NOTE:** The above mentioned `directory` changes will be done without affecting the `API` layout. The respective `BUILD` files will be modified as per the changes. For example, BigQuery APIs will still be accessible through `tensorflow_io.bigquery`.

cc: @yongtang @terrytangyuan @BryanCutler @vlasenkoalexey @burgerkingeater

**Comment by yongtang** [comment]
@kvignesh1420 Thanks for the work!

One reason everything was put in `core` was to hide non-public python functions. We consider tensorflow-io package as a python package so go, c++, swift code are placed under `core`. The non-public python `ops` are also placed under `core` for hiding from public.

For `kafka`, `ignite`, `bigquery` and `arrow`, they are more or less grandfathered in so we keep the way it is for now.

As of today, I think we can remove `kafka` as it has already been deprecated almost a year ago and there is equivalent new API. `ignite` we may want to deprecate and remove as well, as the usage is limited as far as I know. Both bigquery and arrow are used pretty widely so we may want to at least keep them for an extended time.

**Comment by kvignesh1420** [comment]
@yongtang you are right, there is no need to expose non-public python ops. However, since the API exposure is being controlled by `python/api` I think we should be fine if we move the entire `python` dir outside `core`. The same goes for `plugins` as well (as the notion of `core` including `plugins` was a bit non-intuitive).

However, all these changes would make sense if we are refactoring `arrow`, `bigquery`, `ignite` and `kafka` as well. (As per the initial proposed change). Since that is not the case (at least for some time in the future), what would you suggest to be the action items for this? Let me know.

**Comment by yongtang** [comment]
> However, since the API exposure is being controlled by python/api I think we should be fine if we move the entire python dir outside core. The same goes for plugins as well (as the notion of core including plugins was a bit non-intuitive)

Ah I think that is a good point and makes sense. We can just move the out and not to be part of the `core`.

> arrow, bigquery, ignite and kafka 

@kvignesh1420 I am wondering if we can expose arrow and bigquery to be part of the API module as `tfio.arrow` and `tfio.bigquery` (we can remove top level kafka and ignite)? That will at least make API almost consistent?

**Comment by kvignesh1420** [comment]
@yongtang yes, that can be done. Just like `python/api/audio.py`, we can have `python/api/arrow.py` and `python/api/bigquery.py` which will have the necessary imports. And by modifying `python/api/__init__.py` we can expose:
```
tfio.arrow.*
tfio.bigquery.*
```
Coming to `kafka` and `ignite`, their respective APIs (if applicable) can be moved into the common `python/api`. This will make the API and dir layout almost consistent. WDYT?

**Comment by yongtang** [comment]
> Coming to kafka and ignite, their respective APIs (if applicable) can be moved into the common python/api. This will make the API and dir layout almost consistent. 

I think that make sense. Over time some of the API can be deprecated with different pace due to their respective usage frequency.

**Comment by kvignesh1420** [comment]
Yes. Okay, will give this a try. Thanks.

**Comment by kvignesh1420** [comment]
@yongtang for the final action item, do we want to rename the `core/plugins` directory to `core/filesystems`? after giving it a further thought, moving that dir out of core didn't seem right as it is a part of the `libtensorflow_io.so` object in most of the cases. So was thinking if just the rename would suffice. WDYT?

**Comment by yongtang** [comment]
@kvignesh1420 We have two main `.so` files. One is `libtensorflow_io.so` and another is `libtensorflow_io_plugins.so`.

The reason we have `libtensorflow_io_plugins.so` was because we want to have a `.so` file that only uses tensorflow's C APIs. We name it `plugins` since at that time, the only possible usage of C API was for modular file system plugins.

But now as tensorflow has quite a few different `plugin` types (e.g., optimize graph, devices, etc). In the future, it could be possible to use C API to build customized kernel as well (dont' know when though).

I think changing `core/plugins` directory to `core/filesystems` makes a lot of sense.

For `.so` file naming, actually if we are forward thinking, maybe we can use `libtensorflow_io.so` for tensorflow C API only plugins (and future C only kernels), and use `libtensorflow_io_c++.so` or `libtensorflow_io_legacy.so` for C++ kernels? Though renaming of the `.so` is not so urgent at the moment. We can leave it alone for now.

**Comment by kvignesh1420** [comment]
All the action items have been completed. Closing for now. Thanks, @yongtang for the discussion.

**Comment by kpe** [comment]
@kvignesh1420  
 do I read this correctly - ignite support has been removed completely? So there is no IGFS or IgniteDataset for tensorflow any more? 
 Can you please elaborate on this? Could you think of a replacement that brings a similar low latency as Ignite?

**Comment by kvignesh1420** [comment]
@kpe yes, we deprecated and removed ignite support as a part of the io revamp/refactor effort. The primary reason was that it wasn't being actively maintained and we were less confident in its usage by the community. You can consider alternatives such as Redis for the same. However, it entirely depends on your use case.
