### ISSUE TITLE
How to install tensorflow-io without pulling tensorflow?

### ISSUE THREAD

**Issue by elgalu** [tensorflow/io#1459]
I wonder if it's possible to install this `tensorflow-io` library but without pulling additional ~450mb of stock `tensorflow` package.

My use case is to leverage parts of this library that don't need a whole tensorflow setup.

**Comment by kvignesh1420** [comment]
@elgalu can you let us know the subset of features that you are interested in?

**Comment by elgalu** [comment]
just `tfio.experimental.IODataset.from_prometheus()` for now

**Comment by elgalu** [comment]
I think my request doesn't make sense as this project heavily relies on tensors to store data types, https://github.com/AICoE/prometheus-api-client-python suits my use case better, thanks!

**Comment by kvignesh1420** [comment]
@elgalu yes, tensorflow_io relies on tensorflow for building custom ops. If you want a python based client to connect to prometheus, you can take a look at this: https://github.com/prometheus/client_python
