### ISSUE TITLE
Support Keras callback for predict

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#146]
In Keras, the `model.predict` will generate the output in batches. The data could be accessed from the callbacks.

It should be possible to add support to callbacks so that predict output can be written to somewhere else (e.g., Kafka, etc) whenever possible.

Below is the code snippet:
```python
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)

class OutputCallback(tf.keras.callbacks.Callback):
  def on_predict_batch_begin(self, batch, logs=None):
    print("on_predict_batch_begin:", batch,", ", logs)
  def on_predict_batch_end(self, batch, logs=None):
    print("on_predict_batch_end:", batch,", ", logs)
    
output = OutputCallback()
model.predict(x_test, callbacks=[output])
```

**Comment by terrytangyuan** [comment]
Sounds good. This is similar to [SessionRunHook](https://www.tensorflow.org/api_docs/python/tf/train/SessionRunHook).

**Comment by yongtang** [comment]
We have the Keras callback support for predict now already. Think this issue could be closed. We will roll out additional support for other ops as needed.

**Comment by zaccharieramzi** [comment]
Hi,

I need exactly this and I wanted to know how we were supposed to access the result of the prediction. In the [docs](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/Callback#on_predict_batch_end) I only see that we have access to the batch index but not necessarily to the predictions.

**Comment by yongtang** [comment]
@zaccharieramzi It is actually easier to add an additional layer as an output. Depending on where you want the output to go (console, text file, streaming framework like Kafka, or format files such as parquet/avro), it might be already available or need additional kernel to make it happen. What kinds of output you want the prediction to go?

**Comment by zaccharieramzi** [comment]
Ah ok interesting ! So I would basically build a `SaveModel` which would have the original model as a property and save to file in the `call` method after calling the original model?

And to answer your question, of course it's me again, so I want to save to a `.h5`.

**Comment by yongtang** [comment]
@zaccharieramzi Not really, you can add a `passthrough` layer at the end of you initial model. Then you can just call the mode like before. It will be replayed in background implicitly.

For `h5`..., a new kernel ops will be needed. Can you create a new issue. I will see if I can work on it (likely sometime after v0.13.0 release)

**Comment by zaccharieramzi** [comment]
I see, but if I add this to the original model, then it will also save the prediction results during `fit` and `evaluate` right ?

Also for `h5` I don't necessarily have to wait for a new op, I can just use a python function wrapped in a tf function, no?

**Comment by yongtang** [comment]
@zaccharieramzi 
> I see, but if I add this to the original model, then it will also save the prediction results during fit and evaluate right ?

Not really, you can extend the pre-trained model with a new layer and wire up the output, so that output of the predict will go through your passthrough layer.

> Also for h5 I don't necessarily have to wait for a new op, I can just use a python function wrapped in a tf function, no?

In graph mode that might be challenging, as layers are not run under the context of python. Though there might be some options to allow you to do context switch in between python and graph mode. (haven't check this part for some time).

For distribution strategy, training could be separated from inference.

**Comment by zaccharieramzi** [comment]
> Not really, you can extend the pre-trained model with a new layer and wire up the output, so that output of the predict will go through your passthrough layer.

Yes I think we have been saying the same thing the whole time actually, that's what I meant when I said create a new model. Cool.

> For distribution strategy, training could be separated from inference.

I actually want to use the `MirroredStrategy` at inference time.

> In graph mode that might be challenging, as layers are not run under the context of python.

But can't I use `tf.py_function`? I tried this in [this colab](https://colab.research.google.com/drive/14Rr_t6kY8EGb3f40sf1IH07USU-nmXv4?usp=sharing), and other than this super weird bug in `predict` that I don't understand yet (maybe you have an idea?), the `tf.py_function` seems to work just fine even in graph mode.
I need to test the distribute strategy but not sure how to make sure that I am actually running the `initial_model` in a distributed setting. Do you have any idea?

**Comment by yongtang** [comment]
py_function will be quite slow, as it involved switching back and forth though.

**Comment by zaccharieramzi** [comment]
Yes definitely but isn't it better than a loop with predict then save?

**Comment by yongtang** [comment]
In case of predict, you don't need mirror strategy as it will only incur additional cost. You can just shard the data and do the predict.
