### ISSUE TITLE
tensorflow.python.framework.errors_impl.FailedPreconditionError:  Corrupted response from the server null

### ISSUE THREAD

**Issue by christophedumont5** [tensorflow/io#1463]
Hello, 

I've followed this tutorial https://www.tensorflow.org/io/tutorials/elasticsearch?hl=en , there's an error when executing the code.

python3.9 main.py
  Type  Age                Breed1  Gender Color1    Color2 MaturitySize FurLength Vaccinated Sterilized   Health  Fee                                        Description  PhotoAmt  AdoptionSpeed
0  Cat    3                 Tabby    Male  Black     White        Small     Short         No         No  Healthy  100  Nibble is a 3+ month old ball of cuteness. He ...         1              2
1  Cat    1  Domestic Medium Hair    Male  Black     Brown       Medium    Medium   Not Sure   Not Sure  Healthy    0  I just found it alone yesterday near my apartm...         2              0
2  Dog    1           Mixed Breed    Male  Brown     White       Medium    Medium        Yes         No  Healthy    0  Their pregnant mother was dumped by her irresp...         7              3
3  Dog    4           Mixed Breed  Female  Black     Brown       Medium     Short        Yes         No  Healthy  150  Good guard dog, very alert, active, obedience ...         8              2
4  Dog    1           Mixed Breed    Male  Black  No Color       Medium     Short         No         No  Healthy    0  This handsome yet cute boy is up for adoption....         3              2
11537 14
Number of training samples:  8075
Number of testing sample:  3462
/home/cdt/.local/lib/python3.9/site-packages/elasticsearch/connection/base.py:208: ElasticsearchWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.13/security-minimal-setup.html to enable security.
  warnings.warn(message, category=ElasticsearchWarning)
deleting the 'train' index.
Response from server: {'acknowledged': True}
creating the 'train' index.
Response from server: {'acknowledged': True, 'shards_acknowledged': True, 'index': 'train'}
bulk index the data
/home/cdt/.local/lib/python3.9/site-packages/elasticsearch/connection/base.py:208: ElasticsearchWarning: [types removal] Specifying types in bulk requests is deprecated.
  warnings.warn(message, category=ElasticsearchWarning)
Errors: False, Num of records indexed: 8075
deleting the 'test' index.
Response from server: {'acknowledged': True}
creating the 'test' index.
Response from server: {'acknowledged': True, 'shards_acknowledged': True, 'index': 'test'}
bulk index the data
Errors: False, Num of records indexed: 3462
Connection successful: http://172.16.238.221:9200/_cluster/health
Connection successful: http://172.16.238.221:9200/_cluster/health
{'Type': b'Cat', 'Age': 24, 'Breed1': b'Domestic Short Hair', 'Gender': b'Female', 'Color1': b'Black', 'Color2': b'White', 'MaturitySize': b'Medium', 'FurLength': b'Short', 'Vaccinated': b'Yes', 'Sterilized': b'No', 'Health': b'Healthy', 'Fee': 0, 'PhotoAmt': 2}
Traceback (most recent call last):
  File "/home/cdt/stream/elk/main.py", line 149, in <module>
  File "/home/cdt/stream/elk/main.py", line 108, in get_normalization_layer
  File "/home/cdt/.local/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_preprocessing_layer.py", line 242, in adapt
  File "/home/cdt/.local/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
  File "/home/cdt/.local/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 917, in _call
  File "/home/cdt/.local/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 3023, in __call__
  File "/home/cdt/.local/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 1960, in _call_flat
  File "/home/cdt/.local/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 591, in call
  File "/home/cdt/.local/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
tensorflow.python.framework.errors_impl.FailedPreconditionError:  Corrupted response from the server null
         [[{{node IO>ElasticsearchReadableNext}}]]
         [[IteratorGetNext]] [Op:__inference_adapt_step_829]

Function call stack:
adapt_step

**Comment by kvignesh1420** [comment]
@christophedumont5 if you are running this in colab, can you try restarting the run-time and execute the cells again? Sometimes the elasticsearch instance in colab env might malfunction.

**Comment by kvignesh1420** [comment]
closing as of now. Please reopen if required.
