### ISSUE TITLE
Support for reading files from HDFS.

### ISSUE THREAD

**Issue by yoavz** [tensorflow/io#147]
Hello -- I'm attempting to read a Parquet data file from an HDFS path (substituted `hdfs://path` for the real path below):

```
import tensorflow as tf
import tensorflow_io.parquet

dataset = tensorflow_io.parquet.ParquetDataset("hdfs://path", [1], (tf.int64))
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

with tf.Session() as sess:
  print(sess.run(next_element))
```

Apparently, it seems as though Arrow is attempting to access the file as a local path (`Failed to open local file`) and failing.

```
/home/y.zimmerman/.pyenv/versions/3.6.7/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
2019-03-12 21:18:00.685124: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-03-12 21:18:00.689128: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3200000000 Hz
2019-03-12 21:18:00.690020: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x32de5a0 executing computations on platform Host. Devices:
2019-03-12 21:18:00.690038: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
terminate called after throwing an instance of 'parquet::ParquetException'
  what():  Arrow error: IOError: Failed to open local file: hdfs://path , error: No such file or directory
Aborted
```

Is reading files from HDFS supported with this library? I have previously assumed it is supported through the normal TensorFlow I/O code-paths that allow standard input formats (ex. `TFRecordDataset`) to be read from HDFS [1]. Note that my environment is already configured according to the instructions in [1], and I have verified I can use `tf.data.TFRecordDataset("hdfs://path")` to successfully read a TFRecord file from the HDFS cluster.

[1] https://github.com/tensorflow/examples/blob/master/community/en/docs/deploy/hadoop.md

**Comment by yongtang** [comment]
@yoavz Reading from a non-local file is not supported yet, as the API `OpenFile` is called (not the `Open` interface):
https://github.com/tensorflow/io/blob/master/tensorflow_io/parquet/kernels/parquet_dataset_ops.cc#L200-L204

However, it should be fairly straight ward to add support for additional protocols (like s3/gcs/hdfs). TensorFlow's `RandomAccessFile` already have the support for s3/gcs/hdfs so switching to ParquetReader's `Open` interface should be enough to allow HDFS support.

**Comment by yongtang** [comment]
Added non local filename support for ParquetDataset in #222.
