### ISSUE TITLE
CI enhancement in tensorflow-io?

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#148]
I have been testing CircleCI in the past couple of weeks:
https://circleci.com/gh/yongtang/io/tree/circleci

Overall better than Travis CI in several areas:
- It shares storages among jobs and stages, so that we could build once, test multiple times. For Travis CI, you have to build and test at the same job
- Travis CI has a limit of 50 minutes. CircleCI seems to be 5 hours?
- Initially I thought CircleCI has 1000 minutes per month. But that is for private repo, looks like there is no apparent limit for open source.
- macOS for CircleCI is limited.

Overall, I think the 50 min limitation in Travis CI is a big issue for us. Our repo is getting big with C++ code and dependencies. We are close to the limit again (after optimization last time).

I think CircleCI could be a viable choice. Thought?

/cc @dmitrievanthony @terrytangyuan @BryanCutler

**Comment by BryanCutler** [comment]
+1. I don't have any direct experience with it, but the benefits seem like it's worth a shot. I'm happy to help with the migration too.

**Comment by yongtang** [comment]
Thanks @BryanCutler  Following our discussions in monthly meeting, I think we will try to see if we could use Google CI for build and testing.

**Comment by terrytangyuan** [comment]
Yes as Edd mentioned in the meeting, CircleCI requires unnecessary permissions. I agree that we should try to leverage Google CI (Kokoro) so we don't have the current limitations.

**Comment by yongtang** [comment]
@ewilderj @dynamicwebpaige @martinwicke In the monthly meeting we discussed about the CI enhancement. The main issue we are facing with Travis CI is the 50min execution time restriction. 

With several new additions (e.g., GCP PubSub and TIFF) recently,  many C++ code/dependencies are includes.  The build time 43 min now (https://travis-ci.org/tensorflow/io/builds/504866327). 

From the meeting we are looking for Google CI (kokorun), wondering how we could get started? Or should we setup a script like kokorun.sh for Google CI to invoke?

One note with tensorflow-io repo is that we setup docker containers for several cloud vendor emulations (like Google Cloud emulator for PubSub, and LocalStack for Kinesis).

I don't know about the environment setup of Google CI (kokorun), does it allows running a container through `docker run`?

**Comment by yongtang** [comment]
Google CI Kokoro is in place, think this issue could be resolved.
