### ISSUE TITLE
Multiple warnings on BigQueryDataset

### ISSUE THREAD

**Issue by cadama** [tensorflow/io#1485]
I am receiving lots of error warnings from the tensorflow logs when using BigQueryClient. 

I tested this with `tensorflow_io` 0.19 and `tensorflow` 2.5 as well as with the `tensorflow-io-nightly` and tf 2.6 rc01.  

I am not sure whether it is affecting performance

```
WARNING:tensorflow:AutoGraph could not transform <bound method BigQueryClient.read_session of <tensorflow_io.python.ops.bigquery_dataset_ops.BigQueryClient object at 0x7fcbbc05b210>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: name 'DataFormat' is not defined
```

```
 E tensorflow/core/framework/dataset.cc:552] Unimplemented: Cannot compute input sources for dataset of type IO>BigQueryDataset, because the dataset does not implement `InputDatasets`
```

**Comment by kvignesh1420** [comment]
@cadama I don't think the warning and error mentioned above will affect performance. Refer this https://github.com/tensorflow/tensorflow/issues/37144#issuecomment-617373639 for a similar discussion.

And as far as the error is concerned, the `Unimplemented` status should not be an issue as per the comment:
https://github.com/tensorflow/tensorflow/blob/db23048cd06b7ed1887fd3bb7ef99bdfd9ce3962/tensorflow/core/framework/dataset.h#L958-L964

**Comment by kvignesh1420** [comment]
@cadama any updates on this?

**Comment by YannisPap** [comment]
My code crashes after an error similar to the above.

```
E tensorflow/core/framework/dataset.cc:825] Unimplemented: Cannot merge options for dataset of type IO>BigQueryDataset, because the dataset does not implement `InputDatasets`.

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

I don't know if the segmentation fault is caused by this error or is coincidental.
I use:

- tensorflow==2.5.1
- tensorflow-io==0.19.1

**Comment by kvignesh1420** [comment]
@YannisPap can you please provide a reproducible colab notebook so that it will be easy to identify the root-cause? Thanks!

**Comment by cadama** [comment]
@kvignesh1420 I confirm I don't have any visible performance issues related to this warning. It is just a bit annoying but I guess we all have to get used to tensorflow flooding us with warnings.
