### ISSUE TITLE
Random permutation range dataset (proposal)

### ISSUE THREAD

**Issue by suphoff** [tensorflow/io#149]
Proposing a dataset that generates a permutation of a range(0..n).
I believe this to be useful for table based dataset mapping ([Example from tf_agent](https://github.com/tensorflow/agents/blob/master/tf_agents/replay_buffers/table.py)) and indexed datasets.
Conceptually it would be the same as Dataset.range(n).shuffle(n) - just more efficient.
Initially I plan to use a simple [Fisher–Yates shuffle](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle) - however bitmap based implementations could be considered if storage space becomes an issue. 

```python
# Example usage pattern based on tf_agent's table.py
d = Dataset.permutation(table._capacity).map(lambda x: table.read(x))
```

My plan is to steal most of the random code (seed initialization, save/restore ..) from the dataset shuffle implementation. (I plan to attack this after some initial work on  #109)

**Comment by kvignesh1420** [comment]
@suphoff any updates on this?

**Comment by suphoff** [comment]
@kvignesh1420 - Sorry - no update and not in a position to work on this. Closing the issue.
