### ISSUE TITLE
[GSoC] JSON Reader for tensorflow-io

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#150]
With tensorflow and tensorflow-io, a lot of file formats have been well covered. One format which is used everywhere but has not been supported yet, is the json format file. In tensorflow, it is certainly possible to read json files with `tf.py_func` and pass it through graph or tf.data. There are some limitations with this approach as was mentioned in the tensorflow docs.

We could actually build the json format parser support in, and selectively pass the values to tf.data.

A C++ library of json parser might be needed. The jsoncpp could be a choice, other options are fine as long as the library is in good quality.

Note: This could be part of the GSoC (TensorFlow) project:
https://docs.google.com/document/d/1zT57PFMGZ04A4CvHxAKVpMTgXjsO92_oKeSKwZMc0Gs/edit

**Comment by jjmachan** [comment]
I would like to work on this summer for GSoC. jsoncpp seems to be the best, fastest library for parsing JSON according to this [experiment](https://blog.thousandeyes.com/efficiency-comparison-c-json-libraries/). So is it ok to proceed using jsoncpp?

**Comment by jjmachan** [comment]
[RapidJSON](https://github.com/Tencent/rapidjson)  is also very fast. The results are shown in this [experiment](https://github.com/mloskot/json_benchmark)

**Comment by yongtang** [comment]
Given that tensorflow uses jsoncpp already:
https://github.com/tensorflow/tensorflow/blob/5bd9569d9b7b1c871839d6a62fb93024a4909f23/tensorflow/workspace.bzl#L543-L553

I think we could start with jsoncpp (and potentially reuse some code in tensorflow).

**Comment by jiachengxu** [comment]
Hi @yongtang, can you please assign this issue to me :)

**Comment by yongtang** [comment]
@jiachengxu I think assign the issue need explicit member access from you. I think I don't have the access to add you as the member. Nevertheless I created an label `assigned` to signify.

**Comment by yongtang** [comment]
@jiachengxu It looks like if you create a new issue, I might be able to assign it to you. Can you try create a new issue?

**Comment by jiachengxu** [comment]
I have created #262

**Comment by yongtang** [comment]
Closed through #262.
