### ISSUE TITLE
Impossible to load directory of parquet files using map due to tf.io.gfile.isdir 

### ISSUE THREAD

**Issue by GeraudK** [tensorflow/io#1504]
Hi,

I'm trying to load a list of parquet files in a directory. For this I do:
```
files = tf.data.Dataset.list_files(dir_path)
dataset = files.map(lambda x: tfio.IODataset.from_parquet(x, columns=...))
```
I'm getting the following error:
```
TypeError: Expected binary or unicode string, got <tf.Tensor 'f:0' shape=() dtype=string>
```
Which seems to be coming from `tf.io.gfile.isdir` in v0.20.0 [here](https://github.com/tensorflow/io/blob/master/tensorflow_io/python/ops/parquet_dataset_ops.py#L30)

You can try the following example to replicate the error:
```
tf.io.gfile.isdir(tf.constant("/path/to/file"))
```
And you will get the same error. Is there anyway to use map or interleave to load a directory of parquet files?

Thank you for you help!

**Comment by kvignesh1420** [comment]
@GeraudK I see. Will take a look.

**Comment by kvignesh1420** [comment]
@GeraudK I have opened PR #1521 to address this issue.

On a related note, @yongtang you seem to be working on this issue with this PR: https://github.com/tensorflow/tensorflow/pull/33590. Any plans on going forward with it?

**Comment by kvignesh1420** [comment]
@GeraudK as PR #1521 has been merged, you can use `tensorflow-io-nightly` for the fix. Thanks for reporting the issue.
