### ISSUE TITLE
S3 driver creates temporary files in current directory

### ISSUE THREAD

**Issue by 0x0badc0de** [tensorflow/io#1519]
As a result if a process is executed on an environment where whole FS is read-only except `/tmp` directory - uploading to S3 fails with `Could not append to the internal temporary file`.

That's not the case with GCS which tries to find tmp dir:
https://github.com/tensorflow/io/blob/6110049ff73ed5dc85046737f71057401b679eac/tensorflow_io_gcs_filesystem/core/gcs_helper.cc#L46 =>
https://github.com/tensorflow/tensorflow/blob/17774a11b576186e439174298af82b096dcd5582/tensorflow/core/platform/path.cc#L329

Compare with S3 which just passes null prefix downstream:
https://github.com/tensorflow/io/blob/6110049ff73ed5dc85046737f71057401b679eac/tensorflow_io/core/filesystems/s3/s3_filesystem.cc#L358

TF S3 implementation just uses `/tmp`:
https://github.com/tensorflow/tensorflow/blob/17774a11b576186e439174298af82b096dcd5582/tensorflow/core/platform/s3/s3_file_system.cc#L57

Quick workaround can be to `os.chdir("/tmp")` if acceptable.

**Comment by yongtang** [comment]
Added a PR #1526 for the fix.
