### ISSUE TITLE
tfio.audio.AudioIOTensor does not work with TPU

### ISSUE THREAD

**Issue by invoxiaglo** [tensorflow/io#1524]
Hello, 

I am trying to use tensorflow-io for decoding .wav files and using TPU for training. It works fine on GPU but the operation is apparently not registered for TPU.

Here is a colab showing the error:
https://colab.research.google.com/drive/1gSP3bhmDkMFwHwxWWc3B3hdR9SNA0hM9?usp=sharing

The error is the following:

```
NotFoundError: Op type not registered 'IO>AudioReadableInit' in binary running on n-6a025964-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. [Op:BatchDatasetV2]
```

Is there other ways to decode .wav files and use TPU?

**Comment by vlasenkoalexey** [comment]
In order to support different data sources provided by tensorflow-io, it has to be installed on TPU VM. See 
https://github.com/tensorflow/io/issues/716#issuecomment-988362978 for details.
