### ISSUE TITLE
Support a variant for tensorflow-rocm

### ISSUE THREAD

**Issue by elukey** [tensorflow/io#1548]
Hi everybody!

At the Wikimedia Foundation we use AMD ROCm GPUs, and we are currently testing their latest drivers/tools (4.3.1) and the related new `tensorflow-rocm` 2.6 (a fork of the official `tensorflow` that supports AMD GPUs). The main issue that we are encountering is related to Hadoop HDFS support, since IIUC it has been offloaded to `tensorflow-io`, that in turns requires `tensorflow` when installed (that doesn't play well, in my tests, with `tensorflow-rocm`).

I created https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/1461 on the ROCm end as well.

Since `tensorflow-rocm` is a drop-in replacement of `tensorflow` (or at least, it should be) I am wondering if you could add a variant to `setup.py` to variate the dependency to tensorflow if needed. For example, `pip install tensorflow-io[rocm]` would try to install `tensorflow-rocm` and not `tensorflow`. Would it be possible/feasible in your opinion?

Thanks in advance,

Luca

**Comment by yongtang** [comment]
@elukey That sounds good to me. Never used tensorflow-rocm before so I may need to spend some time to take a look before a PR. But in the meantime, if you can create a PR that will be better.

**Comment by elukey** [comment]
@yongtang any feedback? :)

**Comment by yongtang** [comment]
@elukey Sorry I am out of office and have limited access to my usual workstation. Tt is a little slowed to setup the build env. I will try to get env setup soon to work on this issue while on the road..

**Comment by elukey** [comment]
Ack thanks! @jayfurmanek if you have time can you check/review the pull request in the meantime?

**Comment by jayfurmanek** [comment]
I don't have review authority on tensorflow-io, but I did try your PR and it does work as expected.
