### ISSUE TITLE
Release 0.21 is incompatible in pip with TF 2.7

### ISSUE THREAD

**Issue by leandro-gracia-gil** [tensorflow/io#1554]
If you try to install both tensorflow 2.7 and the latest available tensorflow-io you get a pip error saying tensorflow-io requires tensorflow >= 2.6 but < 2.7.

Would it be possible to produce a newer tensorflow-io release compatible with tensorflow 2.7?

**Comment by Marmotte06** [comment]
Same here, trying to update Tensorflow_io automatically downgrades Tensorflow to version 2.6.1

**Comment by yongtang** [comment]
We are working on getting 0.22 release. Once PR #1546 is merged, 0.22 will be released immediately.

**Comment by yongtang** [comment]
tensorflow-io 0.22.0 has been released (see #1555) which is compatible with TF 2.7. I am closing this issue now but feel free to re-open if any issue is encountered.
