### ISSUE TITLE
Python 3.10 - Setup.py Doesn't Allow

### ISSUE THREAD

**Issue by sampathweb** [tensorflow/io#1591]
Thanks for the release of v0.23.0 and generating the wheels for Python 3.10, but the `setup.py` still doesn't allow for Pythob 3.10 - 

https://github.com/tensorflow/io/blob/master/setup.py#L168 ( `python_requires=">=3.6, <3.10",`)

And also add support for Python 3.10 in setup as (`"Programming Language :: Python :: 3.10",`)

This is blocking TF 2.8 support of Python 3.10

**Comment by yongtang** [comment]
@sampathweb Thanks for the info and sorry for that. A PR #1592 has been created to fix the issue.

**Comment by sampathweb** [comment]
@yongtang - Thank you so much for doing the fix so quickly.  Any ETA on the Release of 0.24.0 into PyPi?  Can we do this today so it can be tested before TF 2.8 branch cut Tomorrow (Dec'16th)?

cc: @mihaimaruseac

**Comment by yongtang** [comment]
@mihaimaruseac @sampathweb The 0.23.1 has been released and a PR to update TF's dependency has been created: https://github.com/tensorflow/tensorflow/pull/53442

**Comment by sampathweb** [comment]
@yongtang - Thank you so much for resolving this issue.
