### ISSUE TITLE
decode_json empty lists -> Segmentation fault

### ISSUE THREAD

**Issue by denadai2** [tensorflow/io#1605]
Dear all, 
I have a huge problem using decode_json, which results in a segmentation fault core dumped with:

    import tensorflow as tf
    print(tf.__version__)
    import tensorflow_io as tfio
    print(tfio.__version__)

    INPUT_SPEC = {
        "user_id": tf.TensorSpec(shape=(), dtype=tf.string),
        "actions": tf.TensorSpec(shape=(None,), dtype=tf.string),
    }
    tfio.experimental.serialization.decode_json(
            b'{"user_id":"0000asdasdasdasdas dasdasdasdasdasd","actions":[]}\n',
        INPUT_SPEC, name=None
        )

    '2.5.2'
    '0.19.1'

could you help me?

**Comment by denadai2** [comment]
The bug is present also in tensorflow 2.7.0 with tensorflow-io 0.23.1

**Comment by denadai2** [comment]
I believe @yongtang is the expert of this function :)

**Comment by yongtang** [comment]
Added a PR #1608 for the fix.

**Comment by denadai2** [comment]
great! Thanks!

**Comment by denadai2** [comment]
@yongtang is there any hope to see a version 0.23.2 for tensorflow 2.7 with this bugfix? Tensorflow 2.8 is not ready yet :) 

thx

**Comment by yongtang** [comment]
@denadai2 In our monthly community meeting, it was mentioned that 2.8 will be imminent (another rc was supposed to be out already though it might be delayed a little). If it take further time to see 2.8 release we can certainly consider another release of tensorflow-io in between.

**Comment by denadai2** [comment]
> @denadai2 In our monthly community meeting, it was mentioned that 2.8 will be imminent (another rc was supposed to be out already though it might be delayed a little). If it take further time to see 2.8 release we can certainly consider another release of tensorflow-io in between.

thank you!
