### ISSUE TITLE
Remove the generated/outdated R package

### ISSUE THREAD

**Issue by terrytangyuan** [tensorflow/io#1623]
I am considering moving the generated R package because it's always outdated. Currently, we rely on https://github.com/rstudio/reticulate and provide a thin wrapper. Actually `reticulate` package is mature enough and if users are interested, they can use `reticulate` to import `tensorflow-io` Python package directly in R.

Removing the generated R package would make it easier for maintenance (unfortunately CRAN (where R packages are hosted) does not provide an automated process to release R packages and manual inspections are usually required). We could update the documentation to provide some suggestions to existing/new users on how to run TensorFlow I/O in R.

WDYT? @tensorflow/sig-io-maintainers

**Comment by yongtang** [comment]
+1 👍

**Comment by kvignesh1420** [comment]
@terrytangyuan this makes sense. We can notify the users about the "end-of-support" during the next release and suggest alternatives.
