### ISSUE TITLE
Does tensorflow_io.kafka support consumer group auto-partition assignment and offset commits?

### ISSUE THREAD

**Issue by zhjunqin** [tensorflow/io#163]
Does Kafka support consumer group auto-partition assignment and offset commits?

I checked code, seems it doesn't support. Do you have any plan on this?

Thanks!

**Comment by yongtang** [comment]
We could add those support with additional args.

**Comment by kvignesh1420** [comment]
@yongtang I guess we can't achieve this using the existing ops. Can I start working on a PR for this? We can have a discussion in that thread.

**Comment by yongtang** [comment]
@kvignesh1420 Sure! Would be great if you can open a PR (even a working in progress one). Contributions are always welcomed.

**Comment by kvignesh1420** [comment]
@zhjunqin , the feature is now available in the `tfio.experimental.streaming.KafkaGroupIODataset` API. Would be great if you can test it and give us the feedback.

Reference: https://www.tensorflow.org/io/api_docs/python/tfio/experimental/streaming/KafkaGroupIODataset
