### ISSUE TITLE
parquet error:   Unexpected end of stream

### ISSUE THREAD

**Issue by cnglen** [tensorflow/io#1667]
tfio.__version__:  '0.24.0'

- pd.read_parquet(): OK
- tfio.IODataset.from_parquet(f1): Failed with error

```
terminate called after throwing an instance of 'parquet::ParquetException'
  what():  Unexpected end of stream
Aborted
```

Any help?

**Comment by CourierKyn** [comment]
Did you fix this? I encountered the same error.

**Comment by samiemostafavi** [comment]
I am facing the same error, using Tensorflow 2.8.0 and tfio 0.25.0:

    df = pd.read_parquet(files[0], engine='pyarrow')
    print(len(df))
    
    df_tfio = tfio.IODataset.from_parquet(filename = files[0])
    ds = df_tfio.take(len(df))

    for d in ds:
      print(d)

Throws this error when reaches ~80% of the file:

    libc++abi: terminating with uncaught exception of type parquet::ParquetException: Unexpected end of stream

**Comment by BenoitLeguay** [comment]
Hello !
I also ran into this issue. Do you guys have any news on that ?
Thanks :)

**Comment by daviddwlee84** [comment]
Same issue here

```
tensorflow                        2.13.0
tensorflow-io                     0.33.0
```

```
terminate called after throwing an instance of 'parquet::ParquetException'
  what():  Unexpected end of stream
Aborted (core dumped)
```

**Comment by BenoitLeguay** [comment]
Hey @daviddwlee84, on my side, the reason of the error was because I had null values in my parquet files.

**Comment by daviddwlee84** [comment]
> Hey @daviddwlee84, on my side, the reason of the error was because I had null values in my parquet files.

Seems like that. 😂

https://github.com/tensorflow/io/issues/1781#issuecomment-1485061779
