### ISSUE TITLE
TypeError: Invalid shape (0,) for image data (dicom data)

### ISSUE THREAD

**Issue by innat** [tensorflow/io#1743]
# Issue Type

Bug

# Tensorflow Version

2.6.4

# TensorFlow I.O. Version

0.21.0

# Custom Code

Yes

# OS Platform and Distribution

Ubuntu

# Current Behaviour?

I've tried to open a dicom file with tensorflow and tensorflow-io. And it fails to open the file for some cases. 

DATA SET: https://www.kaggle.com/competitions/rsna-2022-cervical-spine-fracture-detection/data

![image](https://user-images.githubusercontent.com/17668390/205439139-fadcac61-82f6-426d-8e60-f0e444f8f6bd.png)

To reproduce the problem, just use any of the dicom file from the above data source. Hopefully, you will able to reproduce the issue.

# Standalone code to reproduce the issue

```python
dcm_data = 'train_images/1.2.826.0.1.3680043.10261/107.dcm'
image_bytes = tf.io.read_file(dcm_data)
image = tfio.image.decode_dicom_image(image_bytes, dtype=tf.uint16)
plt.imshow(image) # image is empty, why?
```

But 

```python
import pydicom
img = pydicom.read_file(dcm_data).pixel_array
plt.imshow(img) # OK
```

### Relevant log output

```shell
TypeError: Invalid shape (0,) for image data
```

**Comment by MarkDaoust** [comment]
Oh, I didn't know you could do that.

**Comment by MarkDaoust** [comment]
Note that if tfio's dicom is working, just not for these files, then they'll probably need an example of a file that causes it to fail like this.

**Comment by MarkDaoust** [comment]
Yeah, you shared a link to the whole dataaset. It will be easier for the owners here if you can share a link to a specific file that's failing to load.

**Comment by innat** [comment]
@MarkDaoust Thanks for the response. 

Now, I found that, the issue is about the dtype while loading the dicom files. If I use `tf.uint8` or `tf.uint16` in `tfio.image.decode_dicom_image` function, it returned `(0,)` an empty array. But if I use any of the following (`tf.uint32`, `tf.uint64`, `tf.float32`, `tf.float64`), it works. So, `tf.uint8/16` doesn't work on these files (link below) but other files on the same dataset (the whole dataset, posted above).

On the other hand, `pydicom` seems work just fine, it returns `int16` input array. Below are some dicom files and sample gist. 

Here are some dicom files. [LINK](https://drive.google.com/drive/folders/1VUJZEazB6fgOaTHi5Is99c0ItP_Etfd8?usp=sharing).
[Colab](https://colab.research.google.com/drive/1sLBmegNVciHTszxFjdbpVtzWVcAUdWzU?usp=sharing).

---

Apart from this, using `tfio.image.decode_dicom_image` in notebook, it prints the following logs. Is there any way to disable them? And how should I interpret them - what do they mean?

```
W: DcmMetaInfo: No Group Length available in Meta Information Header
W: DcmItem: Length of element (7fe0,0010) is not a multiple of 2 (VR=OW)
W: DcmMetaInfo: No Group Length available in Meta Information Header
W: DcmItem: Length of element (7fe0,0010) is not a multiple of 2 (VR=OW)
W: DcmMetaInfo: No Group Length available in Meta Information Header
W: DcmItem: Length of element (7fe0,0010) is not a multiple of 2 (VR=OW)
W: DcmMetaInfo: No Group Length available in Meta Information Header
W: DcmItem: Length of element (7fe0,0010) is not a multiple of 2 (VR=OW)
```

**Comment by innat** [comment]
Any update on this?
