### ISSUE TITLE
Query  tf.sysconfig.get_compile_flags() for _GLIBCXX_USE_CXX11_ABI version

### ISSUE THREAD

**Issue by suphoff** [tensorflow/io#175]
Replace hard coded  _GLIBCXX_USE_CXX11_ABI value in ./configure (and in various BUILD files) with value returned from  tf.sysconfig.get_compile_flags().

**Comment by yongtang** [comment]
@suphoff That is a good solution to fix several issues we are facing 👍 . I will take a look and see if I could come up with something quick.

Also /cc @henrytansetiawan as this might be related to the issue you encountered.

**Comment by suphoff** [comment]
@yongtang : I have a working prototype - will add some error checking and submit a pull request tomorrow.

**Comment by yongtang** [comment]
Close this one as #176 has been merged.
