### ISSUE TITLE
Unable to load libtensorflow_io_plugins.so for aarch64 tensorflow-io-gcs-filesystem wheels

### ISSUE THREAD

**Issue by matthewfeickert** [tensorflow/io#1755]
# Description

The `aarch64` architecture wheels for `tensorflow-io-gcs-filesystem` are missing the `libtensorflow_io_plugins.so` file. Here is a reproducible demonstration of this problem for `aarch64` but not for `amd64` using Docker for `tensorflow-io-gcs-filesystem` `v0.29.0` installed through `tensorflow-aarch64`. However it is noted that this library is not used in the passing example for the `amd64` wheel.

## Minimal failing example for `arm64`

```console
$ docker run --rm -ti --platform linux/arm64 python:3.9 /bin/bash
root@38df62ecc9c2:/# python -m venv venv && . venv/bin/activate
(venv) root@38df62ecc9c2:/# python -m pip --quiet install --upgrade pip setuptools wheel
(venv) root@38df62ecc9c2:/# python -m pip --quiet install 'tensorflow-aarch64==2.11.0'
(venv) root@38df62ecc9c2:/# python -m pip list | grep tensor
tensorboard                  2.11.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow-aarch64           2.11.0
tensorflow-estimator         2.11.0
tensorflow-io-gcs-filesystem 0.29.0
(venv) root@38df62ecc9c2:/# python -c 'import tensorflow_io'
/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ["[Errno 2] The file to load file system plugin from does not exist.: '/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so'"]
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: cannot open shared object file: No such file or directory']
  warnings.warn(f"file system plugins are not loaded: {e}")
(venv) root@38df62ecc9c2:/# python -c 'import tensorflow'  # for consistency with passing example
/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ["[Errno 2] The file to load file system plugin from does not exist.: '/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so'"]
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: cannot open shared object file: No such file or directory']
  warnings.warn(f"file system plugins are not loaded: {e}")
(venv) root@38df62ecc9c2:/# find /venv/ -type f -iname "libtensorflow_io_plugins.so"
(venv) root@38df62ecc9c2:/#
```

## Minimal working example for `amd64`

```console
$ docker run --rm -ti --platform linux/amd64 python:3.9 /bin/bash
root@41f993536792:/# python -m venv venv && . venv/bin/activate
(venv) root@41f993536792:/# python -m pip --quiet install --upgrade pip setuptools wheel
(venv) root@41f993536792:/# python -m pip --quiet install 'tensorflow-cpu==2.11.0'
(venv) root@41f993536792:/# python -m pip list | grep tensor
tensorboard                  2.11.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow-cpu               2.11.0
tensorflow-estimator         2.11.0
tensorflow-io-gcs-filesystem 0.29.0
(venv) root@41f993536792:/# python -c 'import tensorflow'
2023-01-03 19:55:09.854903: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-03 19:55:09.922735: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
(venv) root@41f993536792:/# find /venv/ -type f -iname "libtensorflow_io_plugins.so"
(venv) root@41f993536792:/# find /venv/ -type f -iname "libtensorflow_io*.so"
/venv/lib/python3.9/site-packages/tensorflow_io_gcs_filesystem/core/python/ops/libtensorflow_io_gcs_filesystem.so
(venv) root@41f993536792:/# 
```

# Expectation

For the `aarch64` wheels to be able to be used without the warning

```pytb
/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ["[Errno 2] The file to load file system plugin from does not exist.: '/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so'"]
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: cannot open shared object file: No such file or directory']
  warnings.warn(f"file system plugins are not loaded: {e}")
```

# Related Issues

(I'm creating this one as the others don't have easily reproducible examples)

* Issue #1532
* Issue #1643
* Issue #1689
* Issue #1735
* Issue #1754

**Comment by gfalcone** [comment]
Having the same issue on my end too

**Comment by AIEMERIC** [comment]
is there a tensorflow 23.1 wheel for aarch64? I'm having the same issue, pretty anoying...

**Comment by matthewfeickert** [comment]
> is there a tensorflow 23.1 wheel for aarch64?

I'm not sure what you're referring to as there isn't a `v23.1` for `tensorflow`. Can you elaborate? (or maybe that was a typo?)

**Comment by AIEMERIC** [comment]
> > is there a tensorflow 23.1 wheel for aarch64?
> 
> I'm not sure what you're referring to as there isn't a `v23.1` for `tensorflow`. Can you elaborate? (or maybe that was a typo?). If that's supposed to be CalVer then I'm also confused what you mean, or why you think that would help things.

Hi, sorry i wanted to say `tensorflow-io` version `0.23.1`. Some people say that it's working on this version, but impossible to find an `aarch64` wheel compatible...

**Comment by matthewfeickert** [comment]
> Hi, sorry i wanted to say tensorflow-io version 0.23.1.

Gotcha. No, if you check the release history for `tensorflow-io` on PyPI (https://pypi.org/project/tensorflow-io/#history) then for [`tensorflow-io` `v0.23.1`](https://pypi.org/project/tensorflow-io/0.23.1/#files) there are no `aarch64` wheels. You can also check the available versions of a package for your Python distribution from the command line with

```
python -m pip index versions <package name>
```

**Comment by AIEMERIC** [comment]
> 

Thanks! So there is no way to run mi AI model on my rapsberry pi?

**Comment by matthewfeickert** [comment]
> Thanks! So there is no way to run mi AI model on my rapsberry pi?

I think you'd need to give more information in Issue #1754 about what your model requirements are in terms of TensorFlow versions to get an answer there. If you can establish hard lower bounds in terms of dependencies for your project and describe them on your Issue I think people can give more informed feedback.

I know nothing about your project, though if you're trying to run on a Raspberry Pi then maybe TensorFlow Lite might be a good choice? (Maybe not though, you would know best)

**Comment by gfalcone** [comment]
@yongtang sorry for the ping out of knowhere, but is this a known issue :) ?

**Comment by guoz23** [comment]
Im having the same issue as it cant find libtensorflow_io_plugins.so. Im currently using M1 mac.

**Comment by thanhle7** [comment]
Reinstall tensorflow-io can help:

`pip3 install --force-reinstall tensorflow-io`

**Comment by matthewfeickert** [comment]
This still remains an issue with the [`v0.30.0`](https://github.com/tensorflow/io/releases/tag/v0.30.0) release on 2023-01-21:

```console
$ docker run --rm -ti --platform linux/arm64 python:3.9 /bin/bash
root@cc02cb0b48df:/# python -m venv venv && . venv/bin/activate
(venv) root@cc02cb0b48df:/# python -m pip --quiet install --upgrade pip setuptools wheel
(venv) root@cc02cb0b48df:/# python -m pip --quiet install 'tensorflow-aarch64==2.11.0'
(venv) root@cc02cb0b48df:/# python -m pip list | grep tensor
tensorboard                  2.11.2
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow-aarch64           2.11.0
tensorflow-estimator         2.11.0
tensorflow-io-gcs-filesystem 0.30.0
(venv) root@cc02cb0b48df:/# python -c 'import tensorflow_io'
/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ["[Errno 2] The file to load file system plugin from does not exist.: '/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so'"]
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: cannot open shared object file: No such file or directory']
  warnings.warn(f"file system plugins are not loaded: {e}")
(venv) root@cc02cb0b48df:/# python -c 'import tensorflow'
/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ["[Errno 2] The file to load file system plugin from does not exist.: '/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so'"]
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: cannot open shared object file: No such file or directory']
  warnings.warn(f"file system plugins are not loaded: {e}")
(venv) root@cc02cb0b48df:/# find /venv/ -type f -iname "libtensorflow_io_plugins.so"
(venv) root@cc02cb0b48df:/#
```

**Comment by matthewfeickert** [comment]
Actually, in retrospect the authors tell us in the docs that we shouldn't expect `tensorflow-io` to get picked up automatically (so I'm not really sure why it does for systems other than `aarch64`)

https://github.com/tensorflow/io/blob/2d0c38e39455f7dc9ea70dd6432b28c443331b68/README.md?plain=1#L14-L15

and their compatibility instructions

https://github.com/tensorflow/io/blob/2d0c38e39455f7dc9ea70dd6432b28c443331b68/README.md?plain=1#L86-L91

work

```console
> docker run --rm -ti --platform linux/arm64 python:3.9 /bin/bash
root@4765712f639c:/# python -m venv venv && . venv/bin/activate
(venv) root@4765712f639c:/# python -m pip --quiet install --upgrade pip setuptools wheel
(venv) root@4765712f639c:/# python -m pip --quiet install --upgrade 'tensorflow-io[tensorflow]'
(venv) root@4765712f639c:/# python -m pip list | grep tensor
tensorboard                  2.11.2
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.11.0
tensorflow-cpu-aws           2.11.0
tensorflow-estimator         2.11.0
tensorflow-io                0.30.0
tensorflow-io-gcs-filesystem 0.30.0
(venv) root@4765712f639c:/# python -c 'import tensorflow_io'
(venv) root@4765712f639c:/# 
```

So I guess from the authors' perspective there is no problem here.

@yongtang @kvignesh1420, as you reviewed @elukey's PR #1551 that supported this `tensorflow` extra functionality, can you comment on if I have the right understanding that as `tensorflow-io` is a standalone supplement to `tensorflow` we shouldn't have any expectations on it getting installed without explicitly requiring it.

If so, can you comment on why the "Minimal working example for `amd64`" example in my first comment doesn't incur the same `UserWarning`?

**Comment by elfringham** [comment]
@matthewfeickert There was a bug in the packaging of tensorflow-io-gcs-filesystem for AARCH64 that led to parts of tensorflow-io being incorrectly included. This has been corrected in the build scripts and will resolve the issue in the next release.
In the meantime as a workaround you can
`python -m pip install tensorflow-io
python -m pip uninstall -y tensorflow-io`
Installing and then removing tensorflow-io will clean up the install of tensorflow-io-gcs-filesystem by removing the incorrectly included files and leave you with a working system.
I am sorry for the inconvenience.

**Comment by matthewfeickert** [comment]
Thanks very much @elfringham for the summary! That's quite useful to understand and I appreciate you taking the time to explain it. Thanks for all your work!

**Comment by MrAta** [comment]
@elfringham Thanks for the pointer.
Mind elaborating more about the issue and the fix?
I'm having a similar issue with centos7 where the `libtensorflow_io_plugins.so` contains no symbol except a few which makes tf throwing a warning not being able to find a TF_InitPlugins symbol.

**Comment by wendaovswendao** [comment]
.so' (no such file) still exists， I am is arm64 linux, I can build the .so file from source code?Thanks

**Comment by elfringham** [comment]
I believe that this issue is resolved with the release of tensorflow-io 0.31.0.
If anyone is still having issues on aarch64 then please give full details of your setup.

**Comment by matthewfeickert** [comment]
Yeah, using the extra workflow works well

```console
$ docker run --privileged --rm tonistiigi/binfmt --install arm64  # I'm on an amd64 machine
$ docker run --rm -ti --platform linux/arm64 python:3.10 /bin/bash
root@61821132ad7d:/# python -m venv venv && . venv/bin/activate
(venv) root@61821132ad7d:/# python -m pip --quiet install --upgrade pip setuptools wheel
(venv) root@61821132ad7d:/# python -m pip --quiet install --upgrade 'tensorflow-io[tensorflow]==0.31.0'
(venv) root@61821132ad7d:/# python -c 'import tensorflow_io; print(tensorflow_io)'
<module 'tensorflow_io' from '/venv/lib/python3.10/site-packages/tensorflow_io/__init__.py'>
(venv) root@61821132ad7d:/# find /venv/ -type f -iname "libtensorflow_io_plugins.so"
/venv/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so
(venv) root@61821132ad7d:/#
```

so I'm going to close this as I think this is sufficiently resolved. :+1:

**Comment by BARKHAC** [comment]
I am working on x86 , windows 11. Python 3.11
tensorflow-io=0.31.0

The error:

NotImplementedError: unable to open file: libtensorflow_io.so, from paths: ['C:\\Users\\bchai\\PycharmProjects\\AudioML\\venv\\Lib\\site-packages\\tensorflow_io\\python\\ops\\libtensorflow_io.so']
    caused by: ['C:\\Users\\bchai\\PycharmProjects\\AudioML\\venv\\Lib\\site-packages\\tensorflow_io\\python\\ops\\libtensorflow_io.so not found']

The file does exist at this location. I have tried downgrading tensorflow-io to 0.30.0 but that did not help either

**Comment by BARKHAC** [comment]
More information^ I installed tensorflow and tensorflow-io both using pip separately

pip install tensorflow
pip install tensorflow-io

**Comment by TiagoGouvea** [comment]
Looking at many questions on stackoverflow, with 5k view, 3 answers, and 6 up votes on the best answer, make me convinced that it just doesn't work for the major of devs trying.

**Comment by trueToastedCode** [comment]
> # Description
> The `aarch64` architecture wheels for `tensorflow-io-gcs-filesystem` are missing the `libtensorflow_io_plugins.so` file. Here is a reproducible demonstration of this problem for `aarch64` but not for `amd64` using Docker for `tensorflow-io-gcs-filesystem` `v0.29.0` installed through `tensorflow-aarch64`. However it is noted that this library is not used in the passing example for the `amd64` wheel.
> 
> ## Minimal failing example for `arm64`
> ```
> $ docker run --rm -ti --platform linux/arm64 python:3.9 /bin/bash
> root@38df62ecc9c2:/# python -m venv venv && . venv/bin/activate
> (venv) root@38df62ecc9c2:/# python -m pip --quiet install --upgrade pip setuptools wheel
> (venv) root@38df62ecc9c2:/# python -m pip --quiet install 'tensorflow-aarch64==2.11.0'
> (venv) root@38df62ecc9c2:/# python -m pip list | grep tensor
> tensorboard                  2.11.0
> tensorboard-data-server      0.6.1
> tensorboard-plugin-wit       1.8.1
> tensorflow-aarch64           2.11.0
> tensorflow-estimator         2.11.0
> tensorflow-io-gcs-filesystem 0.29.0
> (venv) root@38df62ecc9c2:/# python -c 'import tensorflow_io'
> /venv/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
> caused by: ["[Errno 2] The file to load file system plugin from does not exist.: '/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so'"]
>   warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
> /venv/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
> caused by: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: cannot open shared object file: No such file or directory']
>   warnings.warn(f"file system plugins are not loaded: {e}")
> (venv) root@38df62ecc9c2:/# python -c 'import tensorflow'  # for consistency with passing example
> /venv/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
> caused by: ["[Errno 2] The file to load file system plugin from does not exist.: '/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so'"]
>   warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
> /venv/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
> caused by: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: cannot open shared object file: No such file or directory']
>   warnings.warn(f"file system plugins are not loaded: {e}")
> (venv) root@38df62ecc9c2:/# find /venv/ -type f -iname "libtensorflow_io_plugins.so"
> (venv) root@38df62ecc9c2:/#
> ```
> 
> ## Minimal working example for `amd64`
> ```
> $ docker run --rm -ti --platform linux/amd64 python:3.9 /bin/bash
> root@41f993536792:/# python -m venv venv && . venv/bin/activate
> (venv) root@41f993536792:/# python -m pip --quiet install --upgrade pip setuptools wheel
> (venv) root@41f993536792:/# python -m pip --quiet install 'tensorflow-cpu==2.11.0'
> (venv) root@41f993536792:/# python -m pip list | grep tensor
> tensorboard                  2.11.0
> tensorboard-data-server      0.6.1
> tensorboard-plugin-wit       1.8.1
> tensorflow-cpu               2.11.0
> tensorflow-estimator         2.11.0
> tensorflow-io-gcs-filesystem 0.29.0
> (venv) root@41f993536792:/# python -c 'import tensorflow'
> 2023-01-03 19:55:09.854903: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2023-01-03 19:55:09.922735: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
> (venv) root@41f993536792:/# find /venv/ -type f -iname "libtensorflow_io_plugins.so"
> (venv) root@41f993536792:/# find /venv/ -type f -iname "libtensorflow_io*.so"
> /venv/lib/python3.9/site-packages/tensorflow_io_gcs_filesystem/core/python/ops/libtensorflow_io_gcs_filesystem.so
> (venv) root@41f993536792:/# 
> ```
> 
> # Expectation
> For the `aarch64` wheels to be able to be used without the warning
> 
> ```
> /venv/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
> caused by: ["[Errno 2] The file to load file system plugin from does not exist.: '/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so'"]
>   warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
> /venv/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
> caused by: ['/venv/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: cannot open shared object file: No such file or directory']
>   warnings.warn(f"file system plugins are not loaded: {e}")
> ```
> 
> # Related Issues
> (I'm creating this one as the others don't have easily reproducible examples)
> 
> * Issue [tensorflow-io cannot be used with tf compiled with --config=monolithic #1532](https://github.com/tensorflow/io/issues/1532)
> * Issue [Can not build `tensorflow-io` from source on Apple M1 #1643](https://github.com/tensorflow/io/issues/1643)
> * Issue [tensorflow io on Mac not working with s3 paths #1689](https://github.com/tensorflow/io/issues/1689)
> * Issue [Fail to use version 0.28.0 caused by undefined symbol #1735](https://github.com/tensorflow/io/issues/1735)
> * Issue [unable to open file: libtensorflow_io.so, undefined symbol raspberry pi os 64bits #1754](https://github.com/tensorflow/io/issues/1754)

I don't understand why this issue has been closed, cause this issue still occurs.

**Comment by elfringham** [comment]
@trueToastedCode It was closed because this works.
```
$ docker run --rm -ti --platform linux/arm64 python:3.9 /bin/bash
root@9dd720c550b9:/# python -m venv venv && . venv/bin/activate
(venv) root@9dd720c550b9:/# python -m pip --quiet install --upgrade pip setuptools wheel
(venv) root@9dd720c550b9:/# python -m pip --quiet install 'tensorflow-aarch64==2.12.0'
(venv) root@9dd720c550b9:/# python -m pip list | grep tensor
tensorboard                  2.12.3
tensorboard-data-server      0.7.1
tensorflow-aarch64           2.12.0
tensorflow-estimator         2.12.0
tensorflow-io-gcs-filesystem 0.32.0
(venv) root@9dd720c550b9:/# python -c 'import tensorflow'
(venv) root@9dd720c550b9:/# python -m pip --quiet install 'tensorflow-io'
(venv) root@9dd720c550b9:/# python -c 'import tensorflow_io'
(venv) root@9dd720c550b9:/#
```

**Comment by trueToastedCode** [comment]
> docker

It was able to get this working inside a Docker Linux arm64 container as well! .... but it won't work on MacOS arm64...

**Comment by elfringham** [comment]
@trueToastedCode I believe that the M1 support is still a WIP. But that is a completely separate issue to this one.
