### ISSUE TITLE
pip install tensorflow-io MacOs M1

### ISSUE THREAD

**Issue by AnasAr96** [tensorflow/io#1757]
I have a problem with the installation. 

i always get this error message on my Mac M1 processor, macOs Ventura 13.1 

> pip install tensorflow-io
> ERROR: Could not find a version that satisfies the requirement tensorflow-io (from versions: none)
> ERROR: No matching distribution found for tensorflow-io

**Comment by AnasAr96** [comment]
solved with:

> $ git clone https://github.com/tensorflow/io.git
> $ cd io
> $ python3 setup.py -q bdist_wheel
> 
Project: tensorflow-io Exclude: ['tests', 'tests.*', 'tensorflow_io_gcs_filesystem', 'tensorflow_io_gcs_filesystem.*'] Install Requires: ['tensorflow-io-gcs-filesystem==0.24.0'] Project Rootpath: tensorflow_io /Users/olivierskonieczny/miniforge3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools. warnings.warn(
(There I get a warning but importing at the end work (also with some weird warnings :) ))

In Directory dist u schuld have the "tensorflow_io-0.24.0-cp39-cp39-macosx_11_0_arm64.whl" file just install it with this command 
$ python3 -m pip install --no-deps PATH_TO_IO_DIR/dist/tensorflow_io-0.24.0-cp39-cp39-macosx_11_0_arm64.whl

And last I check if every thing works by:
$ python3
>>> import tensorflow_io as tfio
(its part that throw some error )
>>> print(tfio.__version__)
0.24.0

**Comment by AnasAr96** [comment]
what will show you libtensorflow_io? And which file are you missing?

**Comment by wendaovswendao** [comment]
@AnasAr96 yes, the waring message is : python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so' (no such file),

**Comment by AnasAr96** [comment]
yes I did. 
i don't know why the clone command doesn't install the /dist directory, which includes the .whl file, anymore. Maby they updated the Link.

**Comment by AnasAr96** [comment]
Yes I have. 
just clone this:
```
$ git clone https://github.com/tensorflow/io.git
$ cd io
$ python3 setup.py -q bdist_wheel
```

and you will have a directory named list in the cloned directory. 
n Directory dist u schuld have the "tensorflow_io-0.24.0-cp39-cp39-macosx_11_0_arm64.whl" file just install it with this command

`$ python3 -m pip install --no-deps PATH_TO_IO_DIR/dist/tensorflow_io-0.24.0-cp39-cp39-macosx_11_0_arm64.whl`

And last I check if every thing works by:

```
$ python3
import tensorflow_io as tfio
(its part that throw some error )
print(tfio.version)
0.24.0

```
