### ISSUE TITLE
Add batch support for dataset at the creation

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#191]
The current workflow for Dataset is to read one record at a time, then use a batch() call to aggregate the result. Since Dataset is processed sequentially, it really makes sense to add batch support when reading records. In other words, data will be copied in large memory chunks (batch) with multiple records at each process. Believe this will help improve the overall performance. The batch parameter could be passed as the output_shapes so it should be fairly easy. The only item remaining is that, in case of multiple files, batch will need to be pieced together in between two files (if the record count is not divided by the batch).

**Comment by yongtang** [comment]
With PR #202 the batch support has been added for Text, MNIST, and CIFAR. Will update other ops as well.

**Comment by BryanCutler** [comment]
I'm working on this for the Arrow Dataset ops, should have a PR ready soon.

**Comment by yongtang** [comment]
Instead of add batch to creation directly, now we count on follow up op of `batch(n)` and `unbatch()` in tf.data.Dataset. Think this issue could be resolved.
