### ISSUE TITLE
Add compatibility matrix of tensorflow v.s. tensorflow_io versions

### ISSUE THREAD

**Issue by terrytangyuan** [tensorflow/io#223]
I am often asked this question "what version of TensorFlow works with what version of TensorFlow IO?". We should provide a table in README.md showing the compatibility between different versions of tensorflow and tensorflow_io.

**Comment by BryanCutler** [comment]
Yes, I agree this would be very helpful

**Comment by yongtang** [comment]
| tensorflow-io | Tensorflow |
|---|---|
| v0.1.0 | 1.12 |
| v0.2.0 | 1.12 |
| v0.3.0 | 1.12 |
| v0.4.0 | 1.13 |
| v0.5.0 | 1.13 |


Also, `v0.6.0` will likely be 1.13, given 1.14 has not been released yet and we are likely to release another version soon.

**Comment by terrytangyuan** [comment]
That sounds good as long as users have something to follow when upgrading/downgrading. Probably need to add `>` and `<` wherever needed in the above table as well.

**Comment by yongtang** [comment]
@terrytangyuan Yes we have `tensorflow>=1.13.0,<1.14.0` for v0.4.0 and v.0.5.0 now. For v0.3.0 and earlier we used `tensorflow == 1.12.0` which was too restrictive.

**Comment by BryanCutler** [comment]
I can go ahead and update the readme. I think having the release date would be helpful too.

**Comment by terrytangyuan** [comment]
Sure. Go ahead then.

**Comment by yongtang** [comment]
For release date, it is available in:
https://github.com/tensorflow/io/tags

| version | Date|
|---|---|
| v0.1.0 | Dec 16, 2018 |
| v0.2.0 | Jan 29 |
| v0.3.0 | Feb 15 |
| v0.4.0 |  Mar 1 |
| v0.5.0 | April 12 |
