### ISSUE TITLE
Update README.md quick start example

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#224]
With the recent update, MNISTDataset automatically detect the file format and uncompress gz as needed. So there is no need to pass `compression_type="GZIP"` anymore.

The README.md should be updated to reflect the changes.

As a side note, tensorflow-io should always favor non user input if there is a way. We don't want to minimize unneeded args.

**Comment by XiongKezhi** [comment]
It seems easy and I'm just trying to make contributions these days, I think this issue can help me familiar with the contribution workflow(https://www.tensorflow.org/community/contribute/code).
Here are the steps I'm trying to follow:
1. Remove arg 'compression_type='GZIP'' in the example code, and run it to see whether I make it right.
2. Adding some note behind to explain this change.

Any problems?

**Comment by yongtang** [comment]
@XiongKezhi That is right, looking forward to your contribution!

**Comment by BryanCutler** [comment]
> And I also found it in https://www.tensorflow.org/api_docs/python/tf/nn/dropout, it seems like a problem of tensorflow version 1.13 instead of tensorflow_io, should we just skip it or what?

Yes, that warning can be ignored
