### ISSUE TITLE
Create docs/tutorial/ consistent with other TF projects

### ISSUE THREAD

**Issue by missaugustina** [tensorflow/io#227]
Per mailing list conversation (https://groups.google.com/a/tensorflow.org/forum/#!topic/io/ctHeERQj5nw) we should create a docs/tutorials directory to house Colab Jupyter notebooks. 

Please assign this issue to me, I'm working on a tutorial for the change referenced in the mailing list link above - https://github.com/tensorflow/io/pull/30

**Comment by yongtang** [comment]
@missaugustina Assigned to you, thanks!

**Comment by missaugustina** [comment]
- [ ] look at other projects for examples of this directory structure

Other projects store these in docs starting from the parent level directory of the repository. The use of the "tutorials" directory is less consistent for projects following this structure.

tensorflow/tensorboard - https://github.com/tensorflow/tensorboard/tree/master/docs

* .yamllint
* _book.yaml
* _index.yaml
* _project.yaml 

tensorflow/tfx - https://github.com/tensorflow/tfx/tree/master/docs/tutorials

* _index.yaml
* _toc.yaml

tensorflow/tensor2tensor - https://github.com/tensorflow/tensor2tensor/tree/master/docs/tutorials

* asr_with_transformer.md	"Add a placeholder to link to the official ASR tutorial"

tensorflow/datasets - https://github.com/tensorflow/datasets/tree/master/docs

* a mix of markdown & yaml files

**Comment by missaugustina** [comment]
- [ ] determine best initial stub document

Because other projects consistently use markdown, I'm going to initialize this new directory structure with a README.md file with instructions for creating & submitting a tutorial.

**Comment by missaugustina** [comment]
Create Readme document with the following sections:

- [ ] What content makes sense
- [ ] How to submit
- [ ] Formats (maybe just cover Jupyter to start)

**Comment by lamberta** [comment]
Looks like there's work on the landing page here: https://github.com/tensorflow/io/pull/498
and would be great to get some notebooks that we can pull into tensorflow.org (similiar to the tf-addons [notebook tutorials](https://github.com/tensorflow/addons/tree/master/docs/tutorials)).

Would like to link off to this from the main tutorials section, so these [load_data notebooks](https://github.com/tensorflow/docs/tree/master/site/en/tutorials/load_data) might provide a useful starting point.

cc: @markdaoust

**Comment by MarkDaoust** [comment]
There's one notebook in the works here: https://github.com/tensorflow/io/pull/591, I've given some feedback on how they can integrate with the tensorflow.org setup.

**Comment by kvignesh1420** [comment]
@yongtang can this be closed?

**Comment by yongtang** [comment]
@kvignesh1420 Thanks yes this can be closed now.
