### ISSUE TITLE
How does kafka dataset batchsize means?

### ISSUE THREAD

**Issue by poryfly** [tensorflow/io#234]
Is training data used for trained one by one like streamings? Why do we need batch_size? Does it means must wait for batch_size samples for training，if it does not have batch_size samples，the progress is hanged？

**Comment by yongtang** [comment]
@poryfly Not sure which batch_size you are referring to. Can you provide you code snippet that reproduce the issue?

**Comment by poryfly** [comment]
@yongtang in the io/tests/test_kafka.py，`repeat_dataset = kafka_io.KafkaDataset(
        topics, group="test", eof=True).repeat(num_epochs)
    batch_dataset = repeat_dataset.batch(batch_size)`
you read data from kafka,then you set batch_size for this dataset.when the graph is runing,how does the data flow

**Comment by yongtang** [comment]
@poryfly The batch_size is part of tf.data.Dataset.batch. I believe it will wait unless EOF is encountered.
