### ISSUE TITLE
Support for streaming data into a running process. 

### ISSUE THREAD

**Issue by pjm4github** [tensorflow/io#251]
I would like to use tensorflow-io to listen (subscribe) to a Kakfa data feed of weather inputs in order to predict solar panel outputs.  

I have created and tested a set tensorflow keras forecast models, that predict output based on this weather feed.   

I get about 500 weather data sets per hour. Each data set include a current weather condition and forecasts for the next week in 1 hour steps, so I have 168 rows in a table. Here is one line of that file. This is typical of what I have coming in:

ID | DATE | RELH| GUST_KM_PER_HR | PRECTYPE | PRECIPITATION  | VISIBILITY_M  | PRESSURE  | SOLAR
-- | -- |-- | -- |-- | -- | -- | -- | -- 
910 | 2019-05-06T08:00 | 96  | 9.5 |  0 | 0 | 1013 | 993.6  | 355.8 

The weather data is pushed onto the Kafka bus; a subscriber pulls the data off (features_in) and sends it to a python process that is running the 50 prediction model like this:
F0 = model0.predict(features_in)
F1 =model1.predict(features_in)
…
F49 =model49.predict(features_in)

The predictions need to run continuously so that whenever the weather data appears on the Kafka bus it is pulled off and used for predicting the power. 

How would I setup a loop for continuous prediction? I assume its a callback in a loop for this type of prediction. I assume that I want to run a callback after every line in the incoming file. 

Any help would be useful. 

Thanks in advance!
Pat

**Comment by yongtang** [comment]
@pjm4github Here is a code snippet I shared in Gitter for Kafka and Keras training with KafkaDataset in tensorflow-io:
```python
import numpy as np
import tensorflow as tf
import kafka

# 1. MNIST Kafka Producer, run separately
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
print("train: ", (x_train.shape, y_train.shape))

producer = kafka.KafkaProducer(bootstrap_servers=['localhost:9092'])
count = 0
for (x, y) in zip(x_train, y_train):
  producer.send('xx', x.tobytes())
  producer.send('yy', y.tobytes())
  count += 1
print("count(x, y): ", count)
producer.flush()

import numpy as np
import tensorflow as tf
import tensorflow_io.kafka as kafka_io

# 2. KafkaDataset with map function
def func_x(x):
  # Decode image to (28, 28)
  x = tf.io.decode_raw(x, out_type=tf.uint8)
  x = tf.reshape(x, [28, 28])
  # Convert to float32 for tf.keras
  x = tf.image.convert_image_dtype(x, tf.float32)
  return x
def func_y(y):
  # Decode image to (,)
  y = tf.io.decode_raw(y, out_type=tf.uint8)
  y = tf.reshape(y, [])
  return y
train_images = kafka_io.KafkaDataset(['xx:0'], group='xx', eof=True).map(func_x)
train_labels = kafka_io.KafkaDataset(['yy:0'], group='yy', eof=True).map(func_y)
train_kafka = tf.data.Dataset.zip((train_images, train_labels)).batch(1)
print(train_kafka)

# 3. Keras model
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(train_kafka, epochs=5, steps_per_epoch=12000)
```

**Comment by yongtang** [comment]
For your `model.predict` case it should be easier than training I think.

> The weather data is pushed onto the Kafka bus; a subscriber pulls the data off (features_in) and sends it to a python process that is running the 50 prediction model

In tensorflow-io, the KafkaDataset is served as consumer/subscriber. It needs to know the format of the message you send to Kafka (on producer side).

Since Kafka is message based, 
> The weather data is pushed onto the Kafka bus

I am wondering if you have the format of the weather data that is serialized into the string and sent to kafka?

**Comment by yongtang** [comment]
@pjm4github Here is another example shared in Gitter channel https://gitter.im/tensorflow/sig-io

The original question was to convert an existing [Fraud Detection](https://www.datascience.com/blog/fraud-detection-with-tensorflow) to use KafkaDataset directly.

Related background could be found in Gitter channel room https://gitter.im/tensorflow/sig-io

The following are code snippet:
```python
# Part 1: Produce data into Kafka (optional)
# $ pip3 install kafka-python
import kafka

producer = kafka.KafkaProducer(bootstrap_servers=['localhost:9092'])

# NOTE: Data from https://www.kaggle.com/mlg-ulb/creditcardfraud/data
with open('creditcard.csv', 'r') as f:
  next(f) # skip header line
  count = 0
  for line in f:
    producer.send('creditcard', line.rstrip().encode())
    count += 1
  print(count, "records has been produced in 'creditcard'")
producer.flush()
```


```python
# Part 2: KafkaDataset
# $ pip3 install tensorflow==2.0.0b1
# $ pip3 install tensorflow-io-2.0-preview
import tensorflow as tf
import tensorflow_io.kafka as kafka_io

# NOTE: From original model
nb_epoch = 5
batch_size = 32

# Autoencoder: 30 => 14 => 7 => 7 => 14 => 30 dimensions
input_dim = 30 # train_x.shape[1] #num of columns, 30
encoding_dim = 14
hidden_dim = int(encoding_dim / 2) #i.e. 7
learning_rate = 1e-7

# Dense = fully connected layer
input_layer = tf.keras.layers.Input(shape=(input_dim, ))
# First parameter is output units (14 then 7 then 7 then 30) :
encoder = tf.keras.layers.Dense(encoding_dim, activation="tanh", activity_regularizer=tf.keras.regularizers.l1(learning_rate))(input_layer)
encoder = tf.keras.layers.Dense(hidden_dim, activation="relu")(encoder)
decoder = tf.keras.layers.Dense(hidden_dim, activation='tanh')(encoder)
decoder = tf.keras.layers.Dense(input_dim, activation='relu')(decoder)
autoencoder = tf.keras.models.Model(inputs=input_layer, outputs=decoder)


autoencoder.compile(metrics=['accuracy'],
                    loss='mean_squared_error',
                    optimizer='adam')

# NOTE: KafkaDataset processing
def process_csv(entry):
  # "Time","V1","V2","V3","V4","V5","V6","V7","V8","V9","V10","V11","V12","V13","V14","V15","V16","V17","V18","V19","V20","V21","V22","V23","V24","V25","V26","V27","V28","Amount","Class"
  return tf.io.decode_csv(entry, [[0.0], *[[0.0] for i in range(28)], [0.0], [""]])

creditcard_dataset = kafka_io.KafkaDataset(['creditcard:0'], group='creditcard', eof=True).batch(batch_size).map(process_csv)

def process_x_y(*entry):
  return (tf.stack(entry[0:30], 1), tf.strings.to_number(entry[30], out_type=tf.int32))

train_dataset = creditcard_dataset.map(process_x_y)
print(train_dataset)

# NOTE: model.fit()
# NOTE: "Time" and "Amount" are not transformed with the following yet
# df_norm['Time'] = StandardScaler().fit_transform(df_norm['Time'].values.reshape(-1, 1))
# df_norm['Amount'] = StandardScaler().fit_transform(df_norm['Amount'].values.reshape(-1, 1))
# Runtime transformation of the above, mayrequires all data available which may defeat the purpose of "streaming" data
autoencoder.fit(train_dataset, epochs=nb_epoch)
```

**Comment by kvignesh1420** [comment]
@pjm4github you can try exploring the `KafkaGroupIODataset` and it's `stream_timeout` functionality for continuous predictions on new data points. 
Reference: https://www.tensorflow.org/io/api_docs/python/tfio/experimental/streaming/KafkaGroupIODataset
Tutorial: https://www.tensorflow.org/io/tutorials/kafka#evaluate_the_performance_on_the_test_data

**Comment by kvignesh1420** [comment]
Closing as of now. Please reopen if required.
