### ISSUE TITLE
Support for DICOM images

### ISSUE THREAD

**Issue by SSaishruthi** [tensorflow/io#257]
DICOM is one of the most common formats generated by vendors of imaging modalities (CT/MRI Scan images). `dicom` python package can be used to read the DICOM images. 

- If there is a need it can be converted to other image formats.
- Convert to tensor

Providing support for DICOM can be a benefit to medical researchers.

Sample dataset:
https://wiki.cancerimagingarchive.net/display/NLST/National+Lung+Screening+Trial

If this is of our interest, I can contribute to this.

Thanks in advance.

**Comment by yongtang** [comment]
@SSaishruthi This could be a useful addition I think. Though in order to import dicom into the graph of TF I think it may need C++, or a library that could be built as part of the .so/.dll (unless we go with from_tensor_slices which could be a huge cost.). Can take a look first.

**Comment by SSaishruthi** [comment]
Thanks @yongtang 
I will work on this and update soon

**Comment by yongtang** [comment]
GDCM seems to be a decent choice:
http://gdcm.sourceforge.net/wiki/index.php/Main_Page

**Comment by SSaishruthi** [comment]
Thanks, @yongtang for the suggestion. 
What do you think about using `pydicom` for reading dicom files?

**Comment by yongtang** [comment]
@SSaishruthi pydicom has some limitations but it could be good to start with.

Basically you can read dicom files through pydicom and then pass it to `tf.data.Dataset.from_tensor_slices`. You can create a PR and let me know if you encounter any issues.

**Comment by SSaishruthi** [comment]
Perfect. I will keep you updated. 
Thanks @yongtang

**Comment by ntenenz** [comment]
@yongtang @SSaishruthi, I'd caution that you proceed with caution before diving head-first into a DICOM implementation as there's quite a bit of nuance to the format. Happy to discuss further and/or assist as this is something that's been top of mind for quite a while.

**Comment by SSaishruthi** [comment]
Hi @ntenenz 

Thanks a lot for the response. I just collected some sample images to get started with the code. 
Would definitely like to discuss pointers/plans that you have in mind. This way I can streamline my plans and avoid future conflicts.

**Comment by ntenenz** [comment]
Happy to discuss further (perhaps on gitter?) and/or collaborate.

Given the complexity of the task, it may be prudent to only support a subset of the DICOM standard initially but design the API such that it supports a greater subset. I'd argue this should probably be the first step. Much of the aforementioned difficulties stem from the fact that a single DICOM file can represent:
- a single, planar image (of which 1+ files may represent a series, i.e. a single sample for training)
- an anisotropically sampled 3D volume
- a collection of related but arbitrarily oriented/sampled 2D images
- a segmentation mask
- a container for storing near-arbitrary documents
- ...

**Comment by SSaishruthi** [comment]
Can you please provide me either your id or email so that I can create a channel for discussion?

**Comment by yongtang** [comment]
We have a Gitter channel [tensorflow/sig-io](https://gitter.im/tensorflow/sig-io) as well.

**Comment by ntenenz** [comment]
@SSaishruthi, the gitter channel that @yongtang posted was the one I was referencing. I use my github handle there.

**Comment by SSaishruthi** [comment]
Apologize for not being active. I will start providing updates on this soon.

**Comment by yongtang** [comment]
@SSaishruthi See discussion in:
https://gitter.im/tensorflow/sig-io?at=5d2d06b2570ac36f8d2f29f3

also:

https://github.com/gradienthealth/gradient_decode_dicom

**Comment by SSaishruthi** [comment]
@yongtang I was using pydicom to read dicom files. Looks like `gradient_decode_dicom` will replace that. Is my understanding correct?
I started with uncompressed dicom image type.

**Comment by Ouwen** [comment]
@SSaishruthi 
Give this a try: https://colab.research.google.com/drive/1MdjXN3XkYs_mSyVtdRK7zaCbzkjGub_B
You can upload your dicom file of interest and sees if it reads properly.

**Comment by SSaishruthi** [comment]
@Ouwen Thanks for the links
I will try with this with my current work and keep you posted.

**Comment by yongtang** [comment]
As PR #359 and several follow up PRs have been added, I think this issue could be closed. Thanks @marcelolerendegui @Ouwen for the great contribution!

Feel free to open new issues if there are additional enhancement requests.
