### ISSUE TITLE
Automatic publishing releases to PyPI using Travis

### ISSUE THREAD

**Issue by terrytangyuan** [tensorflow/io#261]
Publishing new releases to PyPI for different versions of Python and different operating systems often require a relatively clean environment.

Instead of doing this manually, we could setup automatic releases on Travis whenever there are new Github tags/releases created. See [here](https://docs-staging.travis-ci.com/user/deployment/releases/#running-commands-before-or-after-release) for some instructions.

**Comment by yongtang** [comment]
The process is now pretty much automated, see:
https://github.com/tensorflow/community/pull/123
