### ISSUE TITLE
[GSoC] JSON Reader for tensorflow-io

### ISSUE THREAD

**Issue by jiachengxu** [tensorflow/io#262]
Hi folks,
I am Jiacheng Xu, and I am working on this feature during this summer as my Google Summer of Code project, here is a description from my mentor @yongtang: 

With tensorflow and tensorflow-io, a lot of file formats have been well covered. One format which is used everywhere but has not been supported yet, is the json format file. In tensorflow, it is certainly possible to read json files with tf.py_func and pass it through graph or tf.data. There are some limitations with this approach as was mentioned in the tensorflow docs.

We could actually build the json format parser support in, and selectively pass the values to tf.data.

A C++ library of json parser might be needed. The jsoncpp could be a choice, other options are fine as long as the library is in good quality. 

Refs:
- [Project website](https://summerofcode.withgoogle.com/projects/?sp-search=jiacheng#5823672818860032)
- [Proposal of the project](https://docs.google.com/document/d/1yCB41MLIDS0OUgKhv9xP8XXHHctFGTkppaQKsHm0r9g/edit?usp=sharing)
- [Benchmark about different json libraries](https://github.com/mloskot/json_benchmark)

**Comment by jiachengxu** [comment]
Hi @yongtang, can you try to assign this issue to me?

**Comment by BryanCutler** [comment]
Hi @jiachengxu , welcome!  This will be a nice addition, I'm looking forward to the PR. Thanks!

**Comment by jiachengxu** [comment]
Hi @BryanCutler, thanks for your warm welcome, I am also looking forward to contributing to the project!

**Comment by yongtang** [comment]
@jiachengxu The C++ code base in tensorflow-io has a pretty deep learning curve.

To get started quickly, I would suggest you to:
1. Start with a test for JSON format in python. You can look into tests/test_text.py (or other test for examples).
   In tensorflow-io we typically have two types of tests. The first is the integration with tf.keras so that dataset could be passed for training and inference directly. The second is the iteration of tf.data.Dataset itself.
2. Implement in python a JSON parser (no need for jsoncpp for now), and pass it through `tf.data.Dataset.from_tensor_slices`. This will help you pass the test implemented in 1). `from_tensor_slices` has limitations but that could be an easy step to make progress.
3. Finally we could work on get jsoncpp integrated. The tests in 1) could be reused.

Let us know if you run into any issues.

**Comment by jiachengxu** [comment]
Hi @yongtang, thanks for your information, and I will take a look at the `test` part and try to add some tests first.
I have started to play with [rapidjson](https://github.com/Tencent/rapidjson), and it seems this one is better than jsoncpp in terms of the performance([experiments](https://blog.thousandeyes.com/efficiency-comparison-c-json-libraries/)). Maybe we could use rapidjson.

**Comment by yongtang** [comment]
@jiachengxu The issue is tensorflow already linked with jsoncpp which means we might have two libraries if rapidjson is used. I think we could start with jsoncpp.

Also, I would strongly suggest to go with python and test first to make progress. We can always worry about JSON C++ later.

**Comment by yongtang** [comment]
@jiachengxu Any update or need any help?

**Comment by jiachengxu** [comment]
Hi @yongtang,
Thanks for asking me. 
As we discussed before, I wrote some tests for JSON format in Python, and also I just used [json](https://docs.python.org/2/library/json.html) library in Python to implement a simple json parser to make the tests pass.

Now, I am playing around the jsoncpp and try to start with a simple json parser in CPP, I will let you know when I have some progress and if I need help.

Thanks,
Jiacheng

**Comment by yongtang** [comment]
@jiachengxu Please create a working-in-progress PR. This will allow others and community to help and see progress.

**Comment by jiachengxu** [comment]
As the GSoC is reaching to the end, I want to summarize my contributions in the following:
- JSONDataset is implemented for supporting reading JSON format files.
- 2 custom ops(`list_json_columns` and `read_json`) are implemented to support reading JSON format files in eager mode.
- Tests for both normal mode and eager mode are added.
- A user guide is added. 
- [WIP] A blog about the JSONDataset and TensorFlow IO.
After the blog is done, I will put the link here.

Overall, it was a fantastic experience for me to work with TensorFlow IO during this summer :), and really appreciate all the help you have provided @yongtang @terrytangyuan @BryanCutler ! I will
keep contributing to the projects in the future and it was really a pleasure to work with you :)

**Comment by jiachengxu** [comment]
Here is the blog draft: https://docs.google.com/document/d/1ph47xg9PXyp2yFR2-rui45SdG9Inn28QM8M0rnXd77c/edit?usp=sharing
It would be really great that you can take a look and give me some feedback, I am going to submit it to [ Google Open Source blog](https://opensource.googleblog.com/), and it is accepted, then it will be published there.

**Comment by terrytangyuan** [comment]
@jiachengxu The draft looks great! I've left some small comments. What's the status on that so far? In the meantime, we've made many improvements over the past few months so it would be good to make sure the code snippets in the blog post still work as expected.

**Comment by jiachengxu** [comment]
@terrytangyuan Thanks for your comments for the draft, Unfortunately, the PR is not accepted by Google Open Source blog, but I still want to keep it accessible so it can give people an overview of how to use tf-io :)

**Comment by terrytangyuan** [comment]
@jiachengxu I see. Thanks for the good work!
