### ISSUE TITLE
Upgrade Apache Arrow to version 0.14.1

### ISSUE THREAD

**Issue by BryanCutler** [tensorflow/io#273]
TensorFlow I/O is currently using Apache Arrow 0.11.1 and we should plan on upgrading soon. Arrow 0.14.0 will be released soon and it would be a good idea to update to get bug fixes / improvements.

**Comment by BryanCutler** [comment]
I am thinking a good time to do this will be for tf-io v0.8.0, so after TensorFlow 1.14.0 and tf-io makes a release 0.7.0 against it.

**Comment by BryanCutler** [comment]
Update since 0.14.1 was just released

**Comment by emkornfield** [comment]
Was Arrow ever updated.  If not this is a blocker for https://github.com/tensorflow/io/issues/890.  The V1 endpoint relies on arrow post 0.15.0

**Comment by BryanCutler** [comment]
@emkornfield the Arrow version is 0.16.0, it's a little hard to find, but
in the build file here
https://github.com/tensorflow/io/blob/master/third_party/arrow.BUILD#L34.
I'm planning on upgrading to 1.0.0 also at some point now that's it's been
released.

**Comment by emkornfield** [comment]
Thanks.  Should this issue be closed then?

**Comment by BryanCutler** [comment]
Yeah, didn't notice it was still open
