### ISSUE TITLE
Use `import tensorflow as tf` in tensorflow-io

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#274]
In tensorflow-io for legacy reasons we used different ways of importing tensorflow. Some are through non-public api (to make TF 2.0 and 1.x work at the same time). Some used `import tensorflow`, some uses `import tensorflow as tf`.

It is desirable to use `import tensorflow as tf` if application. The reason is that this is the supported tf2_upgrade format. See https://github.com/tensorflow/tensorflow/issues/29380#issuecomment-499289446

This issue is to track the progress in changing `import tensorflow` to `import tensorflow as tf`.

Contributions welcome!

**Comment by jiachengxu** [comment]
Hi @yongtang, can I work on this?

**Comment by yongtang** [comment]
@jiachengxu Sure, go ahead 👍
