### ISSUE TITLE
Support BigQuery for tensorflow-io

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#29]
BigQuery is Google's serverless cloud data analytics platform. During last SIG I/O call the support for BigQuery (`BigQueryDataset`) was mentioned.

It would be good to add BigQuery (`BigQueryDataset`) to tensorflow-io so that users could use tensorflow to do more big data analytics on cloud.

Note that Google's BigQuery seems to have no C++ client library. It does have a python support and a RESTful API support. The implementation likely will need to use BigQuery's python client library, or http?

**Comment by yongtang** [comment]
One challenge is that BigQuery essentially returns a json response so a json library with good performance in C/C++ is needed.

**Comment by suphoff** [comment]
@yongtang: I used jsoncpp last year (https://github.com/open-source-parsers/jsoncpp) for a RESTful API. It was nowhere near a performance critical path so I can't speak for the performance - however I can say it was trivially to use it for encoding & decoding and it was super easy to build it as an external dependency with cmake.

**Comment by suphoff** [comment]
@yongtang: Just checked and it is also used in TF - so all bazel build infrastructure should be there

**Comment by yongtang** [comment]
@suphoff Thanks! Will take a look at jsoncpp.

**Comment by vlasenkoalexey** [comment]
I've recently joined Google CloudAI team and going to work on this.
Btw, BigQuery has recently released https://cloud.google.com/bigquery/docs/reference/storage/rpc/google.cloud.bigquery.storage.v1beta1#google.cloud.bigquery.storage.v1beta1.ReadRowsRequest API that is using gRPC and specifically designed for high performance scenarios like this one.

**Comment by yongtang** [comment]
Thanks @vlasenkoalexey 👍 ! Let me know if you have any questions or anything I could be of help.
