### ISSUE TITLE
When reading hdf5 files compressed with gzip, error occured

### ISSUE THREAD

**Issue by CaptainDuke** [tensorflow/io#308]
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: external/hdf5/src/H5Dio.c line 199 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: external/hdf5/src/H5Dio.c line 601 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: external/hdf5/src/H5Dchunk.c line 2259 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: external/hdf5/src/H5Dchunk.c line 3624 in H5D__chunk_lock(): data pipeline read failed
    major: Dataset
    minor: Filter operation failed
  #004: external/hdf5/src/H5Z.c line 1301 in H5Z_pipeline(): required filter 'deflate' is not registered
    major: Data filters
    minor: Read failed

**Comment by CaptainDuke** [comment]
However, I can use command line h5dump to read such compressed h5files successfully.

**Comment by CaptainDuke** [comment]
I think it's because hdf5.BUILD and WORKSPACE files doesn't compile hdf5 together with 'deflate' filter, but only orign hdf5-1.10.5.tar.gz. 

The commmand line should be like this:
./configure --enable-cxx --enable-fortran --with-zlib=/path/to/zlib/include,/path/to/zlib/lib 

But I don't know how to add this 
![screen_shot](https://user-images.githubusercontent.com/24515303/59744105-6d722600-92a4-11e9-8dea-b5e1fa950121.png)

**Comment by yongtang** [comment]
@CaptainDuke Do you have a sample file I can test? I think it could an easy fix but I may need a sample file to test it.

**Comment by CaptainDuke** [comment]
> @CaptainDuke Do you have a sample file I can test? I think it could an easy fix but I may need a sample file to test it.

Here's a test file, I just compress the /io/tests/test_hdf5/tdset.h5 with gzip
`with h5py.File('compressed_h5.h5', 'w') as output_f:
    output_f.create_dataset('/dset1', data=h5f['/dset1'][()], compression='gzip')`

[compressed_h5.zip](https://github.com/tensorflow/io/files/3308451/compressed_h5.zip)

**Comment by CaptainDuke** [comment]
Thanks for your contribution, I will compile new version of this code by myself.

By the way, what's the meaning of output_shape? I found that no matter how I set this value, the output results remain unchanged. Only 'batch' matters.

**Comment by yongtang** [comment]
@CaptainDuke PR #311 has been merged, you give tensorflow-io-nightly a try. Also  new version (v0.7.0) of tensorflow-io will be rebased soon.

For `output_shape`, it used in DatasetV1, in DatasetV2 there are some changes that makes it less strict. If you can share the code you are trying to run (maybe open another issue?) then we may take a look.
