### ISSUE TITLE
Unable to install directly using pip

### ISSUE THREAD

**Issue by natemurthy** [tensorflow/io#33]
@yongtang I seem unable to download artifact from PyPI using `pip`:

```
$ pip install tensorflow-io
Collecting tensorflow-io
  Could not find a version that satisfies the requirement tensorflow-io (from versions: )
No matching distribution found for tensorflow-io
```

Is there a step I'm missing that we could add to the README?

Referencing: https://github.com/tensorflow/io/issues/7

**Comment by yongtang** [comment]
@natemurthy which OS are you using (Ubuntu 14.04/16.04?), and can you check the python versions?

**Comment by natemurthy** [comment]
I'm using macOS 10.12.5 with Python 3.6.4

**Comment by yongtang** [comment]
@natemurthy We are not able to support tensorflow-io on Mac yet. We have plans to support it really soon though:
https://github.com/tensorflow/io/issues/4

**Comment by natemurthy** [comment]
Awesome, thanks! Closing this out and will follow online.
