### ISSUE TITLE
macOS python3 packages not published to pypi

### ISSUE THREAD

**Issue by damienpontifex** [tensorflow/io#352]
Just went to install latest tensorflow-io release and found that no version satisfies the requirement. Doing a `-vvv` I noticed macOS only has cp27 wheels published. See interesting part (just the 0.7.0 versions) of the `python -m pip install -U tensorflow-io -vvv` below:

```
Skipping link https://files.pythonhosted.org/packages/dd/63/338863803549731df8a39a9a80fe52b098f21753e1cb7443a1063f1a3353/tensorflow_io-0.7.0-cp27-cp27m-macosx_10_12_intel.whl#sha256=43080ca915e5c9ad2be70da1039dc9cd800d6f66ca66e8b6f9d58529692dc6d8 (from https://pypi.org/simple/tensorflow-io/); it is not compatible with this Python
Skipping link https://files.pythonhosted.org/packages/ae/b6/a0b932a1b24bb4d115cd597a9a5dae55b86550c81e6d812c9263acfbaf45/tensorflow_io-0.7.0-cp27-cp27mu-manylinux1_x86_64.whl#sha256=a70961861e4e694ad6fd60ebb689ea83c393ae50438405bbd3e4d6d9e3cb7f80 (from https://pypi.org/simple/tensorflow-io/); it is not compatible with this Python
Skipping link https://files.pythonhosted.org/packages/96/4f/ea60661304f351aee902e7f9f94768b16e37293af5fa10ed615ff06e1861/tensorflow_io-0.7.0-cp34-cp34m-manylinux1_x86_64.whl#sha256=ac62873cad9d9bd1de63f4257f266e0962d5cd9b8f1e544ed86ec81313df73a6 (from https://pypi.org/simple/tensorflow-io/); it is not compatible with this Python
Skipping link https://files.pythonhosted.org/packages/3e/16/be1b71bb7eee281fae39e8224f83d5172eba22e119a54f967f6050a768c2/tensorflow_io-0.7.0-cp35-cp35m-manylinux1_x86_64.whl#sha256=207ea209db190d9a6108a0f944eaa63ddc2fb380c79a846074deb3d1bbb7b76f (from https://pypi.org/simple/tensorflow-io/); it is not compatible with this Python
Skipping link https://files.pythonhosted.org/packages/f0/16/0ed48f2fd32c2a5d5697979c5a184b4feae874896869de208b9784cf5c6b/tensorflow_io-0.7.0-cp36-cp36m-manylinux1_x86_64.whl#sha256=a5410c872077f1ee9a9979f9916cb1db1b403ea482edce216f286813c0c3999c (from https://pypi.org/simple/tensorflow-io/); it is not compatible with this Python
Skipping link https://files.pythonhosted.org/packages/0a/5a/ba266c9d26d028354e1926eeb8bc941e3bfd4ea13262e7f39b55b524362b/tensorflow_io-0.7.0-cp37-cp37m-manylinux1_x86_64.whl#sha256=7f2d3eca1c904af0343969f35f613bbef55aa50146e9e05cce767972d066a899 (from https://pypi.org/simple/tensorflow-io/); it is not compatible with this Python
```

I thought we were building the 3.{4567} versions as well? Is it just that they aren't automated for release to pypi? And if not, how could I help getting these python3 versions published for macOS?

**Comment by yongtang** [comment]
@damienpontifex We build 2.7, 3.4-3.7 on Linux. On macOS at the moment we only build 2.7 with mac's default python (and latest pip). The binary is generated from Travis CI's machine (to be consistent) with Intel CPU and osx 10.12.

Travis CI potentially support 3.x version of python:
https://docs.travis-ci.com/user/languages/python/
though I haven't tried any one of them yet.

To build macOS with 3.x, we will need to find a configuration on Travis CI, then we could setup the release automatically (along with each commit).

**Comment by damienpontifex** [comment]
Could use `pyenv` to install and set appropriate python versions - https://docs.travis-ci.com/user/reference/osx/#python-related-tools

Maybe a macOS if check in .travis/wheel.build.sh such as 

```bash
pyenv install $entry
pyenv local $entry
```

I'll have a go at adding it and see how it goes

**Comment by damienpontifex** [comment]
@yongtang thoughts on pushing the extra outputs for macOS versions to 0.7.0?

**Comment by yongtang** [comment]
@damienpontifex if someone could build 0.7.0 for macOS locally (from the same tag version) then we could push to PyPI.org.

**Comment by yongtang** [comment]
@damienpontifex We could also have a 0.8.0 release sooner (with macOS binary built from Travis CI for consistency).

**Comment by damienpontifex** [comment]
Either is fine. I built the whl file for myself and using that for now. Happy to wait for 0.8.0 release for publishing consistency and to make sure everything goes through proper CI vs uploading builds outside of that cycle

**Comment by yongtang** [comment]
@damienpontifex We have one successful macOS build and all binaries are pushed to Dropbox. You can take a look at release 1298:

https://www.dropbox.com/sh/dg0npidir5v1xki/AACor-91kbJh1ScqAdYpxdEca?dl=0

and give macOS whl files a try to see if they works on your machine or not.
