### ISSUE TITLE
Adding gdb to the dev dockerfile for debugging purpose.

### ISSUE THREAD

**Issue by jiachengxu** [tensorflow/io#377]
gdb is really necessary for debugging both python and cpp code, so it would be really useful to have gdb installed when building the dev docker image. If it is ok to add an entry of gdb, I can take care of that by following a PR.

**Comment by yongtang** [comment]
@jiachengxu I think gdb is good to have. Could you open a PR? 

cc @BryanCutler

**Comment by BryanCutler** [comment]
Thanks @jiachengxu , that would be great to have!

Btw, it would be really good to have a guide for debugging also. It was a little tricky for me to get everything setup so I could see the tensorflow symbols and step into that code too. What do you guys think?

**Comment by yongtang** [comment]
@BryanCutler That would be great. Though if I remember, Bazel automatically strips symbols unless specified explicitly with a flag `--strip=never`? I never tried but I think this is the flag to use.

@jiachengxu would you mind to also add some content about debugging with gdb if possible?

**Comment by jiachengxu** [comment]
Hi @yongtang @BryanCutler, I will send a PR  to include gdb in the dockerfile and also add some hints of debugging with gdb in the README.md

**Comment by yongtang** [comment]
@jiachengxu On a side note to enable gdb `--cap-add=SYS_PTRACE ` will have to be added when running `docker run`.

`--security-opt seccomp=unconfined ` might also be needed, though I believe you could attach to another running process.
