### ISSUE TITLE
Port tensorflow/contrib/cloud:gcs_config_ops_test

### ISSUE THREAD

**Issue by henrytansetiawan** [tensorflow/io#395]
The tensorflow_io/cloud is missing the gcs_config_ops_test, this build target was originally defined in: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cloud/BUILD#L78, as:

```python
tf_py_test(
    name = "gcs_config_ops_test",
    size = "small",
    srcs = ["python/ops/gcs_config_ops_test.py"],
    additional_deps = [
        ":cloud_py",
        "//tensorflow/python:client_testlib",
    ],
    tags = ["manual"],
)
```

The task here is to port tf_py_test(...) into equivalent py_test(...) for tensorflow_io

**Comment by henrytansetiawan** [comment]
Some pointers from @yongtang:

By default, most likely python test could work already, if you place it in tests directory, and type TFIO_DATAPATH=bazel python -m pyrest -s -v tests/test_xxx.py.

**Comment by yongtang** [comment]
This has been covered in tests/test_gcs_config_ops.py, think it could be resolved.
