### ISSUE TITLE
Port tensorflow/contrib/cloud:bigquery_reader_ops_test

### ISSUE THREAD

**Issue by henrytansetiawan** [tensorflow/io#396]
The tensorflow_io/cloud is missing the gcs_config_ops_test, this build target was originally defined in: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cloud/BUILD#L59, as:

```python
tf_py_test(
    name = "bigquery_reader_ops_test",
    size = "small",
    srcs = ["python/ops/bigquery_reader_ops_test.py"],
    additional_deps = [
        ":cloud_py",
        "//tensorflow/core:protos_all_py",
        "//tensorflow/python:array_ops",
        "//tensorflow/python:client_testlib",
        "//tensorflow/python:data_flow_ops",
        "//tensorflow/python:dtypes",
        "//tensorflow/python:io_ops",
        "//tensorflow/python:parsing_ops",
        "//tensorflow/python:platform",
        "//tensorflow/python:util",
    ],
    tags = ["manual"],
)
```

The task here is to port tf_py_test(...) into equivalent py_test(...) for tensorflow_io

**Comment by henrytansetiawan** [comment]
Some pointers from @yongtang:

By default, most likely python test could work already, if you place it in tests directory, and type TFIO_DATAPATH=bazel python -m pyrest -s -v tests/test_xxx.py.

**Comment by vlasenkoalexey** [comment]
I added corresponding test to https://github.com/tensorflow/io/blob/master/tests/test_bigquery_eager.py
