### ISSUE TITLE
Update docker build image for both CI and dev

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#403]
From https://groups.google.com/a/tensorflow.org/forum/#!topic/developers/fSAAd4bxQ4M

> As of today (07/31) the tf-nightly(-gpu) packages will have 2.0 behavior turned on by default. They will also be manylinux2010 compliant.
> We have received a few requests to revert back to 1.x behavior for tf-nightly(-gpu) to provide users with more time to migrate to 2.0 behavior, and will be rolling back the changeover. 
> We will still be planning to retry the migration in approximately 2 weeks. We will send out a reminder closer to the official migration date as well.

The manylinux2010 for tf seems to be built on Ubuntu 16.04 with devtoolset, which looks like a big overhaul on our CI docker image.

There is a `custom build for manylinux2010` docker file:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/ci_build

However, from my past experience normally the `custom-op` docker build on tensorflow repo are not always up to date (which is understandable as there are so many files and so many versions in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/ci_build).

So likely we will have much work to do just to keep up to the manylinux2010 change (in two weeks).

/cc @terrytangyuan @BryanCutler @dmitrievanthony

**Comment by yongtang** [comment]
Update from https://groups.google.com/a/tensorflow.org/forum/#!topic/developers/tds7vLcmIrA

> TensorFlow team will stop updating 1.x tf-nightly pip packages starting 8/16/19
tf-nightly-2.0-preview will continue to be available as before.
> If you rely on TensorFlow 1.x nightly pip packages and have not migrated your code to be 2.0 compatible, you will be impacted and will need to pin to the last available version of 1.x tf-nightly to continue working.
> After 2.0.0 final is released, tf-nightly will default to TF 2.0 nightly pip packages.

**Comment by BryanCutler** [comment]
>They will also be manylinux2010 compliant.

This is great news! I can definitely help out to get our builds up to speed with this.

**Comment by yongtang** [comment]
@terrytangyuan @BryanCutler Well this is really messy. Looks like tf-nightly-2.0-preview already changed to use GCC 7.3.1:
```
libtensorflow_framework.so.2: stripped=false, compiler=GCC 7.3.1, byteorder=LittleEndian, machine=Advanced Micro Devices x86-64
```

I assume the upcoming 1.14.1 will not work with 0.7.0 (last release).

Haven't been able to figure out the OS that is being used though I assume it is Ubuntu 16.04.

**Comment by yongtang** [comment]
We already updated the docker image so this issue could be resolved.
