### ISSUE TITLE
tf-nightly failure cases

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#431]
Since there are several recent changes in tf.data, the following has been disabled temporarily:

- Ignite tests has been temporarily disabled (9c8dce4)
- Arrow tests has been temporarily disabled (b704dee)
- Arrow has to comment out the optimization_only usage (4e6718c)

We may want to fix those before 0.8.0 release is out.

**Comment by BryanCutler** [comment]
I'm looking into the Arrow test failures now

**Comment by BryanCutler** [comment]
Apologies for the delay, @yongtang . I believe I have fixed the arrow test failures now.

**Comment by BryanCutler** [comment]
Is anyone looking at the Ignite test failures? I can give it a shot if no one else is..

**Comment by yongtang** [comment]
@BryanCutler If you can take a look at ignite test failure that would be great. I think we are very close to release the new version soon.

**Comment by yongtang** [comment]
With PR #519 and #526 merged, this issue could be closed.
