### ISSUE TITLE
Feature Request: Support for Decoding Video Files from Memory

### ISSUE THREAD

**Issue by SudeepDasari** [tensorflow/io#455]
It'd be awesome to extend the current FFMPEG library to support video decoding from data already in memory (rather than from given filenames). What I'm asking for is something akin to `tf.io.decode_image` except for video streams. Below is example usage of my proposed "decode_video" op:
```
buf = ...                           # byte tensor of placeholder string
frames = tf_io.decode_video(buf)    # decodes buffer into [T, H, W, C] list of frames 
```

@yongtang I'm a noob but I'd be happy to help work on this feature, if you could give me pointers for where to start :)

**Comment by yongtang** [comment]
@SudeepDasari See related discussion in https://github.com/tensorflow/io/issues/453#issuecomment-533802219

In your original example you mentioned decoding stream in mp4 format to tensors. As we also have other places that process videos in different ways, I think it makes sense to split the container parsing from the decoding.

For example, mp4 typically consists of multiple tracks (video/audio/subtitle). It is hard to fit them into one big ops implemented in C++/FFmpeg. Instead, I think a better way would be to have basic/primitive ops of `read_video()` (from mp4) to string, and `decode_video` to decode (from string) to tensors.

We could build up higher level ops in python to combine basics ops for ease of use.

**Comment by yongtang** [comment]
/cc @SudeepDasari 

Added PR #509 to have decoding video from memory support. Keep in mind video could be big after decoding. Eventually there might be a need to only decode a small number of frames (e.g., start:stop = 100:200 ).
