### ISSUE TITLE
Guidance on custom filesystem

### ISSUE THREAD

**Issue by damienpontifex** [tensorflow/io#46]
The past guide for this was here https://www.tensorflow.org/guide/extend/filesystem and I'm looking at porting the [azure blob storage file system](https://github.com/tensorflow/tensorflow/pull/21649) to this repo. 

I was wanting some guidance on what might have changed? I found the igfs registration here https://github.com/tensorflow/io/blob/master/tensorflow_io/ignite/ops/igfs_ops.cc and what seems to be the build target here https://github.com/tensorflow/io/blob/master/tensorflow_io/ignite/BUILD#L5-L43 for this file system. Are these two components what is likely from my point of view?

**Comment by yongtang** [comment]
@damienpontifex Thanks for the interest! Yes to build a custom filesystem, the `igfs_ops.cc` and `tensorflow_io/ignite/kernels/igfs/` could be a good starting point.

The ignite module actually consists of two functionalities. One is the `IgniteDataset` which will feed data into `tf.data`. Another is the `tensorflow_io/ignite/python/ops/igfs_ops.py` which implements a filesystem.

If your focus is azure blob storage, then `tensorflow_io/ignite/python/ops/igfs_ops.py` is a very similar example.

Let me know if I can be of any help.

**Comment by damienpontifex** [comment]
Thanks @yongtang I've begun copying past work over here and got it in a branch here https://github.com/damienpontifex/io/tree/azure-blob-fs/tensorflow_io/azure

I'm trying to run `bazel build //tensorflow_io/azure:azfs.so` to at least get minimal build and then work on code. Currently I'm getting errors such as:

## External dependency issue:
```
ERROR: /private/var/tmp/_bazel_ponti/1e60068efdb36cc98840a74d3f5c528e/external/azure_storage_fuse/BUILD.bazel:6:1: no such package '@azure_storage_fuse//tensorflow': BUILD file not found on package path and referenc
ed by '@azure_storage_fuse//:azure_storage_fuse'
ERROR: Analysis of target '@azure_storage_fuse//:azure_storage_fuse' failed; build aborted: no such package '@azure_storage_fuse//tensorflow': BUILD file not found on package path
```

but no idea where the `@azure_storage_fuse//tensorflow` bazel path came from. Is this something about the setup building alongside tensorflow?

## TF lib issue:
I was also getting other errors such as:
```
WARNING: /private/var/tmp/_bazel_ponti/1e60068efdb36cc98840a74d3f5c528e/external/local_config_tf/BUILD:3504:1: target 'libtensorflow_framework.so' is both a rule and a file; please choose another name for the rule
WARNING: /private/var/tmp/_bazel_ponti/1e60068efdb36cc98840a74d3f5c528e/external/local_config_tf/BUILD:5:12: in hdrs attribute of cc_library rule @local_config_tf//:tf_header_lib: file '_api_implementation.so' from
target '@local_config_tf//:tf_header_include' is not allowed in hdrs
WARNING: /private/var/tmp/_bazel_ponti/1e60068efdb36cc98840a74d3f5c528e/external/local_config_tf/BUILD:5:12: in hdrs attribute of cc_library rule @local_config_tf//:tf_header_lib: file '_message.so' from target '@lo
cal_config_tf//:tf_header_include' is not allowed in hdrs
```

Again, is this something about my local dev environment alongside tensorflow? Or something I've missed when defining the dependency on the appropriate tensorflow pieces?

Thanks for any assistance

**Comment by damienpontifex** [comment]
Done both of these in my branch already here https://github.com/damienpontifex/io/blob/azure-blob-fs/third_party/azure_storage_fuse.BUILD and here https://github.com/damienpontifex/io/blob/azure-blob-fs/WORKSPACE#L136-L145

That's why I thought they were odd. Tried a clean and rebuild with the below steps, but same result:
```bash
bazel clean --expunge
git clean -xfd
bazel build //tensorflow_io/azure:azfs.so
```

**Comment by damienpontifex** [comment]
@yongtang could it be related to these lines:
```
linkopts = select({
        "//tensorflow:linux_x86_64": [
            "-luuid"
        ],
        "//conditions:default": [],
    }),
```

Had these from tensorflow and now wondering if the same select options are available in tensorflow_io

**Comment by yongtang** [comment]
Ah `"//tensorflow:linux_x86_64"` is not available in tensorflow_io. They are used as placeholder for other platforms. Since tensorflow_io only support Linux at the moment anyway, you can remove the `"//tensorflow:linux_x86_64"` and ` "//conditions:default"` then I think it will work.

**Comment by damienpontifex** [comment]
Thanks @yongtang 
I've got to the point where bazel builds the targets successfully and just adding some tests. I'm now getting an error:

```
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/private/var/tmp/_bazel_ponti/1e60068efdb36cc98840a74d3f5c528e/sandbox/darwin-sandbox/1/execroot/__main__/bazel-out/darwin-fastbuild/bin/tensorflow_io/azure/azfs_py_test.runfiles/__main__/tensorflow_io/azure/_azfs.so, 6): Symbol not found: _Curl_ssl_darwinssl
  Referenced from: /private/var/tmp/_bazel_ponti/1e60068efdb36cc98840a74d3f5c528e/sandbox/darwin-sandbox/1/execroot/__main__/bazel-out/darwin-fastbuild/bin/tensorflow_io/azure/azfs_py_test.runfiles/__main__/tensorflow_io/azure/_azfs.so
  Expected in: flat namespace
 in /private/var/tmp/_bazel_ponti/1e60068efdb36cc98840a74d3f5c528e/sandbox/darwin-sandbox/1/execroot/__main__/bazel-out/darwin-fastbuild/bin/tensorflow_io/azure/azfs_py_test.runfiles/__main__/tensorflow_io/azure/_azfs.so
```

Are you able to look at the branch or fork or provide insights into why `_Curl_ssl_darwinssl` could not be found or what it is? I assume it's something to do with linking with deps `@boringssl//:ssl`

**Comment by yongtang** [comment]
@damienpontifex I am able to build your branch fine:
```
$ docker run -it -v ${PWD}:/working_dir -w /working_dir tensorflow/tensorflow:custom-op
$ # In docker
$ apt-get -y -qq update
$ apt-get -y -qq install uuid-dev
$ ./configure.sh
$ curl -OL https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel-0.20.0-installer-linux-x86_64.sh
$ chmod +x bazel-0.20.0-installer-linux-x86_64.sh
$ ./bazel-0.20.0-installer-linux-x86_64.sh
$ bazel build //tensorflow_io/azure:_azfs.so
...
...
INFO: Found 1 target...
Target //tensorflow_io/azure:_azfs.so up-to-date:
  bazel-bin/tensorflow_io/azure/_azfs.so
INFO: Elapsed time: 40.816s, Critical Path: 10.28s
INFO: 407 processes: 407 local.
INFO: Build completed successfully, 413 total actions
```

**Comment by damienpontifex** [comment]
Thanks, I was being an idiot and running them on macOS when I knew that wasn't supported yet. Proceeded and starting to add some py tests now. Thanks again

**Comment by kkmsft** [comment]
Hi @damienpontifex, Thank you the work to bring it to the tensor flow io project. Please let me know if you need some help with this.

**Comment by damienpontifex** [comment]
@kkmsft it's now merged into master. We've already identified a few fixes to make, but that'll be much easier now the bulk of that base work is there we can iterate on. Would be very happy for any testing, feedback and fixes if you find any
