### ISSUE TITLE
HDF5Dataset(path, key).batch(size) does't work

### ISSUE THREAD

**Issue by Rendok** [tensorflow/io#484]
Hello.

_tf version: 2.0.0.rc0
tf_io version: 0.9.0-dev1759_

.batch(SIZE) applied to HDF5Dataset() doesn't work. Instead of slicing the dataset, it creates an extra dimension.

For example, if I have [2560, 84, 84, 3] dims dataset, after .batch(100), the shape of a batch is [1, 2560, 84, 84, 3].

Cheers

**Comment by yongtang** [comment]
@Rendok my understanding is that this is largely the expected behavior for tf.data.Dataset. `batch` will always create an additional dimension. If you only have one element ` [2560, 84, 84, 3]` in the form of  tf.data.Dataset:
```
 [2560, 84, 84, 3]  + .batch(100) => [100, 2560, 84, 84, 3] => [1, 2560, 84, 84, 3] * 1 element 

# note since you don't have enough data, you only have 1 element at the end with [1, 2560, 84, 84, 3]
```

If your have 2560 elements of  `[84, 84, 3]` in the form of  tf.data.Dataset, then it will have the effect you desire:
```
 [84, 84, 3]  + .batch(100) => [100, 84, 84, 3] => [100, 84, 84, 3] * 25 element + [60, 84, 84, 3]

# note you have one [60, 84, 84, 3] extra which is the remain of the last chunk.
```

**Comment by yongtang** [comment]
@Rendok I will close this issue for now. But feel free to reopen if you still have questions.

**Comment by Rendok** [comment]
@yongtang Thanks for your reply. However, I think the behaviour is not in line with the standard behaviour of `tf.data.Dataset`. Here is an example:

```
import h5py
import tensorflow_io.hdf5 as tfio
data = np.random.randn(2000, 2, 2, 3)

with h5py.File(filename, 'w') as f:
    f.create_dataset('int', data=data, dtype='i4')

dataset = tfio.HDF5Dataset(filename, '/int')

print(dataset)
# <HDF5Dataset shapes: (None, 2, 2, 3), types: tf.int32>
# here looks right

for d in dataset.take(3):
    print(d.shape)
```
This prints `(2000, 2, 2, 3)`, although it should be:
```
(1, 2, 2, 3)
(1, 2, 2, 3)
(1, 2, 2, 3)
```

Then for
```
for d in dataset.batch(100).take(3):
    print(d.shape)
```
This prints `(1, 2000, 2, 2, 3)`, although it should be 
```
(100, 2, 2, 3)
(100, 2, 2, 3)
(100, 2, 2, 3)
```

I believe `.shuffle()` and the rest also work incorrectly.

Cheers
