### ISSUE TITLE
How streaming dataset can be used in distributed environment?

### ISSUE THREAD

**Issue by liyi193328** [tensorflow/io#488]
Hi, guys:
      I 'm considering the problem , is streaming dataset can be used directly in distributed statergy(like estimatory distritubed api).
      As I know, for static data(file list), N worker can consume N batch, and each worker is shard a dataset to consum data. But for streaming data, we don't know the whole data size(len),  what is the dataset shard method ?  we need to do other data split operation for streaming data? (I use estimator distributed api). Thanks

**Comment by yongtang** [comment]
@liyi193328 See some related discussion in https://github.com/tensorflow/io/pull/478 

When passing dataset for tf.keras, tf.keras expect dataset could be recreated and repeated. If your dataset is not repeatable, then you could use tf.keras.Sequence which will only read data once (but internally cache the whole dataset implicitly).

For tf.estimator, I am not very familiar with estimator api so don't know how data are processed.

**Comment by liyi193328** [comment]
@yongtang thanks. And how distributed stratergy handle the streaming dataset?

**Comment by yongtang** [comment]
@liyi193328 That very much depending on the `distributed strategy`. For training, most of the time each node will have a copy of either whole or partial data. As I mentioned streaming dataset is not a good fit for distributed training as it is not truly `splittable`. To split data multiple node may have to unnecessarily repeat the data multiple times. Inference is totally different though.

**Comment by liyi193328** [comment]
@yongtang Got it, nice, Thanks very much
