### ISSUE TITLE
[Azure support] fails with 'std::runtime_error'

### ISSUE THREAD

**Issue by psitronic** [tensorflow/io#500]
Python 3.6.5
TF 1.14

```
import os
import tensorflow as tf
import tensorflow_io.azure

os.environ['TF_AZURE_STORAGE_BLOB_ENDPOINT']='.blob.core.windows.net'
os.environ['TF_AZURE_STORAGE_KEY']=<MY_KEY>

with tf.gfile.Open('az://<account-name>/<container>/path/to/blob.csv') as infile:
    file = infile.read()
```
fails with the exception:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  length of base64 string is not an even multiple of 4
```

**Comment by yongtang** [comment]
@damienpontifex wondering if you have an idea about the exception?

Also, @psitronic it would be good if you could provide a small `blob.csv` that can trigger the problem.

**Comment by psitronic** [comment]
Here it is:
[blob.zip](https://github.com/tensorflow/io/files/3651381/blob.zip)

Forgot to mention:
TF I/O 0.7.0

**Comment by damienpontifex** [comment]
Thanks, I'll take a look and see if I can figure it out

**Comment by yongtang** [comment]
@psitronic I recently created an Azure account and tried myself, with tensorflow 2.0 + tensorflow-io 0.10.0. It looks like the azure file system works correctly. Here is the code I use (as TF 2.0 made some changes):
```
  os.environ['TF_AZURE_STORAGE_KEY']=<key>
  with tf.io.gfile.GFile('az://<account>/<container>/blob.csv', mode='r') as infile:
    file = infile.read()
```

It did through out an exception:
```
E       UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbd in position 0: invalid start byte
```

But as far as I could see this is not related to tensorflow-io's Azure file system, instead it is related to tensorflow issue  tensorflow/tensorflow#33563

I will close this issue for now, let's track the other issue on  tensorflow/tensorflow#33563 instead.

**Comment by niklas-mohr-jdas** [comment]
Does the above mentioned PR also fix the issue with utf-8 characters in the azure key?
```
import os
import tensorflow as tf
import tensorflow_io as tfio
os.environ['TF_AZURE_STORAGE_KEY']="Bär"
tf.io.gfile.exists("az://account/container/test.txt")
```
triggers an error
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  length of base64 string is not an even multiple of 4
Aborted
```
using `tensorflow==2.1.0` and `tensorflow_io==0.11.0`.
The same code works with a key `os.environ['TF_AZURE_STORAGE_KEY']="Bur"`

**Comment by yongtang** [comment]
@niklas-mohr-jdas Sorry the GitHub notification email slip through my inbox. I will take a look.

**Comment by yongtang** [comment]
@niklas-mohr-jdas  I think this is a new scenario. Opened a new issue #842 to track.
