### ISSUE TITLE
Add prefix for all implemented ops

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#510]
TensorFlow RFC https://github.com/tensorflow/community/pull/126 introduced namespaces for custom TF ops that are separated by `>` characters.

> Since an op’s name uniquely identifies it, different TF packages should ensure their op names are globally unique across the entire TF ecosystem. To do so, prepend the package’s name to the op’s name and separate with a ‘>’. An op named “MatMul” inside the “tensorflow_addons” package should be named “Addons>MatMul”, for example.

We should follow the same prefix rule so that tensorflow-io plays well in overall tensorflow ecosystem.

**Comment by ricky3dec** [comment]
Hello @yongtang , was just understanding the changes needed for this, and found a reference pull request in tensorflow_addons : https://github.com/tensorflow/addons/pull/516

Hope, this should be good reference point and be of some help!

**Comment by yongtang** [comment]
@ricky3dec That would be great!

**Comment by ricky3dec** [comment]
Referring to : tensorflow_io/pubsub/ops/dataset_ops.cc

REGISTER_OP("PubSubDataset") needs to be changed to REGISTER_OP("IO>PubSubDataset") i.e. prefix the ops with IO>. 

And similarly it's usage should become and elsewhere as well:

REGISTER_KERNEL_BUILDER(Name("IO>PubSubDataset").Device(DEVICE_CPU),
                        PubSubDatasetOp);

If this looks ok, please assign this CR to me, and also please add me to the list of contributors. 

Thanks!

**Comment by ricky3dec** [comment]
Hello @yongtang , if everything looks ok, can you help me get this going?

**Comment by yongtang** [comment]
@ricky3dec Assigned the issue to you, we always creates pull requests against master branch. Once it is in master branch it will be cherry-picked to a specific branch (if needed).

**Comment by ricky3dec** [comment]
Hello @yongtang I created an initial pull request for this : https://github.com/tensorflow/io/pull/540.

Though I see some failure in nightly build:https://travis-ci.org/tensorflow/io/jobs/597223205. Please let me know If I am missing something obvious, until I will try to debug the error. Since this is something new for me.

Please note I have not modified the python operations, please let me know if that is required too and also help with 1-2 examples.

Thanks

**Comment by ricky3dec** [comment]
@yongtang , I am able to debug locally now, please hold on the review for now, until I request again. Thanks!

**Comment by ricky3dec** [comment]
Hello @yongtang , I hope there are no more obvious issues with build (except that some jobs are timing out especially macos ones and linux one executed fine, so not sure about that).

You may review the PR now: https://github.com/tensorflow/io/pull/540

These are minimalistic changes, to make things going. Please let me know anything additional to be done as part of this

**Comment by ricky3dec** [comment]
Thanks @yongtang for your support!

**Comment by ricky3dec** [comment]
@yongtang thanks for working on fixing additional tests, looks like I should have re-checked changes after the merge from master. I shall take care of it next time.

That brings to me another point, could you please share the build and test steps reference, so that I can do some sanity checks on my end?
Also, I think we should document these naming conventions in development guide, so that anyone contributing can follow them. I know it's not fool proof, but still some guidance would be there. Just a suggestion!

Is there anything pending in this issue now?

**Comment by yongtang** [comment]
@ricky3dec The developing and testing is covered in https://github.com/tensorflow/io#python

It may not be very detailed or complete. If you find anything missing, we can improve the documentation and update. 

The naming conventions is a good content for docs. Would be great if you can help?

Our initial docs directory has been setup in https://github.com/tensorflow/io/pull/498

The tensorflow/docs team is actively helping us getting tensorflow-io's documentation into tensorflow.org. I think it would be great if we could get documentation for development guide in `tensorflow_io/docs` directory. Then tensorflow/docs team can help us get the content published in tensorflow.org website!

**Comment by ricky3dec** [comment]
Sure @yongtang , I can work on that!

Can you please help create an issue and assign that to me, with details about what all needs to be taken care from documentation side?

**Comment by ricky3dec** [comment]
Hello @yongtang , I did not get a chance to follow up on all discussions, but just wanted to know, did we face any issues with current naming convention "IO>"? I see we had to change it to 'Io' as a prefix in current release.

**Comment by yongtang** [comment]
@ricky3dec The `"IO>"` works with `TF 1.15.0rc3 but not `TF 1.15.0` (final). Since we are pending release for 0.8.0 (compatible TF1.15.0), I switch to `Io` so that all python changes could remain (only C++ changes from  `"IO>"` => `"Io"`.

Our 0.9.0 release (will happen as soon as we release 0.8.0) with switch back to `"IO>"` as this is the way to move forward.

See https://github.com/tensorflow/io/pull/555/commits which reverts back the change. (will only merge after 0.8.0 release).

**Comment by ricky3dec** [comment]
Thanks for your explanation @yongtang !

**Comment by ricky3dec** [comment]
Hello @yongtang , anything more pending in this issue? Not sure, when we actually close the issues :-)

**Comment by yongtang** [comment]
@ricky3dec All have been completed. Thanks for the great work! 👍 🎉
