### ISSUE TITLE
[Azure support] Never finishes reading a blob (EOF problem?)

### ISSUE THREAD

**Issue by psitronic** [tensorflow/io#511]
TF2.0rc2
TF I/O tensorflow-io-nightly
Python 3.7.4

I used a simple csv file:
```
col_1, col_2, col_3
0,0,1
0,0,1
```

The dataset is created by the following code:

```
import os
import tensorflow as tf
import tensorflow_io.azure

os.environ['TF_AZURE_STORAGE_KEY'] = <KEY>
record_defaults = [[-1], [-1], [-1]]

files = <path-to-file>

dataset = tf.data.experimental.CsvDataset(files, record_defaults=record_defaults, header=True)

for item in dataset:
    print(item)
```

If `<path-to-file>` is `/local/path/to/file` the dateset is created and the output of its iterations:
```
(<tf.Tensor: id=18, shape=(), dtype=int32, numpy=0>, <tf.Tensor: id=19, shape=(), dtype=int32, numpy=0>, <tf.Tensor: id=20, shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: id=21, shape=(), dtype=int32, numpy=0>, <tf.Tensor: id=22, shape=(), dtype=int32, numpy=0>, <tf.Tensor: id=23, shape=(), dtype=int32, numpy=1>)

Process finished with exit code 0
```
It exits the loop after iterating. The same result if I read from Google cloud storage using `gs://<blob>/path/to/file`.

When `<path-to-file>` is `az://<azure-storage-account>/<container>/path/to/file` (Azure storage) it never exits the loop even after finishing all iterations (note there is no `Process finished with exit code 0`):
```
(<tf.Tensor: id=18, shape=(), dtype=int32, numpy=0>, <tf.Tensor: id=19, shape=(), dtype=int32, numpy=0>, <tf.Tensor: id=20, shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: id=21, shape=(), dtype=int32, numpy=0>, <tf.Tensor: id=22, shape=(), dtype=int32, numpy=0>, <tf.Tensor: id=23, shape=(), dtype=int32, numpy=1>)
```

**Comment by damienpontifex** [comment]
Will do @yongtang

**Comment by yongtang** [comment]
@psitronic @damienpontifex I don't have access to Azure storage, though I am able to reproduce the issue with the Azure emulator. Think I found out where the issue arise, will send a PR soon.

**Comment by yongtang** [comment]
Added a PR #525 for the fix.
