### ISSUE TITLE
tf-io for tensorflow 2.0 ?

### ISSUE THREAD

**Issue by kleysonr** [tensorflow/io#521]
When will tensorflow-io be compatible with the new tensorflow 2.0 ?

**Comment by yongtang** [comment]
@kleysonr At the moment tensowflow-io-nightly is based on tensorflow==2.0.0 so it is compatible with 2.0. We are actively working on getting a release version soon.

The current:
1) Release tensorflow-io 0.8.0 once TensorFlow 1.15.0 final is out.
2) Release tensorflow-io 0.9.0 immediately after tensorflow-io 0.8.0 is out.

At the moment, the update I had in SIG Build's meeting, is that TensorFlow 1.15.0 final was supposed to be out this week but was delayed by an additional patch. My expectation is that TensorFlow 1.15 final will be out in one or two weeks.

Once TensorFlow 1.15.0 final is out, tensorflow-io will immediate release two versions:
1) tensorflow-io 0.8.0 <==> TensorFlow 1.15.0
2) tensorflow-io 0.9.0 <==> TensorFlow 2.0.0

The only reason that is hold tensorflow-io release is that we would rather release 0.8.0 then 0.9.0, than release 0.9.0 (for TF 2.0) then 0.8.0 (for TF 1.15).

We will be there in a couple of weeks I assume.

**Comment by yongtang** [comment]
@hollowgalaxy version 0.8 and 0.9 will have exactly the same code base, the only difference is that 0.8 depends on tensorflow 1.15.0 and 0.9 depends on tensorflow 2.0.0.

The diff is in setup.py, and the behavior difference is controlled indirectly by tensorflow (2.0.0 has eager mode enabled by default while 1.15.0 does not).

**Comment by yongtang** [comment]
tensorflow-io v0.9.0 is compatible with TF2.0 and has been released:
https://github.com/tensorflow/io/releases/tag/v0.9.0

Let us know if you run into any issues.
