### ISSUE TITLE
BigQueryClient read_session: `row_restriction` is unused

### ISSUE THREAD

**Issue by megaserg** [tensorflow/io#527]
Looks like `row_restriction` parameter is saved in Python class but never propagated to actual BigQuery client. Is my understanding correct? @vlasenkoalexey

**Comment by vlasenkoalexey** [comment]
Indeed, looks like I missed to pipe it through to the C++ code. Will fix this.

**Comment by megaserg** [comment]
Thank you very much! Appreciate the convenient interface.
