### ISSUE TITLE
Add naming conventions and prefixes in docs for development guide

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#552]
We should document naming conventions in development guide, so that anyone contributing can follow.

**Comment by ricky3dec** [comment]
On it now!

**Comment by ricky3dec** [comment]
Hello @yongtang , anything more pending in this issue? Not sure, when we actually close the issues :-)

**Comment by yongtang** [comment]
@ricky3dec All completed, thanks for the great contribution! 👍 🎉
