### ISSUE TITLE
tensorflow_io build is broken at master

### ISSUE THREAD

**Issue by vlasenkoalexey** [tensorflow/io#572]
I believe this is due to https://github.com/tensorflow/io/pull/570
There is a typo in /.travis/bazel.build.sh, but tests are not passing even with the fix:
https://github.com/tensorflow/io/pull/571

And even with the fix on my machine, auditwheel does not generate whl files under wheelhouse folder. When I run auditwheel show, it said "The wheel requires no external shared libraries! :)"

**Comment by yongtang** [comment]
Thanks @vlasenkoalexey! I enabled python 3.7 for macOS but looks like we just encountered too many issues with python 3.7 macOS. let me disable the python 3.7 on macOS and revert back.

**Comment by yongtang** [comment]
Master build has been fixed in:
https://travis-ci.org/tensorflow/io/builds/601023351
