### ISSUE TITLE
audio sample rate support

### ISSUE THREAD

**Issue by Mazagov** [tensorflow/io#582]
I am looking through  IODataset from_ffmpeg and from_audio and it's not clear to me how read audio at a specific sampling rate similar to what was provided in [tf.contrib.ffmpeg.decode_audio](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/contrib/ffmpeg/decode_audio).
Is this already implemented? if so can you point me out to how to do that, if not can we add support to that?

**Comment by yongtang** [comment]
The resample of the audio is not supported yet. We could add this feature. Ideally I think this could be implemented as a standalone custom ops, and used as
```
dataset = tfio.IODataset.from_ffmpeg(...)
dataset = dataset.map(lambda e: resample(e,...))
```

Will work on this feature later (likely after next week).

**Comment by aliutkus** [comment]
any update ?

**Comment by yongtang** [comment]
@Mazagov @aliutkus Created a PR #803 to add resample support, based on Xiph's speex library. Please take a look if interested.
