### ISSUE TITLE
macos/ERROR: No matching distribution found for tensorflow-io

### ISSUE THREAD

**Issue by purbanow** [tensorflow/io#609]
Hi,
Any idea why with pip2 is working but with pip3 it doesn't?

![image](https://user-images.githubusercontent.com/37292156/68208828-0794f980-000d-11ea-832d-372b248abbd9.png)

Thanks

**Comment by yongtang** [comment]
@purbanow We don't have python 3.7 support yet, but are actively working on it (see PR #576). Python 3.7 support on Mac should be available in the next version of release.
