### ISSUE TITLE
Please put a mac build of release 0.7.1 in PyPI

### ISSUE THREAD

**Issue by daphneweinstein** [tensorflow/io#610]
I would like to use tensorflow-io 0.7.1 on a mac operating system and noticed that there is no 0.7.1 mac wheel in PyPI. 

I need the fixes of 0.7.0 introduced in 0.7.1. I am working on a project where it is not currently tenable to upgrade to 0.8.0 or 0.9.0 because we are relying on an earlier version of tensorflow.

 I would just build the wheel locally from my downloaded zip of 0.7.1 but I also get errors when doing so:

```python setup.py install
setup.py - create /var/folders/6x/cwr4n2kn72z4nbsqn8xmzxvc0000gn/T/tmpfci63B and copy tensorflow_io
setup.py - create /var/folders/6x/cwr4n2kn72z4nbsqn8xmzxvc0000gn/T/tmpfci63B/MANIFEST.in
setup.py - create /var/folders/6x/cwr4n2kn72z4nbsqn8xmzxvc0000gn/T/tmpfci63B/setup.py with required = 'tensorflow>=1.14.0,<1.15.0', project_name = 'tensorflow-io' and __version__ = 0.7.1
setup.py - run sandbox.run_setup /var/folders/6x/cwr4n2kn72z4nbsqn8xmzxvc0000gn/T/tmpfci63B/setup.py ['install']
running install
error: SandboxViolation: open('/Users/dweinstein/miniconda2/envs/tf1-14/lib/python2.7/site-packages/test-easy-install-8051.write-test', 'w') {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.```

Thanks so much for your help

**Comment by vlasenkoalexey** [comment]
Indeed I missed to uploade macos files.
The right way to build those is to sync your github repostitory to 0.7.1 tag and run following command: bash -x -e .travis/python.release.sh

I'll try to rebuild myself and upload macos files.

**Comment by daphneweinstein** [comment]
Thanks! Will wait for the upload because I'm still having trouble building locally using the command you suggest.

**Comment by vlasenkoalexey** [comment]
Uploaded files to pypi: https://pypi.org/project/tensorflow-io/0.7.1/#files
Tested on my mac, everything works as expected.

Building on Mac is a bit tricky since everything is built without docker and you need all dependencies to be installed. 
bash -x -e .travis/python.release.sh script worked for me after installing all python versions and manually upgrading pip for each version.

Closing bug, please let me know if you still have issues.

**Comment by daphneweinstein** [comment]
Works perfectly. Thanks so much for the quick turnaround on this.
