### ISSUE TITLE
Enable CPU instructions when building the binary.

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#612]
This was initially raised in #611, but I think it deserves wide discussion by its own:

In order to support the maximum range of users, we use the most generic CPU instructions when compiling C++ code. This ensures user will not encounter any invalid CPU instructions if their machine is old.

However, this is really bad in performance as the binary we shipped does not use modern instructions such as AVX/SSE4.2 etc which has been around for a long time (SSE4.2 was released in 2008 if I remember correctly).

I believe we really could enable at least instructions that have been around for some time. This will help the performance greatly.

/cc @vlasenkoalexey, I remember you mentioned at one point that there were some performance issues with avro in bigquery. Maybe we could enabling additional CPU instructions to give it a try?

**Comment by yongtang** [comment]
PR #613 adds SSE4.2 and AVX support which is inline with tensorflow-core.

AVX2 is not enabled, also inline with tensorflow-io.

**Comment by vlasenkoalexey** [comment]
I'll run few tests to see if it had any effect on bigquery performance.

**Comment by yongtang** [comment]
@vlasenkoalexey Thanks! 👍
