### ISSUE TITLE
tfio.ffmpeg.VideoDataset doesn't work inside of  tf.function

### ISSUE THREAD

**Issue by hollowgalaxy** [tensorflow/io#616]
To be more descriptive.... I'm trying to do something along the lines of 
```
csv_dataset = Dataset(....)
csv.flat_map(lambda filename, label: Dataset.zip(VideoDataset(filename),Dataset.from_tensor(label).repeat))
```
Tried using `tfio.ffmpeg.VideoDataset`
```
    nflux/amazon_demo/vid_extV2/video_tools/kinetics_dataset.py:88 _csv_to_clips  *
        frames = VideoDataset(video_path)
    anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_io/ffmpeg/python/ops/ffmpeg_ops.py:43 __init__
        super(VideoDataset, self).__init__(filename, stream)
    anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_io/core/python/ops/ffmpeg_dataset_ops.py:52 __init__
        shape = tf.TensorShape([None if e < 0 else e for e in shape.numpy()])
    AttributeError: 'Tensor' object has no attribute 'numpy'
```

When I use `tfio.ffmpeg.decode_video(video_path,0)` as suggested by https://github.com/tensorflow/io/issues/581#issuecomment-550132324
```
Traceback (most recent call last):
  File "/home/hollowgalaxy/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-54971d1eb051>", line 1, in <module>
    frames = decode_video(video_path, 0)
  File "<string>", line 849, in io_ffmpeg_decode_video
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: unable to open file: memory [Op:IO>FfmpegDecodeVideo]
```

Switched to using 
`video = tfio.IOTensor.from_ffmpeg(video_path)._values[0].to_tensor()`
error similar to VideoDataset
```
        frames = tfio.IOTensor.from_ffmpeg(video_path)._values[0].to_tensor()
    anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_io/core/python/ops/io_tensor.py:430 from_ffmpeg  *
        return ffmpeg_io_tensor_ops.FFmpegIOTensor(
    anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_io/core/python/ops/ffmpeg_io_tensor_ops.py:92 __init__
        columns = [column.decode() for column in columns.numpy().tolist()]
    AttributeError: 'Tensor' object has no attribute 'numpy'
```

Ideally I would prefer the ability to load a video into a tensor. I was initially using VideoDataset because I was under impression that it loaded part of the video and not the whole thing.
*Edit: statement below is not true*
The first example works if I remove the tf.function decorator.

**Comment by hollowgalaxy** [comment]
I take it back slightly, removing `tf.function` still causes `VideoDataset` to fail inside of the flat_map function

**Comment by hollowgalaxy** [comment]
Also tried putting `VideoDataset` into `tf.py_function`.
This lead to OOM error. I didn't explore specifically why (as my video was sensible, [267,1080,720,3]) but believed that it may be that sseveral copies of the video accumulated one is a tf tensor another is a numpy ndarray and perhaps a 3rd one due to accumulation of `get_next` from the `VideoDataset`

**Comment by hollowgalaxy** [comment]
Solved. 
The magic sause I was missing         
```
content = tf.io.read_file(video_path)
frames = D.from_tensor_slices(decode_video(content, 0))
```

Works inside the tf.function as intended.

**Comment by yongtang** [comment]
@hollowgalaxy Added PR #622 for the fix.
