### ISSUE TITLE
Kokoro CI error

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#621]
I notice Kokoro CI is returning an error for all build in `tensorflow/io`

```
+ readable_run wget https://github.com/bazelbuild/bazel/releases/download/0.29.1/bazel-0.29.1-installer-linux-x86_64.sh
/tmpfs/src/piper/google3/learning/brain/testing/tensorflow_io/kokoro/common.sh: line 26: \
readable_run: command not found
```

Also noticed that the same thing is happening to `tensorflow/addons` repo as well (https://github.com/tensorflow/addons#official-builds). (/cc @seanpmorgan )

I guess there might be some internal infrastructure change that caused `readable_run: command not found`? 

/cc @kokoro-team @ewilderj @martinwicke

**Comment by suyashkumar** [comment]
I noticed this on PR #620, and looked into it a little. I am fairly certain I identified the internal change that broke these builds, and sent a potential fix for review!

**Comment by suyashkumar** [comment]
Looks like the fix worked! Here's a passing build from #620: https://source.cloud.google.com/results/invocations/12b5c52d-ebea-4b10-940c-39c07d29a06f/targets

@yongtang feel free to close this issue out!

**Comment by yongtang** [comment]
Thanks @suyashkumar, great work and much appreciated! 👍 🎉

**Comment by suyashkumar** [comment]
No problem, happy to help!
