### ISSUE TITLE
BigQueryClient query with arrays

### ISSUE THREAD

**Issue by cjmcgraw** [tensorflow/io#627]
Hey guys. I am attempting to pull a table from bigquery that has nested arrays of values inside of it. I would like to pull it into the dataset then do a flat_map across it to unnest the data.

Currently it seems that the BigQueryClient doesn't actually support arrays which is needed for my work with TensorflowRanking

here is a snippet of code:
```python
from tensorflow_io import bigquery as tfiobq

def build_dataset(*args, **kwargs):
    return (tfiobq.BigQueryClient()
        .read_session(
            "projects/" + billing_project,
            project_id=project_id,
            dataset_id=dataset_id,
            table_id=table_id,
            selected_fields=["feature1", "feature2", "labels"],
            output_types=[tf.string, tf.int64, tf.int64],
        )
        .parallel_read_rows()
    )
```

Here feature2 and labels are both arrays in the table

I received the following exception when I try to get the next value from the dataset:

```
2019-11-12 01:05:55.884373: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at iterator_ops.cc:929 : Invalid argument: unsupported data type: 10
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 622, in __next__
    return self.next()
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 666, in next
    return self._next_internal()
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 651, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2673, in iterator_get_next_sync
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: unsupported data type: 10 [Op:IteratorGetNextSync]
```

**Comment by vlasenkoalexey** [comment]
That's correct, reading nested data structures is not supported.
If your table is not very big you can write a query to flatten it, and materialize as another table which will be readable by BigQuery reader. Code to do this is pretty straightforward.

`from google.cloud import bigquery
client = bigquery.Client(project=PROJECT_ID)

dataset_id = 'alekseyv_census_dataset'

def create_bigquery_table_from_query(query, destination_table_name):
    job_config = bigquery.QueryJobConfig()

    dataset_ref = client.dataset(dataset_id)
    destination_table_ref = dataset_ref.table(destination_table_name)
    job_config.destination = destination_table_ref

    # Set configuration.query.createDisposition
    job_config.create_disposition = 'CREATE_IF_NEEDED'

    # Set configuration.query.writeDisposition
    job_config.write_disposition = 'WRITE_TRUNCATE'

    # Start the query
    job = client.query(query, job_config=job_config)

    # Wait for the query to finish
    job.result()  `

**Comment by cjmcgraw** [comment]
@vlasenkoalexey is it not supported because of bq limitations or because of library limitations? Just wondering how difficult a solution is to this. 

For my problem specifics: 

I deal in very high cardinality datasets. Most other options are not very valid. I am also open to the bq -> avro -> tfio approach as needed to handled this problem.

**Comment by vlasenkoalexey** [comment]
This is a BigQuery reader limitation, BigQuery can handle nested structures just fine.
I don't plan to add support for this in nearest future, but eventually it would be nice to have it implemented. The parser code is here, feel free to contribute: https://github.com/tensorflow/io/blob/master/tensorflow_io/bigquery/kernels/bigquery_lib.h

**Comment by RuhuaJiang** [comment]
Hey @vlasenkoalexey, we have internal use cases within Twitter for this.  Is there some special process in TFIO community I should follow to contribute or simply make a pull request?  I have an early prototype which enables: (for each BigQuery table row) for each column it could be REPEATED of primitive types such as STRING, FLOAT etc, RECORD is currently not supported (e.g  mode:REPEATED type:STRING). It gives us 1D tensor for this field instead of scalar Tensor.

**Comment by yongtang** [comment]
@RuhuaJiang Contribution is always welcomed! Please go ahead and create PR. The PR will be merged only if it is approved, though.

**Comment by vlasenkoalexey** [comment]
@RuhuaJiang I've recently added Arrow support #891 and as far as I understand Arrow serializer supports nested structures. I wanted to try it out, but didn't get to it. 
One catch is that Arrow doesn't support strings yet.
Feel free to send a PR or ping me with questions, will be happy to help.
For now as a workaround you can just flatten your dataset and materialize results in a temporary table and read from it using BQ reader.

**Comment by RuhuaJiang** [comment]
Sounds good, will create the PR

**Comment by sshrdp** [comment]
@RuhuaJiang Let us know if you run into any issues implementing the change. 
Do you expect your repeated primitives to have the same length across the batch? I'm worried that it would cause issues with dataset.batch call.

**Comment by RuhuaJiang** [comment]
@sshrdp  the Tensor generated from TFIO would be 1 rank variable-length dense Tensor. It would has a problem with dataset.batch.  We can convert that into a SparseTensor, where the values is the 1 rank variable-length dense Tensor, and indices is [1, 2, ... N-1] where N is size of that values. 
We already made it work end to end internally.  Recently was busy with other things haven't get a chance to  send the pull request yet. Will do it soon

**Comment by emkornfield** [comment]
@brills is there anything from TFX that could be borrowed to support nested data/string from Arrow to Tensors?
