### ISSUE TITLE
Provide Keras native I/O though IO-Layer for Kafka

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#633]
This comes from one discussion about Kafka + TensorFlow IO for predict.

> How can we turn the script into something that continuously streams/predicts from/to kafka?

During `model.predict` we used to rely on KerasCallback to capture the output of the data in a continuous fashion. There are several issues:
1) KerasCallback is in eager mode so it means switching back and forth in graph/eager mode.
2) It is not easy to combine the input data with output data when we need to do some further processing (e.g., calculate the statistics while in inference.).

Thinking again, I think in the past we over-complicates the situation. Keras essentially is a TF graph and every layer is a collection of subgraph. Keras's logic at the input data processing is getting completed because it need to support generator, tensor,  tf.data, numpy arrays, etc. (so many ways to pass the data).

However, in its core Keras is still a TF graph. So for any IO operation all we need is to just add a node in the TF graph, or, similar to tf.keras.layers, add a collection of nodes in the TF graph.

As such I think it is possible to construct an IO operation as a layer of the tf.keras.

Below is a rough diagram:

![Kafka+Keras](https://user-images.githubusercontent.com/6932348/68718666-c34eaf80-055e-11ea-8e94-d4bea65e0fd4.png)

**Comment by yongtang** [comment]
Created a PR #634 for this issue. Here is a rough usage:

```python

  model = tf.keras.Sequential([
      tf.keras.layers.Flatten(input_shape=(28, 28)),
      tf.keras.layers.Dense(128, activation=tf.nn.relu),
      tf.keras.layers.Dense(10, activation=tf.nn.softmax)
  ])

  model.compile(optimizer='adam',
                loss='sparse_categorical_crossentropy',
                metrics=['accuracy'])

  model.fit(train_images, train_labels, epochs=5)

  model.summary()

  # For predict, let's create an additional layer to tee to kafka
  io_layer = tfio.IOLayer.kafka("topic")

  # model.layers[-1].output is the output of the old model,
  # we add an additional layer of IOLayer on top of it, to `tee` the output data.
  io_model = tf.keras.models.Model(
      inputs=model.input,
      outputs=io_layer(model.layers[-1].output))

  # use new model for inference, however, since IOLayer does nothing
  # other than tee the data, no impact on model itself:
  predictions = io_model.predict(test_images)

  io_layer.sync()
```

/cc @terrytangyuan @BryanCutler 

Also /cc @zhjunqin @kaiwaehner @sbaier1 as it is related to Kafka and some discussions.

**Comment by yongtang** [comment]
The PR is opened in #634

**Comment by ricky3dec** [comment]
Hello @yongtang , just few questions:

1. when we are writing the outputs to Kafka here, do we really bother about kafka broker leader acknowledgement? Do we care about write guarantee here?
2. should we configure kafka in way that topics be created on runtime rather than static names while creating io_layer?. Was thinking if we can somehow provide automatic data abstraction for model outputs.
3. I think creating io_layer, passing it to keras model and then calling sync(), can somehow be made more abstract in usage. I am not sure if a flag can be passed, whether to sync to output along-with sync source, and that does this magic internally. For us output sources could be different? I understand today it's just kafka.

**Comment by yongtang** [comment]
Thanks @ricky3dec,

> when we are writing the outputs to Kafka here, do we really bother about kafka broker leader acknowledgement? Do we care about write guarantee here?
I think this is a configuration choice we can set. In #634 I only set a minimal configuration and kafka producer is in asynchronous mode. We could pass additional configurations as needed to have different behavior.

> should we configure kafka in way that topics be created on runtime rather than static names while creating io_layer? Like for e.g on basis of model type. Was thinking if we can somehow provide automatic data abstraction for model outputs.

I think that could be possible. We could allow the Layer to take two inputs, one is the kafka topic name and another is the value to send to kafka. There might be some overheads if each message is sent to topically different topics.

> I think creating io_layer, passing it to keras model and then calling sync(), can somehow be made more abstract in usage. I am not sure if a flag can be passed, whether to sync to output along-with sync target, and that does this magic internally. For us output targets could be different? I understand today it's just kafka.

Yes this area definitely could be improved. Ideally, we could enable auto-sync so that internally we sync as needed. For kafka it is a little special because the producer was set in asynchronous (for performance considerations). So even if `sync()` is not invoked, the message will eventually be delivered. `sync()` is just to make sure the message are delivered before the program exit. I think we could definitely improve.

Also, in PR  #634 I actually wrote two output layer, one is the Kafka, another is the (line-based) text file.

I am thinking to add more output layers for other formats as well. One interesting play is to have a video or audio streaming outputs so that pictures will be delivered in the form of a video. There are more we could do in this area I think.

**Comment by ricky3dec** [comment]
Thank you @yongtang for laying this out so clearly.

For the second question's comment :

"There might be some overheads if each message is sent to topically different topics."

- Actually what I was suggesting is to write different model's outputs to different topics, as it would become intuitive for kafka consumers, and also somehow we provide data abstraction.

**Comment by yongtang** [comment]
Thanks @ricky3dec. If you are looking for parameterize the `topic` for the layer, I think it might be possible to place a `tf.Variable` for topic at the time of the model creation, and feed it later? I will take a look and see if this is feasible.
