### ISSUE TITLE
[Genomics] Write docs & tutorials using tfio.genome

### ISSUE THREAD

**Issue by suyashkumar** [tensorflow/io#637]
Opening this issue to write docs & tutorials using `tfio.genome` as the API and ops are developed and begin to mature. Will hopefully get to this this weekend or early next week.

**Comment by kvignesh1420** [comment]
@suyashkumar any updates on this?

**Comment by suyashkumar** [comment]
Ah yes, this was closed by #775. Thanks for following up!
