### ISSUE TITLE
Explore GitHub Workflow option

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#645]
GitHub workflow is a feature provided by GitHub that allows you to run CI. Since GitHub workflow's execution limit is 6 hours, this is substantially better than the current Travis CI.

I found out some of the Google repo is already using GitHub workflow. One example is Google's filament project:

https://github.com/google/filament

While trying to setup GitHub workflow for tensorflow/io, noticed that it is not possible to set up due to some limitations.

Don't know exactly the underlying issue, though it looks like, GitHub is free to open source orgs, and not free for orgs that pays money to GitHub (sounds strange).

https://github.com/ansible/community/issues/505

Don't know if this is possible, though if tensorflow org is willing to convert to free open source org and don't pay money to GitHub then workflow will be enabled?

**Comment by terrytangyuan** [comment]
This list might be good to be explored in the future as well: https://github.com/sdras/awesome-actions

**Comment by yongtang** [comment]
GitHub actions are supported now:

https://github.com/tensorflow/io/pull/706

I will see if I can move all Travis CI tasks to GitHub Actions. We had enough churn in the past for the Travis CI cache issue.

**Comment by yongtang** [comment]
GitHub Workflow is in place now, as such this issue could be closed.
