### ISSUE TITLE
Standardize tests for dataset

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#651]
We are adding more and more formats to dataset, though the tests are pretty much ad hoc at the moment. Since tf.data's pipeline is pretty standard, we could standardize the tests for almost all Dataset in tensorflow-io by parametrization and fixture. We also need benchmark (with pytest-benchmark?).

/cc @BryanCutler as quite a few columnar dataset are from Arrow, I think it might be easier to standardize tests for those.

The tests for audio and streaming dataset could also be standardized as well.

/cc @terrytangyuan

**Comment by BryanCutler** [comment]
Sounds like a really good idea to me!

**Comment by yongtang** [comment]
Our tests for the majority of the dataset has been standardized in test_io_dataset_eager.py, with different scenarios testing increased functionality. Will continue to enhance the tests, but will close this issue as tests are there.
