### ISSUE TITLE
Integration with Mars

### ISSUE THREAD

**Issue by terrytangyuan** [tensorflow/io#652]
Mars is a tensor-based unified framework for large-scale data computation which scales Numpy, Pandas and Scikit-learn. More information can be found here: https://github.com/mars-project/mars.

Xuye (@qinxuye) from Alibaba Group is currently working on this integration. @qinxuye Feel free to ask any questions you have here and keep us posted on the progress.

**Comment by qinxuye** [comment]
Thank you @terrytangyuan , I will update status in this thread if I have any progress or question.
