### ISSUE TITLE
from_audio crashes in graph model when used in parallel tf.data pipeline

### ISSUE THREAD

**Issue by faroit** [tensorflow/io#654]
when using `from_audio` as part in a `tf.data` pipeline using:

```python
    @tf.function
    def load_chunked_wav(filename, seq=6):
        audio = tfio.IOTensor.graph(tf.int16).from_audio(filename)
        return audio.to_tensor()
```

`dataset = dataset.map(apply_source_loading, num_parallel_calls=k)`

the python interpreter randomly crashes for `k>1`:

```
python(90929,0x700006269000) malloc: *** error for object 0x7f84345998a0: pointer being freed was not allocated
python(90929,0x700006269000) malloc: *** set a breakpoint in malloc_error_break to debug
fish: 'python data.py terminated by signal SIGABRT (Abort)
```

I am using `0.10.0.dev2230` on tf 2.0.0 on OSX

**Comment by yongtang** [comment]
Haven't had the chance to test myself but if it run into issues with parallel run, then mostly likely the mutex lock was not placed. Let me take a quick look and see if I can have a PR.

**Comment by yongtang** [comment]
@faroit Added PR #656 for the fix.

**Comment by faroit** [comment]
@yongtang just tested the nightly. it indeed fixes it.

Thanks
