### ISSUE TITLE
decode video causes memory leak in ram.

### ISSUE THREAD

**Issue by hollowgalaxy** [tensorflow/io#680]
Code to replicate the issue.

```
import tensorflow as tf
from tensorflow_io.core.python.experimental.ffmpeg_ops import decode_video
def decode_video_profiling(files=[]):
    assert len(files) > 0, 'need files to profile'
    @tf.function
    def file_to_video(video_path):
        content = tf.io.read_file(video_path)
        frames = decode_video(content, 0)
        frames = tf.image.resize(frames, [224, 224])
        return frames[:20]
    video_paths = tf.data.Dataset.from_tensor_slices(files).repeat()
    videos = video_paths.map(file_to_video).batch(16, drop_remainder=True)
    memory_profiling(videos)

def memory_profiling(ds, steps=600, stop_and_repeat=False):
    from tqdm import tqdm
    import psutil
    pbar = tqdm(range(steps))
    percents = [psutil.virtual_memory().percent]
    pbar.set_description_str(f'{percents[-1]}')
    pbar.update()
    while pbar.n < pbar.total:
        for i, dps in enumerate(ds):
            if isinstance(dps, tuple):
                print(f'{i}:', ','.join([dp.shape for dp in dps]))
            else:
                print(f'{i}: {dps.shape}')
            percents += [psutil.virtual_memory().percent]
            pbar.set_description_str(f'Memory usage: {percents[-1]}%')
            pbar.update()
            if stop_and_repeat or pbar.n >= pbar.total:
                break

files = [...] # a bunch of mp4 valid mp4 files which are about 24 fps and 10 seconds long
decode_video_profiling(files)
```
The code above will print the metrics overtime *Note: This is CPU RAM* . However I put into a chart,
![Figure_2_all](https://user-images.githubusercontent.com/52365584/70837124-5fb2de80-1db7-11ea-8427-33245cb5de53.png)

**Comment by hollowgalaxy** [comment]
with the code it never reaches the full 600 steps. Throws an OOM error.

**Comment by hollowgalaxy** [comment]
I tried using the suggestion from https://github.com/tensorflow/io/pull/622#issue-339178915
however there is also a memory leak there as well. Code used:
```
import tensorflow_io as tfio
@tf.function
def func(filename):
  return tfio.IODataset.graph(tf.uint8).from_ffmpeg(filename, "v:0").batch(20).take(1)

def decode_video_profiling(files=[]):
    assert len(files) > 0, 'need files to profile'
    @tf.function
    def file_to_video(frames):
        frames = tf.image.convert_image_dtype(frames, dtype=tf.float32)
        frames = tf.image.resize(frames, [224, 224])
        return frames[:20]
    video_paths = D.from_tensor_slices(files).repeat()
    videos = video_paths.flat_map(func)
    videos = videos.map(file_to_video).batch(16, drop_remainder=True)
    videos = prep_preprocessing_options(videos, mode='train')
    memory_profiling(videos)
```

Results in memory usage like this 

![Figure_3_iodataset_test](https://user-images.githubusercontent.com/52365584/70841124-9e9f5f00-1dcc-11ea-9eb8-05a97f86edb7.png)


@yongtang  maybe you know something about this...

**Comment by yongtang** [comment]
I don't see obvious memory leak by reading the code. May need to setup leak detector to check. Will take a look.

**Comment by yongtang** [comment]
On macOS I am able to build with `-fsanitize=address`, after some tweak around of Bazel (also see https://github.com/bazelbuild/bazel/issues/6932). However, the generated binary does not run due to the following:
```
collecting ... ==32228==ERROR: Interceptors are not working. This may be because AddressSanitizer is loaded too late (e.g. via dlopen). Please launch the executable with:
DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib
"interceptors not installed" && 0Fatal Python error: Aborted
```

Adding `DYLD_INSERT_LIBRARIES` does not help and it still crashes.

**Comment by yongtang** [comment]
Will need to spend time looking into alternative of gcc on Linux.

**Comment by hollowgalaxy** [comment]
are you referring to the profiler? or is this the wrong thread?

**Comment by yongtang** [comment]
@hollowgalaxy I am trying to use `fsanitize-address` for memory instrumentation. Apparently it may have some issues with python calling a .so.

**Comment by hollowgalaxy** [comment]
I see. Not familiar with that. Perhaps Tensorflow contributors have a memory profiler for this type of occasion?

**Comment by hollowgalaxy** [comment]
by any chance have you come across a way to clear that memory? or is the only way right now to do `tf.reset_graph`?

**Comment by yongtang** [comment]
@hollowgalaxy I am still work on it... A little slowed as I am a little occupied. Will try to make progress soon.

**Comment by hollowgalaxy** [comment]
No worries. I also double checked to make sure it wasn't the introduction of the Dataset in the tf.function. It is not. memory stayed the same when I used 
```
@tf.function
def func(filename):
  return tf.data.Dataset.from_tensor_slices(np.zeroes([20,224,224,3]).batch(20).take(1)
```

**Comment by kyamagu** [comment]
Hi, I am experiencing the same issue in tensorflow-io==0.8.1.

In the current implementation, `av_read_frame` is called inside the do-while loop of `DecodePacket()`: https://github.com/tensorflow/io/blob/7032617c4598f1a4d2bc1800a6b01754379153cb/tensorflow_io/core/kernels/ffmpeg_kernels_deprecated.cc#L250

But it looks like this function is supposed to be always called with `av_packet_unref`:
https://github.com/FFmpeg/FFmpeg/blob/master/tests/api/api-h264-test.c#L139
https://ffmpeg.org/doxygen/trunk/group__lavf__decoding.html#ga4fdb3084415a82e3810de6ee60e46a61

Is this related to the leak? I am not an expert of ffmpeg and not completely sure.

**Comment by hollowgalaxy** [comment]
I don't have a quick way to test unless @yongtang can suggest something due to https://github.com/tensorflow/io/issues/707 and so I don't know of a way to recompile tfio to check this.

**Comment by kyamagu** [comment]
I checked this part myself and seems not doing `av_packet_unref` after every call to `av_read_frame` is the cause. I will try making a PR

**Comment by kyamagu** [comment]
Is this issue fixed? #1079

**Comment by kvignesh1420** [comment]
@hollowgalaxy any updated on this?

**Comment by hollowgalaxy** [comment]
I don't have the code anymore to test so if @kvignesh1420 would be able to answer this.

**Comment by kyamagu** [comment]
Hi, I was trying ASAN to test `decode_video`, and observed leaks:

```
=================================================================
==18140==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 208000 byte(s) in 100 object(s) allocated from:
    #0 0x1044c44e2 in wrap_realloc (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x454e2)
    #1 0x17f5ea030 in av_reallocp (libavutil.56.70.100.dylib:x86_64+0x1a030)
```

I am still investigating which part of the code has this bug, but I already observe increasing memory use over a long run.
