### ISSUE TITLE
Deprecation of python 2 after the release of 0.11.0

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#698]
At the moment we are planning on release of v0.11.0 which matches TF 2.1. As far as I know TF 2.1 is the last version with python 2 support. Combined with the fact that python 2 is reaching EOL in 12/31/2019, we could deprecate python 2 once v0.11.0 is released.

Since in Linux and macOS `python3` and `python` commands refer to different version, I think we want to use `python3` as the canonical command line moving forward. For example, in macOS Catalina, python 3.7.3 is pre-installed with Xcode and exists as `python3` command. `python` is reserved for python 2 but is deprecated in Catalina.

**Comment by BryanCutler** [comment]
+1 sounds good to me

**Comment by terrytangyuan** [comment]
+1

**Comment by yongtang** [comment]
With the recent addition of GitHub Actions, we pretty much dropped python2 from our build.
