### ISSUE TITLE
Support graph mode HDF5 tensorflow-io

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#710]
This is the issue to track the progress for graph mode HDF5 support in tensorflow-io. 

At the moment HDF5 is supported in tenorflow-io though it requires eager mode. It would be desirable to have graph mode support as well. 

Note in case of graph mode, dtype has to be provided in advance. The shape information may also be needed (to be confirmed).

This issue originated from https://github.com/tensorflow/io/issues/174#issuecomment-568243956

/cc @zaccharieramzi

**Comment by zaccharieramzi** [comment]
@yongtang thanks for creating this!
I have 2 questions:
- do you think this is going to be treated soon or isn't really a priority at the moment?
- when you say that shape will have to be provided, do you mean that the rank will have to be fixed, or even the dimensions (the latter case being of course less user-friendly)?

**Comment by yongtang** [comment]
@zaccharieramzi Exact shape information is definitely not needed. The rank may or may not be needed though I will have to take a look and see if it is possible. I will see if this could be addressed very soon, though due to the year end, it is likely to be done next year. 

By the way, have a good holiday 🎉 !

**Comment by zaccharieramzi** [comment]
Makes sense, thanks for all this and being so responsive.
Have a good holiday too!

**Comment by yongtang** [comment]
Created PR #732 for the fix.
