### ISSUE TITLE
Reading from Prometheus yields incorrect tensor format

### ISSUE THREAD

**Issue by sbaier1** [tensorflow/io#717]
I'm trying to ingest data from Prometheus for multivariate time-series analysis and am running into some issues.
My query returns multiple range vectors from different metrics, like such:
![Bildschirmfoto 2020-01-07 um 18 32 34](https://user-images.githubusercontent.com/20339314/71915472-1a968800-317c-11ea-9432-6874518e41e5.png)
with a long values array for each metric.

However, when running that same query using TFIO's `from_prometheus` method:
```python
>>> IOTensor.from_prometheus(query)
<PrometheusIOTensor: spec=(TensorSpec(shape=(491,), dtype=tf.int64, name=None), TensorSpec(shape=(491, 1), dtype=tf.float64, name=None))>
```
The shape is not what the metric API returns, the shape should be `(n,4)` for the `n` amount of data points in the range vectors.

an example query that would give you a similar result on any Prometheus deployment for testing would be something similar to:
`({__name__ =~ "apiserver_request_.+"})[1h:1m]`
you can use a "subquery" to get a range vector for an instant vector query.

**Comment by sbaier1** [comment]
it appears that the go binding only writes values for the first metric in the matrix received from Prometheus (i don't really know Go though, so not sure if i am reading this correctly)
https://github.com/tensorflow/io/blob/master/tensorflow_io/core/go/prometheus.go#L38

**Comment by yongtang** [comment]
@sbaier1 Thanks for raising the issue. I will take a look.

**Comment by sbaier1** [comment]
great!

as a side note, i just thought about how this would be implemented (building a workaround for myself right now) and i believe it might make sense to assign the `metric` dictionary as the `name` field of the TensorSpec, or setting a selected field in the `metric` dictionary as the name of the tensorspec.

Prometheus will return the result columns in a non-deterministic order meaning that the resulting dataset isn't consistent when querying repeatedly. In general sorting the output tensor columns by `__name__` should work but i'm sure that there are use cases that would want to sort by other or multiple labels from the `metric` dictionary.

What do you think?

**Comment by yongtang** [comment]
@sbaier1 I noticed that `__name__` could have a collision in case of multiple `jobs` or multiple `instances`. For example, a query with `up` might be:
```
curl http://localhost:9090/api/v1/query?query=up
```

with response:
```
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"up","instance":"localhost:9090","job":"prometheus"},"value":[1578935231.08,"1"]},{"metric":{"__name__":"up","instance":"localhost:9153","job":"coredns"},"value":[1578935231.08,"1"]}]}}
```

In that situation, I think an option is to return a structured entries in:
```
{
   'job1': {
      'instance1': {
        'up': ...,
        'other_metric': ...,
      }
      'instance2': {
        'up': ...,
        'other_metric': ...,
      }
    },
   'job2': {

    }
}
```

TF is capable of processing structured dataset so this might not be an challenge. In eager mode the structure could be probed automatically. (In graph mode user may need to provide a structure).

Will spend some time to see if the above route is feasible.

**Comment by sbaier1** [comment]
sounds like that would be the preferrable approach indeed moving forward 👍

**Comment by yongtang** [comment]
Added PR #746 for structured value support.

The structure of the value (in a complex query) is automatically probed in eager mode. 

In graph mode due to the way graph mode works, the spec has to be provided by user (through passing a `spec` arg).

I also moves the API from tfio.IODataset.from_prometheus to tfio.experimenta.IODataset.from_prometheus, as there are API changes. We will move back after API stabilize in (maybe) one or two releases.
