### ISSUE TITLE
Migrate LMDBDataset from tensorflow to tensorflow-io

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#73]
`LMDBDataset` is part of the `tf.contrib.data` and it naturally fits the tensorflow-io context. It makes sense to migrate LMDBDataset to tensorflow-io.

**Comment by terrytangyuan** [comment]
I can work on this one if nobody else is working on it.

**Comment by yongtang** [comment]
Thanks @terrytangyuan that would be great! Let me know if you encounter any issues with LMDBDataset.

**Comment by yongtang** [comment]
This issue is related to tensorflow/datasets#34

**Comment by terrytangyuan** [comment]
@yongtang the support for LMDB is now ready for review: https://github.com/tensorflow/io/pull/74
