### ISSUE TITLE
Support hdf5 reading by column

### ISSUE THREAD

**Issue by liangyy** [tensorflow/io#754]
Hi there, 

For some cases, samples are stored by columns in the hfd5 matrix. 
It will be really helpful if the API has option to read the matrix by column.

Thanks!

Yanyu

**Comment by yongtang** [comment]
Created a PR #795 to allow multiple dimension indexing/slicing, so that the following is possible:
```
tensor = tfio.IOTensor.from_hdf5(...)
tensor[:, 3, 2:8]
```

**Comment by yongtang** [comment]
This issue should have been resolved in #795.
