### ISSUE TITLE
Publish tfio 0.12 to tensorflow.org

### ISSUE THREAD

**Issue by MarkDaoust** [tensorflow/io#783]
Hi, I'm trying to execute the azure notebook for tensorflow.org

I get this error:

```
InternalError                             Traceback (most recent call last)
<ipython-input-5-0fe6a29d3aa3> in <module>
      1 pathname = 'az://{}/aztest'.format(account_name)
----> 2 tf.io.gfile.mkdir(pathname)
      3 
      4 filename = pathname + '/hello.txt'
      5 with tf.io.gfile.GFile(filename, mode='w') as w:

/tmpfs/src/tf_docs_env/lib/python3.5/site-packages/tensorflow_core/python/lib/io/file_io.py in create_dir_v2(path)
    423     errors.OpError: If the operation fails.
    424   """
--> 425   pywrap_tensorflow.CreateDir(compat.as_bytes(path))
    426 
    427 

InternalError: Failed to create directory az://devstoreaccount1/aztest (unknown_error - -598609368)
```
Any ideas?

**Comment by yongtang** [comment]
Thanks @MarkDaoust. I am running the azure notebook from colab.research.google.com:

https://colab.research.google.com/github/tensorflow/io/blob/master/docs/tutorials/azure.ipynb

and it seems to be fine. Are you running the notebook locally?

Wondering if there is any difference between the environment you run and the colab.research.google.com?

**Comment by yongtang** [comment]
One possible scenario is that I am pushing the button one by one on Google Colab. However, the line:
```
tf.io.gfile.mkdir(pathname)
```

will need the previous action `get_ipython().system_raw('azurite-blob -s &')` fully up. 

So if the notebook runs locally, the `azurite-blob -s &` may not be fully up yet.

Wondering if it makes a difference if you add a sleep (e..g, 5 sec) before `tf.io.gfile.mkdir(pathname)`?

**Comment by MarkDaoust** [comment]
Thanks for the tips. It looks like the publisher got silently tripped up on the `npm install` step.

**Comment by yongtang** [comment]
@MarkDaoust With tensorflow-io 0.12.0 released (see #813), I have updated docs in several places (PR #772 #819 #820), mostly to replace tensorflow-io-nightly with tensorflow-io. Can you take a look and see if those changes make sense. Maybe we could just push to tensorflow.org/io once the related PRs ( #772 #819 #820) are merged?

**Comment by MarkDaoust** [comment]
Sure. 

I've got the api-docs for 0.12 done. 

And those PRs are merged now. I'm try the tutorials update and report back.

**Comment by MarkDaoust** [comment]
Okay. 

postgresql went through, and I'm expecting prometheus to run this time. 

But I'm still having trouble with azure.

I haven't found a set of commands that works to install azurite-blob both in colab and our site-builder VMs.

I was going to give up and save the output into the azure notebook, but it doesn't seem to run in colab anymore. 

For me it's just hanging on the last code cell.  I'll get everything else up, LMK if you figure out what's going on with azure.ipynb

**Comment by yongtang** [comment]
Thanks @MarkDaoust for the update. I tried myself and it looks like indeed the last cell hangs. That was not the case the last time I tried (around a couple of weeks ago). I will take a deep look and see if I can fix this issue.

**Comment by yongtang** [comment]
@MarkDaoust I think I found out the issue. The issue seems to be that, when nodejs installs `azurite-blob`, the binary may not be exposed on `PATH` env. On Colab if I use:
```
get_ipython().system_raw('/content/node_modules/.bin/azurite-blob -s &')
```

Then it works through. 

Let me spend a little more time. I will try to see if I can find a generic way to resolve this issue by automatically figure out the nodejs path.

**Comment by yongtang** [comment]
@MarkDaoust I created a PR #827 to resolve the azure issue. Please take a look.

**Comment by yongtang** [comment]
@MarkDaoust Can you take a look at TOC on the left side? I see PostgreSQL is already up (https://www.tensorflow.org/io/tutorials/postgresql) though it is not showing up on the left side bar?

**Comment by MarkDaoust** [comment]
Okay, should be fixed now (if you force-reload the page).

**Comment by yongtang** [comment]
@MarkDaoust Nice! Thanks again for the great work 👍 🎉 🎆 !
