### ISSUE TITLE
Setup CI for Tensorflow I/O

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#8]
This issue tracks the efforts and progresses to setup CI for TensorFlow I/O. We plan to use Google CI so coordination with TensorFlow's CI might be needed.

**Comment by jsimsa** [comment]
@martinwicke seeing as the I/O modules will likely not require GPUs for tests, do you think it would make more sense for the project to use Travis CI?

**Comment by martinwicke** [comment]
I think that would be a fine choice, provided it can be built within the
time that Travis gives you.

**Comment by yongtang** [comment]
I created a PR with Travis CI added: #16

The configuration just uses the default Ubuntu 14.04 with bazel 0.17.2

So far it looks ok. I think we could use it for now, though at some point I think an additional test from Google CI that matches the TensorFlow repos build environment would be great (so that tensorflow-io always matches tensorflow binary build).

**Comment by yongtang** [comment]
This issue has been addressed in PR #16.
