### ISSUE TITLE
Update librdkafka to 1.0.0+

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#800]
This is an issue to update librdkafka to 1.0.0+. The biggest motivation for update is that our current version of librdkafka does not work correctly with OS X 10.13, due to https://github.com/Blizzard/node-rdkafka/issues/686#issue-499098109

Since we are publishing OS X 10.13 compatible wheels now, it is imperative to update librdkafka so that tensorflow-io on 10.13 works correctly.

Currently, there is another issue with librdkafka that is causing segmentation fault if we update, it is being tracked in https://github.com/edenhill/librdkafka/issues/2716

**Comment by jjedele** [comment]
Ahrg, just downloaded 8GB Xcode to figure out it has this issue 😓

**Comment by jjedele** [comment]
Documenting this here in case anyone else runs into the problem.

This is what the error will actually look like when you run into it:
```
In [2]: tf.load_op_library("libtensorflow_io.so")
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-2-cea886c59c24> in <module>
----> 1 tf.load_op_library("libtensorflow_io.so")

~/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py in load_op_library(library_filename)
     55     RuntimeError: when unable to load the library or get the python wrappers.
     56   """
---> 57   lib_handle = py_tf.TF_LoadLibrary(library_filename)
     58   try:
     59     wrappers = py_tf.GetPythonWrappers(py_tf.TF_GetOpList(lib_handle))

NotFoundError: dlopen(libtensorflow_io.so, 6): Symbol not found: _timespec_get
  Referenced from: libtensorflow_io.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in libtensorflow_io.so
```

The problem seems to be the Xcode version rather than the OS version. I'm running macOS 10.4.6. With Xcode 11.x I got above error. Downgrading to Xcode 10.3 seems to have fixed the problem for me. Old versions can be downloaded here: https://developer.apple.com/download/.

I had to following steps after downgrading:
```
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer # make sure right version is selected
sudo xcodebuild -license accept # accept license
bazel clean --expunge # clean bazel cache completely

# then build again
bazel build -s --verbose_failures //tensorflow_io/...
```

**Comment by yongtang** [comment]
@jjedele Sorry for the inconvenience. In order to move forward on https://github.com/edenhill/librdkafka/issues/2716 will need a simplified crash example. I will give another try today.

**Comment by yongtang** [comment]
I am not able to find out the reason yet, though if I comment out the line then librdkafka 1.4.0 will work without crash.
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_cgrp.c#L2727-L2733



Will play a little more, and update the librdkafka either way.

**Comment by yongtang** [comment]
@jjedele Added a PR #838 to upgrade librdkafka to 1.4.0-RC2.

**Comment by yongtang** [comment]
@jjedele The librdkafka has been upgraded to 1.4.0RC2 in #838.
