### ISSUE TITLE
JPEG 2000 (Lossless Only) support for DICOM

### ISSUE THREAD

**Issue by Dr-Gandalf** [tensorflow/io#809]
I've been working with this nice tools, but it can not decode all the images, the only common factor I see is the "JPEG 2000 (Lossless Only)" Transfer Syntax (1.2.840.10008.1.2.​4.​90).

does this tool have support for this compression method?

**Comment by yongtang** [comment]
@Dr-Gandalf Do you have a sample file and the simple code that can produce the issue?

**Comment by Dr-Gandalf** [comment]
yes but it is not anonymized.

**Comment by yongtang** [comment]
@Dr-Gandalf If the image is not available can you show the code if possible?

**Comment by Dr-Gandalf** [comment]
It can be reproduced using the notebook tutorial, I just uploaded the file an change the filename at the code 

https://www.tensorflow.org/io/tutorials/dicom

**Comment by yongtang** [comment]
@Dr-Gandalf Ah, I see it is related to dicom. For dicom my understanding is that DCMTK (the library we build with for dicom support) does not have open source support for JPEG2000 (only available in their commercial license which we are not using here). I think this is not a supported case.

**Comment by yongtang** [comment]
Given DCMTK does not have JPEG 2000 support out of the box, the alternate path would be to rely on GDCM. This could be quite an effort I think.

I will mark this feature request as contribution welcome for now. Also, if there is enough more interests from community we will try to make this happen.

**Comment by bhack** [comment]
An alternative could be https://github.com/DraconPern/fmjpeg2koj

**Comment by yongtang** [comment]
Add a PR #835 to bring fmjpeg2koj, which adds jpeg200 support for dicom

**Comment by yongtang** [comment]
@Dr-Gandalf  The latest tensorflow-io-nightly should consists of the jpeg 2000 support now. Can you give it a try?

**Comment by Dr-Gandalf** [comment]
I tried it works fine, thanks 

great job

**Comment by yongtang** [comment]
@Dr-Gandalf Thanks for the update. Think the issue could be closed.

**Comment by bhack** [comment]
Please give a star to https://github.com/DraconPern/fmjpeg2koj. We need to support upstream effort :wink:
