### ISSUE TITLE
Remove python2 specific code

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#824]
As tensorflow-io dropped the support for python 2, all python 2 specific code could be removed. For example, the following code that are common across almost all py files:

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
```

Mark this issue as `contribution welcome` and `good first issue`.

**Comment by gabrieldemarmiesse** [comment]
Hint from TF Addons: We used Pyugrade which was designed just for this :)

**Comment by yongtang** [comment]
Thanks @gabrieldemarmiesse! I added a PR #843 so that it is possible to run pyupgrade through bazel without installation. The command line below will sanitize file.py:
```
bazel run //tools/lint:lint -- pyupgrade -- file.py
```
