### ISSUE TITLE
Problems with linking libcurl ( third-party )

### ISSUE THREAD

**Issue by vnvo2409** [tensorflow/io#848]
Hello everyones.
I have built successfully tensorflow.io on Windows as I want to use the libcurl in third-party for my project. However, I can not find a way to link the build output to my code. Could someone give the instruction how to link ( Visual Studio or CLion )
Below is the content of the build output directory:
```
curl/
├── _obj/
│   ├── curl/
│        ├── ...obj
├── include/
│   ├── curl_config.h
├── curl.lib
└── curl.lib-2.params
```

**Comment by yongtang** [comment]
@vnvo2409 you can create a BUILD file and in `deps` part of the `cc_library` (or `cc_binary`) include `"@curl"` and that will automatically link against curl.

See the following for an example: https://github.com/tensorflow/io/blob/a970831f38e3bb394ecdf401fde5e58f02e288b5/tensorflow_io/core/BUILD#L70-L85

Let me know if you encounter any issues.

**Comment by vnvo2409** [comment]
So It mean that I can not using the build output to link with other build system such as Cmake ?

**Comment by yongtang** [comment]
@vnvo2409 In theory you still could link with different build systems. For any libraries if you have a header file, you can always link with other libraries (built by cmake, autoconfig, etc). Though it requires much manual effort.

Also, for many different reasons tensorflow stays with Bazel. It may not be exactly the best tool to use but it is there to stay (with all tensorflow related ecosystems). If you use other build systems you will likely face many issues that is hard to solve.

Another note about GCS and S3 support on TensorFlow: the code of GCS and S3 support on tensorflow is pretty much cross-platform (except for minor places that needs to change). In fact it may not need much development effort on C++ side (other than several fixes to compile on Windows).

However, the challenges was that Bazel's Windows support was not that great at the time when they were introduced in tensorflow. And later effort to make the build success on Windows faces with many issues. So the GSoC project by itself is to focus on bazel build on Windows and solve any issues.

(Note Bazel improved a lot over the past year so it could be easier to work with it on Windows. We also made some progress on curl and boringssl on Windows so things should be easier than  a year ago).

**Comment by vnvo2409** [comment]
Thank you. I will close the issue now. :smile:
