### ISSUE TITLE
Multiple HDF5 datasets

### ISSUE THREAD

**Issue by Abhipray** [tensorflow/io#867]
I am using `tfio.IODataset.from_hdf5` to load multiple HDF5 files at the same time. With version 0.12.0, I run into an issue with the two returned datasets pointing to the same underlying HDF5 file. This problem does not exist in 0.11.0. 

See this colab notebook for an example of two differently instantiated HDF5IODatasets pointing to the same underlying data https://colab.research.google.com/drive/1uv8OKu5eHDNyyUr31sJci-ucTSb-l8WQ

**Comment by yongtang** [comment]
@Abhipray Thanks for the report. Will take a look.

**Comment by albangabillon** [comment]
I noticed it too

**Comment by yongtang** [comment]
@Abhipray @albangabillon I tried with the latest nightly, believe the issue has been fixed in #899, But feel free to reopen if the issue persists.

**Comment by Abhipray** [comment]
You are right, it's been fixed. Thanks!
