### ISSUE TITLE
bazel build //tensorflow_io/... fails in debian OS with pylint 2.4.4 not found

### ISSUE THREAD

**Issue by marioecd** [tensorflow/io#909]
I am trying to build tfio in a debian OS VM.
bazel build -s --verbose_failures //tensorflow_io/...

I get error:
ERROR: no such package '@lint_dependencies//': pip_import failed: Collecting pylint==2.4.4 (from -r /home/marioecd/io/tools/lint/requirements.txt (line 1))

I also see a black version problem:
Collecting black==19.10b0 (from -r /home/marioecd/io/tools/lint/requirements.txt (line 2))
 (  Could not find a version that satisfies the requirement black==19.10b0

$ pip --version
pip 20.0.2 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
$ bazel --version
bazel 3.0.0
$ python3 --version
Python 3.5.3
$ python --version
Python 2.7.13

I've been following the steps in https://github.com/tensorflow/io for ubuntu. Anyone knows what's wrong with the pip_command pylint 2.4.4 issue?

**Comment by yongtang** [comment]
@marioecd Created a PR #911 for the fix. Once it is merged, you can upgrade the master and this will resolve your issue.
