### ISSUE TITLE
gcs_config_op_kernels.cc breaking bazel build //tensorflow_io/...

### ISSUE THREAD

**Issue by marioecd** [tensorflow/io#912]
I just got my first bazel build run of tensorflow IO, and found a compilation error. I wonder if this is something that needs fixing and other people are seeing too, or perhaps I am not getting a stable version? I am getting tfio from:

"git clone https://github.com/tensorflow/io.git"
then start the ubuntu setup and run the build command:

$ bazel build -s --verbose_failures //tensorflow_io/...

I get compilation error:
 C++ compilation of rule '//tensorflow_io/gcs:gcs_config_ops' failed (Exit 1): gcc failed: error executing command 

----------------------

Use --sandbox_debug to see verbose messages from the sandbox
tensorflow_io/gcs/kernels/gcs_config_op_kernels.cc:162:12: error: expected ';' at end of member declaration
     string current_token_ TF_GUARDED_BY(mu_);
            ^~~~~~~~~~~~~~
tensorflow_io/gcs/kernels/gcs_config_op_kernels.cc:162:41: error: 'mu_' is not a type
     string current_token_ TF_GUARDED_BY(mu_);
                                         ^~~
tensorflow_io/gcs/kernels/gcs_config_op_kernels.cc:162:44: error: ISO C++ forbids declaration of 'TF_GUARDED_BY' with no type [-fpermissive]
     string current_token_ TF_GUARDED_BY(mu_);
                                            ^
tensorflow_io/gcs/kernels/gcs_config_op_kernels.cc:163:12: error: expected ';' at end of member declaration
     uint64 expiration_timestamp_sec_ TF_GUARDED_BY(mu_) = 0;
            ^~~~~~~~~~~~~~~~~~~~~~~~~
tensorflow_io/gcs/kernels/gcs_config_op_kernels.cc:163:52: error: 'mu_' is not a type
     uint64 expiration_timestamp_sec_ TF_GUARDED_BY(mu_) = 0;
                                                    ^~~
tensorflow_io/gcs/kernels/gcs_config_op_kernels.cc:163:59: error: ISO C++ forbids declaration of 'TF_GUARDED_BY' with no type [-fpermissive]
     uint64 expiration_timestamp_sec_ TF_GUARDED_BY(mu_) = 0;
                                                           ^
tensorflow_io/gcs/kernels/gcs_config_op_kernels.cc:163:38: error: 'int tensorflow::{anonymous}::GcsCredentialsOpKernel::ConstantAuthProvider::TF_GUARDED_BY(int)' cannot be overloaded
     uint64 expiration_timestamp_sec_ TF_GUARDED_BY(mu_) = 0;
                                      ^~~~~~~~~~~~~
tensorflow_io/gcs/kernels/gcs_config_op_kernels.cc:162:27: error: with 'int tensorflow::{anonymous}::GcsCredentialsOpKernel::ConstantAuthProvider::TF_GUARDED_BY(int)'
     string current_token_ TF_GUARDED_BY(mu_);
                           ^~~~~~~~~~~~~
tensorflow_io/gcs/kernels/gcs_config_op_kernels.cc: In member function 'virtual void tensorflow::{anonymous}::GcsCredentialsOpKernel::Compute(tensorflow::OpKernelContext*)':

**Comment by yongtang** [comment]
@marioecd This is very likely caused by the mismatch of TF versions. Between TF 2.2.0rc2 and TF 2.2.0rc3, TensorFlow changed some of the C++ APIs. For that reason if you are installing 2.2.0rc2 or lower, you will encounter the error.

For the master branch of tensorflow/io, you will need TF 2.2.0rc3 (or higher) installed.

**Comment by marioecd** [comment]
Yeah, changed to a TF 2.2 image and the error went away. Thanks!
