### ISSUE TITLE
including a nightly tensorflow version in tensorflow-io

### ISSUE THREAD

**Issue by marioecd** [tensorflow/io#916]
I am trying to build tensorflow-io while picking up some new changes from the tensorflow lib dependency that are only available in the tf-nightly version of tensorflow. Is it possible to build tensorflow-io using tf-nightly as a dependency instead of an official version like 2.2.0rc3? I don't seem to pick up the latest bits when I try pip installing that tensorflow and then doing a tensorflow-io build. Some methods do not appear yet to the compiler.

**Comment by yongtang** [comment]
@marioecd You could re-build tensorflow-io with tf-nightly locally.

The `./configure.sh` will check the installed version of tensorflow, and incase already installed, it will skip the pinned version install.

So, in your case:
1. Uninstall tensorflow (`sudo pip uninstall -y tensorflow`)
2. Install tf-nightly (`sudo pip install tf-nightly`)
3. Configure with `./configure.sh` (notice no new install in this step)
4. Build like before.

**Comment by marioecd** [comment]
Thanks. So, I tried that, but now I get numerous new ubiquitous compilation errors like the ones below. I assume that's because of some version miss-match?

Errors like:
include/absl/strings/internal/ostringstream.h:26:1: error: 'ABSL_NAMESPACE_BEGIN' does not name a type
 ABSL_NAMESPACE_BEGIN

include/absl/numeric/int128.h:1019:8: error: 'int128' does not name a type; did you mean 'uint128'

**Comment by yongtang** [comment]
@marioecd There were lots of C++ API changes in TensorFlow recently so moving from 2.2 to nightly will not be easier.

Since tensorflow/io only release based on formal releases of TensorFlow, we can not bump our pypi package immediately.

I can create a `nightly` branch and keep up with the currently TF nightly. You can work based on `nightly` repo branch then.

On another side notes, what kind of code (file system, data set, or individual ops?) are you looking to add? That may help to see if there are alternative paths.

**Comment by marioecd** [comment]
So I created a virtual gcs_file_system method, [ParseGcsPath](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/cloud/gcs_file_system.h).

In tensorflow-io I want to add a class that inherits gcs_file_system's ParseGcsPath. A new file system will be registered (REGISTER_FILE_SYSTEM) with my new class and a new scheme. My new class will override ParseGcsPath and let gcs_file_system continue to do everything under the hood when my new file system scheme is referenced.

**Comment by marioecd** [comment]
The issue is that the method ParseGcsPath is made virtual in a release from:
tf-nightly==2.2.0.dev20200417

**Comment by yongtang** [comment]
@marioecd I have created the `nightly` branch (see https://github.com/tensorflow/io/tree/nightly) with all build break fixed. You can take a look and base your code on top of `nightly` branch for now.

**Comment by marioecd** [comment]
Woohoo! Thanks! I'll try that one.

**Comment by marioecd** [comment]
That worked very well! I got my local target to build.
