### ISSUE TITLE
Parquet documentation refers to json

### ISSUE THREAD

**Issue by chaaland** [tensorflow/io#921]
The comments for `from_parquet` refer to json files in a couple places. Looks like a copy paste error: https://github.com/tensorflow/io/blob/4643b2af7fb22d508eba10b4e6e7144c362eedaa/tensorflow_io/core/python/ops/io_dataset.py#L260

**Comment by terrytangyuan** [comment]
Thanks. I submitted a PR that corrects this in: https://github.com/tensorflow/io/pull/923
