### ISSUE TITLE
ArrowFeatherDataset example broken

### ISSUE THREAD

**Issue by chaaland** [tensorflow/io#925]
Going off of [this medium blog](https://medium.com/tensorflow/tensorflow-with-apache-arrow-datasets-cdbcfe80a59f) to create an ArrowFeatherDataset, I get the following error

`tensorflow.python.framework.errors_impl_InternalError: Type error: Arrow type mismatch: expected dtype=9, but got dtype=3`

The code I used (taken almost entirely from the linked blog) is below with pandas==1.03, tensorflow==2.1, tensorflow_io==0.12, pyarrow==0.15.1

```python
import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow_io.arrow as arrow_io
import pyarrow as pa
from pyarrow.feather import write_feather

data = {'label': np.random.binomial(1, 0.5,10)}
data['x0'] = np.random.randn(10) + 5 * data['label']
data['x1'] = np.random.randn(10) + 5 * data['label']
df = pd.DataFrame(data)
# Write the Pandas DataFrame to a Feather file
write_feather(df, "df.feather")

# Create the dataset with one or more filenames
ds = arrow_io.ArrowFeatherDataset(
  ["df.feather"],
  columns=(0,1,2),
  output_types=(tf.int64, tf.float64, tf.float64),
  output_shapes=([], [], []),
)

# Iterate over each row of each file
for record in ds:
  print(record)
```

I can get this example to work using by instead doing the following
```python
schema = pa.feather.read_table("df.feather").schema
ds = arrow_io.ArrowFeatherDataSet.from_schema("df.feather", schema)
```
There doesn't seem to be a way to get the feather schema without first reading the entire file into memory so I'd prefer the first approach but I cannot get this example to run successfully.

**Comment by BryanCutler** [comment]
Hi @chaaland , it looks like there is a dtype mixup between what schema is in the feather file and what is specified in `output_types=(tf.int64, tf.float64, tf.float64)`.  The error indicates that it was expecting an `int64` but got `int32`, which could mean somehow your label column is ending up as an `int32`.  Could you post the output of:

```python
from pyarrow.feather import read_table
print(read_table("df.feather").schema)
```
If you have a pandas DataFrame, you could automatically determine the `output_types` needed like this:

```python
from tensorflow_io.arrow.python.ops.arrow_dataset_ops import arrow_schema_to_tensor_types
schema = pa.Schema.from_pandas(df)
output_types, output_shapes = arrow_schema_to_tensor_types(schema)
```

**Comment by chaaland** [comment]
Running the above on Windows10 I do indeed see `label: int32`. Running on MacOS the example runs without error though
