### ISSUE TITLE
bazel run //tools/lint:check is broken in Docker

### ISSUE THREAD

**Issue by vlasenkoalexey** [tensorflow/io#937]
It was broken by
https://github.com/tensorflow/io/commit/fb75864710d0669b9e18e0f5565a1cada78a1b8c
I had to revert llvm_version to 9.x because 10.x does not support Ubuntu16:

https://github.com/grailbio/bazel-toolchain/blob/edd07e96a2ecaa131af9234d6582875d980c0ac7/toolchain/internal/llvm_distributions.bzl#L91

**Comment by yongtang** [comment]
@vlasenkoalexey Created a PR #938 to downgrade.
