### ISSUE TITLE
tfio fails to build with: "no such package '@speexdsp//'"

### ISSUE THREAD

**Issue by marioecd** [tensorflow/io#943]
tensorflow-io nightly branch fails with error: no such package '@speexdsp//'

repro:
$ git clone https://github.com/tensorflow/io.git
then build as instructed in README for ubuntu
... install bazel... and build
$ bazel build -s --verbose_failures //tensorflow_io/...

**Fails with error:**
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/downloads.xiph.org/releases/speex/speexdsp-1.2.0.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://downloads.xiph.org/releases/speex/speexdsp-1.2.0.tar.gz failed: class java.io.IOException connect timed out
ERROR: An error occurred during the fetch of repository 'speexdsp':
   java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/downloads.xiph.org/releases/speex/speexdsp-1.2.0.tar.gz, https://downloads.xiph.org/releases/speex/speexdsp-1.2.0.tar.gz] to /6e155c91bb8cc86ad01c234fda3d7c71/external/speexdsp/speexdsp-1.2.0.tar.gz: connect timed out
ERROR: /home/$USER/io/tensorflow_io/core/BUILD:211:1: //tensorflow_io/core:audio_video_ops depends on @speexdsp//:speexdsp in repository @speexdsp which failed to fetch. no such package '@speexdsp//': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/downloads.xiph.org/releases/speex/speexdsp-1.2.0.tar.gz, https://downloads.xiph.org/releases/speex/speexdsp-1.2.0.tar.gz] to /home/$USER/.cache/bazel/_bazel_$USER/6e155c91bb8cc86ad01c234fda3d7c71/external/speexdsp/speexdsp-1.2.0.tar.gz: connect timed out
ERROR: Analysis of target '//tensorflow_io/bigquery:bigquery' failed; build aborted: no such package '@speexdsp//': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/downloads.xiph.org/releases/speex/speexdsp-1.2.0.tar.gz, https://downloads.xiph.org/releases/speex/speexdsp-1.2.0.tar.gz] to /home/$USER/.cache/bazel/_bazel_$USER/6e155c91bb8cc86ad01c234fda3d7c71/external/speexdsp/speexdsp-1.2.0.tar.gz: connect timed out

**Comment by yongtang** [comment]
@marioecd Created a PR #944 to resolve the issue. Once merged will cherry-pick into nightly branch.

**Comment by yongtang** [comment]
@marioecd The issue have been fixed in #944 now. I will close this one, but let me know if there are any other issues.
