### ISSUE TITLE
test_gcs_config_ops.py fails on: pylint pyupgrade black

### ISSUE THREAD

**Issue by marioecd** [tensorflow/io#946]
As part of PR checks there is a lint error on test_gcs_config_ops.py

repro:
$ bazel run -s --verbose_failures //tools/lint:lint -- bazel pylint pyupgrade black

lint tests/test_gcs_config_ops.py
************* Module tests.test_gcs_config_ops
tests/test_gcs_config_ops.py:21:0: C0411: third party import "import tensorflow as tf" should be placed before "import pytest" (wrong-import-order)
tests/test_gcs_config_ops.py:23:0: C0411: third party import "from tensorflow.python.platform import test" should be placed before "import pytest" (wrong-import-order)

**Comment by yongtang** [comment]
@marioecd I run the same command but didn't face the same issue.

One potential discrepancy I can think of, is the version of pylint? In my local machine I don't have pylint installed. Instead, the run relies on internal pylint configured through bazel 

https://github.com/tensorflow/io/blob/master/tools/lint/requirements.txt

If your local machine have pylint installed and it is not version 2.4.4, then that could trigger discrepancies.

**Comment by marioecd** [comment]
I don't seem to have pylint installed here either. Though finally running lint:lint showed what I needed to change to avoid a pylint failure in the PR. So that's at least solved. Thanks.
