### ISSUE TITLE
[kafka-io] - KafkaStreamIODataset eof and timeout behavior

### ISSUE THREAD

**Issue by nmatare** [tensorflow/io#947]
The first implementation of KafkaDataset (kafka_kernels_deprecated.cc) allowed the user to specify `eof` and `timeout` which blocked the calling thread if no data was present. The new `StreamIODataset` Kafka dataset ("A StreamIODataset where data generation may last forever and/or non-repeatable") immediately exits if there isn't any data, and doesn't allow for a timeout parameter. 

The first behavior allowed us to continuously poll from the Kafka cluster until data arrived to action the model. This prevented us from having to rebuild the iterator if there was a momentary lapse in arriving data. (Unfortunately, `timeout` didn't work in that case) Would it make sense to combine the behaviors?

```sh
bash -x -e tests/test_kafka/kafka_test.sh start kafka
```

The StreamIODataset case:
```python
import tensorflow_io as tfio
import tensorflow_io.kafka as kafka_io
from kafka import KafkaProducer

GROUP_ID = 'test_group'
SERVERS = 'localhost:9092'
TOPIC = 'testing_topic'
PARTITION = 0

producer = KafkaProducer(bootstrap_servers=[SERVERS])

for letter in ['A', 'B', 'C', 'D', 'E']:
  producer.send(TOPIC, letter.encode('utf-8'))

# A StreamIODataset where data generation may last forever and/or non-repeatable.
stream_ds = tfio.IODataset.stream().from_kafka(
    topic=TOPIC,
    offset=0,
    partition=PARTITION,
    stop=-1,
    servers=SERVERS,
    configuration=['auto.offset.reset=earliest', 'enable.partition.eof=false'],
)

for data in stream_ds:
  print(data.message)

```
The above immediately exits with no EOF parameter. We have to rebuild the entire iterator to start reading data again...
https://github.com/tensorflow/io/blob/f71ef1d3b56d665561fe8b10e95ca32ed46870e5/tensorflow_io/core/kernels/kafka_kernels.cc#L201

The KafkaDataset case:
```python
deprecated_ds = kafka_io.KafkaDataset(
    topics=TOPIC,
    servers=SERVERS,
    group=GROUP_ID,
    config_global=['auto.offset.reset=earliest'],
    message_key=False,
    eof=False,   # set here to block
    timeout=10,
)

# WARNING this will forever block, (timeout has no effect here)
for data in deprecated_ds:
  print(data)
```

**Comment by kvignesh1420** [comment]
@nmatare I tried to reproduce the stream_ds snippet which you have pasted and got the output as follows:

```ipython
In [1]: import tensorflow_io as tfio
   ...: import tensorflow_io.kafka as kafka_io
   ...: from kafka import KafkaProducer
   ...:
   ...: GROUP_ID = 'test_group'
   ...: SERVERS = 'localhost:9092'
   ...: TOPIC = 'testing_topic'
   ...: PARTITION = 0
   ...:
   ...: producer = KafkaProducer(bootstrap_servers=[SERVERS])
   ...:
   ...: for letter in ['A', 'B', 'C', 'D', 'E']:
   ...:   producer.send(TOPIC, letter.encode('utf-8'))
   ...:
   ...: # A StreamIODataset where data generation may last forever and/or non-repeatable.
   ...: stream_ds = tfio.IODataset.stream().from_kafka(
   ...:     topic=TOPIC,
   ...:     offset=0,
   ...:     partition=PARTITION,
   ...:     stop=-1,
   ...:     servers=SERVERS,
   ...:     configuration=['auto.offset.reset=earliest', 'enable.partition.eof=false'],
   ...: )
   ...:
   ...: for data in stream_ds:
   ...:   print(data.message)
   ...:
2020-07-19 03:20:05.792924: I tensorflow_io/core/kernels/cpu_check.cc:128] Your CPU supports instructions that this TensorFlow IO binary was not compiled to use: SSE4.2 AVX AVX2 FMA
2020-07-19 03:20:06.155197: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-07-19 03:20:06.172511: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa19df943d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-19 03:20:06.172533: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-19 03:20:06.174720: I tensorflow_io/core/kernels/kafka_kernels.cc:107] Kafka configuration: auto.offset.reset=earliest
2020-07-19 03:20:06.174745: I tensorflow_io/core/kernels/kafka_kernels.cc:107] Kafka configuration: enable.partition.eof=false
2020-07-19 03:20:06.174756: I tensorflow_io/core/kernels/kafka_kernels.cc:107] Kafka configuration: bootstrap.servers=localhost:9092
2020-07-19 03:20:06.273744: I tensorflow_io/core/kernels/kafka_kernels.cc:177] Kafka stream starts with current offset: 0
2020-07-19 03:20:06.314708: E tensorflow_io/core/kernels/kafka_kernels.cc:198] EOF Message: Broker: No more messages
tf.Tensor(b'A', shape=(), dtype=string)
tf.Tensor(b'B', shape=(), dtype=string)
tf.Tensor(b'C', shape=(), dtype=string)
tf.Tensor(b'D', shape=(), dtype=string)
tf.Tensor(b'E', shape=(), dtype=string)
2020-07-19 03:20:06.316592: I tensorflow_io/core/kernels/kafka_kernels.cc:177] Kafka stream starts with current offset: 0

In [2]:
```

So as per your message, you don't see the tensor output's after the `EOF Message: Broker: No more messages`?

**Comment by nmatare** [comment]
Yup, the above is the expected output. But now if you run the next code block you'll notice that the `kafka_io.KafkaDataset` blocks until new data arrives, which is different behavior from the code snippet from above.

Given that a Kafka dataset will most likely be used during inference/production, I think that the behavior of the latter is more intuitive. We don't want to exit immediately when there is no data: we'd rather wait some period of time (perhaps `timeout` seconds -- but this parameter doesn't work as expected) for new data to arrive before exiting.

If we use the first implementation (`tfio.IODataset.stream().from_kafka`), we have to detect when new data arrives and rebuild the iterator each time there's a lapse in arriving data.

**Comment by kvignesh1420** [comment]
@nmatare the timeout functionality after oef is now available in the nightly build. 
You can use the following snippet to prepare the dataset:

```python
dataset = tfio.experimental.streaming.KafkaGroupIODataset(
            topics=[TOPIC],
            group_id=GROUP_ID,
            servers=SERVERS,
            stream_timeout=1000, # in milliseconds
            configuration=["session.timeout.ms=7000", "max.poll.interval.ms=8000"],
        )
```

Would be great if you can try this feature and provide the feedback.

**Comment by nmatare** [comment]
Thanks for the PR, this is great! Tried out the functionality:

---
Confused between on `message_timeout` vs `stream_timeout`. What is the difference between the two? Seeing the docs:

_"However, since we set the `stream_timeout` value to `15000` milliseconds, the dataset will wait for any new messages that might be added to the topic for that duration. The topics will be polled at `message_timeout` intervals."_

Aren't they one in the same? If we're polling the topic(s) for `timeout` amount of time, should we just timeout if no new message arrive from any of the topics?

A reference: 
https://docs.confluent.io/current/clients/confluent-kafka-python/#confluent_kafka.Consumer

See `consume` method:
```
timeout (float) – Maximum time to block waiting for message, event or callback (default: infinite (-1)). (Seconds)
```

Playing around with the KafkaGroupIODataset vs the legacy implementation, I'm finding this version much harder to implement. For the single topic setting, things are about par but once I start messing around with multiple topics with varying arrival rates it gets pretty difficult to track down what parameters are responsible for delays in data retrieval (consumer group re-balancing/leader election/message_timeout, stream_timeout, session.timeout, etc). Will try to gen-up some testcases for comparison.

**Comment by kvignesh1420** [comment]
@nmatare thanks for trying it out. The `stream_timeout` parameter in `KafkaGroupIODataset` is analogous to the `timeout` parameter in confluent Kafka consumer that you have mentioned. 

The `message_timeout` value is the duration that the consumer will wait before polling for new messages. However, if we receive a new message before the `message_timeout` interval finishes, the consumer doesn't resume the consumption but it will wait until the `message_timeout` interval has finished. Thus, if we want to block indefinitely until a new message arrives, we cannot do it with `message_timeout` alone. This is when the `stream_timeout` comes in, where we can set the value to a very high timeout (i.e, block indefinitely) and keep on polling for new messages at `message_timeout` intervals.

If this is causing confusion, I can expose only the `stream_timeout` to the users as it will be more intuitive.
Additional tests will be great!

**Comment by kvignesh1420** [comment]
@nmatare After playing around with a test kafka cluster, I felt it was necessary to expose the `mesage_poll_timeout` (previously `message_timeout`) to the users as a single hard-coded timeout value might not be suitable for all cluster configs. Also, there was an issue with the blocking logic where the new messages were not being consumed for higher `stream_timeout` values. This has been fixed now.
PR: https://github.com/tensorflow/io/pull/1120

**Comment by nmatare** [comment]
@kvignesh1420 

I gave this a whirl and it works great! The API is much more intuitive than previously. I found that playing around with `message_poll_timeout` and `stream_timeout` to make much sense for multiple topic/partition configurations. Thanks for taking the time to put this PR together!

**Comment by kvignesh1420** [comment]
@nmatare thanks for trying it out and providing the feedback. 

Also, If you are interested in exploring a Kafka dataset for **online learning**, you can explore the `tfio.experimental.streaming.KafkaBatchIODataset` API. It is similar to the `KafkaGroupIODataset` API but enables you to train on incoming streaming data perpetually.

Example:
```python
import tensorflow_io as tfio
dataset = tfio.experimental.streaming.KafkaBatchIODataset(
                        topics=["topic1"],
                        group_id="cg",
                        servers="localhost:9092"
                    )
for mini_batch in dataset:
        mini_batch = mini_batch.map(
                lambda m, k: (tf.cast(m, tf.float32), tf.cast(k, tf.float32)))
        model.fit(mini_batch, epochs=10)
```

the `mini_batch` itself is a `tf.data.Dataset` which can be passed to a `tf.keras` model for training. So you train on incoming data for 10 epochs (in this case) and then move on to new data and never return to the old data again.

**Comment by nmatare** [comment]
Wonderful, that looks extremely helpful. Will play around with it in the future.

Closing this. Raised https://github.com/tensorflow/io/issues/1133 to address a callback bug.
