### ISSUE TITLE
DICOM decoder issues with @tf.function

### ISSUE THREAD

**Issue by jpambrun** [tensorflow/io#948]
I get odd error when using the DICOM image loader with J2K files:
```
E: can't change to unencapsulated representation for pixel data
E: can't determine 'PhotometricInterpretation' of decompressed image
E: mandatory attribute 'PhotometricInterpretation' is missing or can't be determined
E: can't change to unencapsulated representation for pixel data
E: can't determine 'PhotometricInterpretation' of decompressed image
E: mandatory attribute 'PhotometricInterpretation' is missing or can't be determined
```

Here is  a minimum working example with some image I found in this repo:
``` python
import tensorflow_io as tfio
import tensorflow as tf

def preprocess(dcm_content):
    image = tfio.image.decode_dicom_image(dcm_content, dtype=tf.float32)
    return image

dataset = (
    tf.data.Dataset.list_files("TOSHIBA_J2K_OpenJPEGv2Regression.dcm") # breaks
    # tf.data.Dataset.list_files("MR-MONO2-16-knee.dcm") # works
    .repeat()
    .map(tf.io.read_file)
    .map(preprocess, num_parallel_calls=1)
    .take(1000)
)
for i, item in enumerate(dataset):
    if i % 100 == 0:
        print(tf.shape(item), i)
```

I am running in docker:
``` Dockerfile
FROM tensorflow/tensorflow:2.1.0-py3
RUN pip install tensorflow-io

RUN mkdir /tmp/build
WORKDIR /tmp/build

COPY . .
RUN python test.py
```

**Comment by yongtang** [comment]
@jpambrun JPEG2000 support for DICOM was added in #835 and merged to master. However, it is not yet part of the release. Our next version v0.13.0 will include this commit.

The release of v0.13.0 is imminent. We are just waiting for the final version of TF 2.2.0. In the meantime, you can use tensorflow-io-nightly.

You can give it a try with the following (replace `tensorflow-io` to `tensorflow-io-nightly`):
```
FROM tensorflow/tensorflow:2.1.0-py3
RUN pip install tensorflow-io-nightly

RUN mkdir /tmp/build
WORKDIR /tmp/build

COPY . .
RUN python test.py
```

I will close this issue for now. But feel free to re-open or create a new issue if you encounter any other issues.

**Comment by yongtang** [comment]
@jpambrun Actually tensorflow 2.2.0 final version was just released yesterday. Now we are in the process of release tensorflow-io v0.13.0 (tracking in #952).

**Comment by jpambrun** [comment]
That's for looking into this. I was actually using a modified version of the original source for this op (`jpambrun/gradient_decode_dicom`) and when I tried to reproduce on tensorflow-io I got the expected error (`can't change to unencapsulated representation for pixel data..`) but didn't notice jpeg2000 wasn't enabled. Hence the confusion.

However, I continued debugging and have identified the failure conditions more precisely. In order to reproduce I need to use `decode_dicom_data` before `decode_dicom_image` AND wrap with `@tf.function`. Note that it fails intermittently. Just now it failed 5 out of 10 tries.

Dockerfile:
```Dockerfile 
FROM tensorflow/tensorflow:2.1.0-py3
RUN pip install tensorflow-io-nightly

RUN mkdir /tmp/build
WORKDIR /tmp/build
RUN python test.py
```

test.py:
``` python
import tensorflow_io as tfio
import tensorflow as tf

@tf.function
def preprocess(dcm_content):
    tags = tfio.image.decode_dicom_data(
        dcm_content, tags=[tfio.image.dicom_tags.PatientsName]
    )
    tf.print(tags)
    image = tfio.image.decode_dicom_image(dcm_content, dtype=tf.float32)
    return image

dataset = (
    tf.data.Dataset.list_files("TOSHIBA_J2K_OpenJPEGv2Regression.dcm")
    .repeat()
    .map(tf.io.read_file)
    .map(preprocess, num_parallel_calls=8)
    .take(200)
)
for i, item in enumerate(dataset):
    if i % 100 == 0:
        print(tf.shape(item), i)
```

The error is the same as before when it fails 50% of the time:
```
["Anonimo"]
["Anonimo"]
E["Anonimo"]
: can't change to unencapsulated representation for pixel data
E: can't determine 'PhotometricInterpretation' of decompressed image
E: mandatory attribute 'PhotometricInterpretation' is missing or can't be determined
["Anonimo"]
["Anonimo"]
E: can't change to unencapsulated representation for pixel data
E: can't determine 'PhotometricInterpretation' of decompressed image
E: mandatory attribute 'PhotometricInterpretation' is missing or can't be determined
E: can't change to unencapsulated representation for pixel data
E: can't determine 'PhotometricInterpretation' of decompressed image
E: mandatory attribute 'PhotometricInterpretation' is missing or can't be determined
E: can't change to unencapsulated representation for pixel data
E: can't determine 'PhotometricInterpretation' of decompressed image
E: mandatory attribute 'PhotometricInterpretation' is missing or can't be determined
E: can't change to unencapsulated representation for pixel data
E: can't change to unencapsulated representation for pixel data
```

**Comment by jpambrun** [comment]
I just tried with 2.2.0 by using `FROM tensorflow/tensorflow:2.2.0` above and it failed consistently  10 times in a row with `@tf.function`, but works fine without it. 

I am struggling to understand why/how `@tf.function` is causing dcmtk to crap out.

**Comment by yongtang** [comment]
The library we use for jpeg2k in dicom, https://github.com/DraconPern/fmjpeg2koj/tree/master/include/fmjpeg2k

is different from DCMTK used in other languages. In fmjpeg2k the cleanup is not safe until program exit. That was the reason for the strange behavior.

Created a PR #955.

**Comment by yongtang** [comment]
@jpambrun The latest nightly should have the issue fixed now. Please let me know if the issue persists.

**Comment by jpambrun** [comment]
Yes. That seemed to have fixed it. I debugged for several hours and figured that init/cleanup was likely the issue, but I would never have been able to come up with the solution. I am very grateful.
