### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#97]
Python 3.7 is a supported version in TF 1.13.0 (rc2), so we should support 3.7 as well (already saw lots of interests in TF about 3.7).

**Comment by yongtang** [comment]
Tried to repackage binary with python 3.7 (on Ubuntu 14.04). When running on Ubuntu 18.04 could see the following error:
```
/usr/local/lib/python3.7/dist-packages/tensorflow_io/image/python/ops/_image_ops.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumES3_
```

A likely cause I guess is that Python 3.7 version of tensorflow is compiled with some flags in gcc (or a different version of gcc).

**Comment by wookayin** [comment]
I ran into this issue. In my environments was:

- python 3.6 (anaconda)
- Ubuntu 16.04
- g++

where I manually built TF 1.13.0-rc2 from source.

When I was using TF 1.13.0-rc2 from `pypi`, the error did not happen.

**Comment by yongtang** [comment]
I haven't tried myself but I guess it may have something to do with the api compatibility. Maybe you could give `-copt="-D_GLIBCXX_USE_CXX11_ABI=0"` a try when building with bazel for both tensorflow and tensorflow-io?

**Comment by yongtang** [comment]
Python 3.7 has been added in PR #193 and tensorflow-io-nightly. it will show up in the next version of release (v0.6.0).
