### ISSUE TITLE
InvalidArgumentError: unable to initialize encoder [Op:IO>AudioEncodeAAC]

### ISSUE THREAD

**Issue by avnx** [tensorflow/io#973]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS (Bionic Beaver)
- TensorFlow installed from (source or binary): https://github.com/horovod/horovod/blob/master/Dockerfile.gpu (changed TENSORFLOW_VERSION=2.2.0)
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: used cpu

`python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`:
v2.2.0-rc4-8-g2b96f3662b 2.2.0

### It was working with 2.2.0-rc3.

```
audio_path = 'path/to/mp3/file.mp3'
audio_data = tf.io.read_file(audio_path)
audio_mp3_decoded = audio_ops.decode_mp3(audio_data)
audio_ops.encode_aac(audio_mp3_decoded, 8000)
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-9-6cd6b5e605d3> in <module>
----> 1 audio_ops.encode_aac(audio_mp3, 8000)

/usr/local/lib/python3.6/dist-packages/tensorflow_io/core/python/ops/audio_ops.py in encode_aac(input, rate, name)
    212         except NotImplementedError:
    213             pass
--> 214     return core_ops.io_audio_encode_aac(input, rate, name=name)
    215 
    216 

<string> in io_audio_encode_aac(input, rate, name)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6651   message = e.message + (" name: " + name if name is not None else "")
   6652   # pylint: disable=protected-access
-> 6653   six.raise_from(core._status_to_exception(e.code, message), None)
   6654   # pylint: enable=protected-access
   6655 

/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: unable to initialize encoder [Op:IO>AudioEncodeAAC]
```

**Comment by yongtang** [comment]
@avnx Can you find out the version of tensorflow-io with `pip freeze`?

**Comment by yongtang** [comment]
@avnx I also notice that you mentioned "after update to tf2.2.0", wondering if you are using `tensorflow-io-nightly`, or `tensorflow-io`?

**Comment by avnx** [comment]
> @avnx I also notice that you mentioned "after update to tf2.2.0", wondering if you are using `tensorflow-io-nightly`, or `tensorflow-io`?

**Comment by avnx** [comment]
> @avnx Can you find out the version of tensorflow-io with `pip freeze`?

tensorflow-io==0.13.0

> @avnx I also notice that you mentioned "after update to tf2.2.0", wondering if you are using tensorflow-io-nightly, or tensorflow-io?

How can I check that? 
When I check version of tfio it prints: 
```
>>> tfio.__version__
'0.13.0'
```

**Comment by yongtang** [comment]
@avnx That should be fine. Would it be possible to upload the `file.mp3` file that was used in your setup, so that I can take a look?

**Comment by avnx** [comment]
> @avnx That should be fine. Would it be possible to upload the `file.mp3` file that was used in your setup, so that I can take a look?

Now that's an interesting case.
I installed ffmpeg on machine via "apt install ffmpeg" and encode_aac starts working.
But encode_mp3 stopped working. 
In particular:
``` 
>>>audio_path = 'path/to/mp3/file.mp3'
>>>audio_data = tf.io.read_file(audio_path)
>>>audio_mp3 = audio_ops.decode_mp3(audio_data)
>>> audio_ops.encode_mp3(audio_mp3, 8000)
python: vbrquantize.c:783: short_block_constrain: Assertion `vbrsf[sfb] >= vbrsfmin[sfb]' failed.
Aborted (core dumped)```

Now I've remembered that I faced that problem before.
But when I install tf 2.2.0 I thought that you fixed this. But it turns out that I just forgot to install ffmpeg. And when I did this I meet "cored dumped" again.

**Comment by yongtang** [comment]
@avnx Yes AAC utilized ffmpeg's codec.

As FFmpeg is LGPL, we can only load it dynamically (our license is Apache 2.0).

The mp3 code is done through lame. I may need to take a closer look to see where the crash happens.

If possible, an upload of `file.mp3` will definitely help.

**Comment by avnx** [comment]
I figured you that encode_mp3 crashes when it is 1 channel audio. With 2 channels it works.
Actually this problem could be apparently connected with https://github.com/tensorflow/io/issues/974

[voice.mp3.zip](https://github.com/tensorflow/io/files/4663808/voice.mp3.zip)

**Comment by yongtang** [comment]
@avnx  Added PR #984 for the fix.

**Comment by yongtang** [comment]
@avnx The latest nightly should have fixed the mono encoding issue. Let me know if issue persists.
