### ISSUE TITLE
encode_mp3 squashes audio in a bad way

### ISSUE THREAD

**Issue by avnx** [tensorflow/io#974]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS (Bionic Beaver)
- TensorFlow installed from (source or binary): https://github.com/horovod/horovod/blob/master/Dockerfile.gpu (changed TENSORFLOW_VERSION=2.2.0)
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: used cpu

`python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`:
v2.2.0-rc4-8-g2b96f3662b 2.2.0

### After encoding and decoding an audio via mp3 codec it starts to sound 2 times faster and on higher frequency

```
import tensorflow as tf
from tensorflow_io.core.python.ops import audio_ops
from IPython.display import Audio, display

audio_path = 'path/to/mp3/file.mp3'
audio_data = tf.io.read_file(audio_path)
audio_mp3_original = audio_ops.decode_mp3(audio_data)
audio_mp3_encoded = audio_ops.encode_mp3(audio_mp3_original, 8000)
audio_mp3_decoded = audio_ops.decode_mp3(audio_mp3_encoded)

display(Audio(tf.transpose(tf.cast(audio_mp3_original * 2 ** 15, tf.int16)), rate=8000))
display(Audio(tf.transpose(tf.cast(audio_mp3_decoded * 2 ** 15, tf.int16)), rate=8000))
```

**Comment by yongtang** [comment]
@avnx Wondering if you can share a sample mp3 file that reproduces the issue? I can take a look.

**Comment by avnx** [comment]
> @avnx Wondering if you can share a sample mp3 file that reproduces the issue? I can take a look.

After you fixed https://github.com/tensorflow/io/issues/973  problem disappeared.
