### ISSUE TITLE
Drop pylint check?

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#980]
There were some discussions about dropping pylint before https://github.com/tensorflow/io/issues/810#issuecomment-600079829

Several big issues for pylint:
1. Slow: pylint runs check 1-2 second/file while black and pyupgrade runs very fast.
2. No auto-lint: It has to be adjusted manually. In some situations, you have to be really creative to make pylint happy.

Positive side:
- tensorflow core repo stays with pylint so it helps us to align with the community. Though we change the max-width to 88 (not 80), and use 4 spaces (not 2) already so our pylint script is not exactly from tensorflow's core repo already.

On a side node, to submit a PR to tensorflow core repo and make pylint happy is not very easy nowadays. This actually caused quite a few unnecessary commits in tensorflow' core repo.

We might consider dropping pylint if agree? @terrytangyuan @BryanCutler @vlasenkoalexey @dmitrievanthony

**Comment by terrytangyuan** [comment]
Yes agree that we can drop it.

**Comment by BryanCutler** [comment]
SGTM

**Comment by yongtang** [comment]
The issue can be closed now as PR #985 has been merged.
